using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text.RegularExpressions;
using Jondo.Unity.Server.Network;

namespace Jondo.Unity.Server.Handlers
{
    /// <summary>
    /// Player-facing command replies. The server console stays in its diagnostic language; only
    /// text sent to the game client is selected from this catalogue.
    /// </summary>
    internal static class CommandTexts
    {
        private static readonly IReadOnlyDictionary<string, string> Es = new Dictionary<string, string>
        {
            ["usage.kamas"] = "Uso: .kamas <cantidad> — por ejemplo .kamas 10000 (con menos delante, resta)",
            ["usage.level"] = "Uso: .level <nivel> — por ejemplo .level 200",
            ["usage.teleport"] = "Uso: .teleport [x,y] | .teleport <id de mapa> — por ejemplo .teleport [-1,0]",
            ["teleport.no_such_map"] = "No existe ningún mapa con el id {0}.",
            ["usage.relative"] = "Uso: .relative — pasa al siguiente MapId de las mismas coordenadas",
            ["usage.shop"] = "Uso: .shop — sin nada detrás",
            ["usage.size"] = "Uso: .size <n> — 100 es el tamaño normal, por ejemplo .size 200",
            ["usage.item"] = "Uso: .item <id> [cantidad] — por ejemplo .item 10784 1",
            ["usage.itemset"] = "Uso: .itemset <id de panoplia> — por ejemplo .itemset 1",
            ["usage.recipe"] = "Uso: .receta <id del objeto> [veces, de 1 a 100] — los ingredientes de su receta al inventario, por ejemplo .receta 44",
            ["usage.packets"] = "Uso: .packets [cuántos] — lo que el cliente manda y no atendemos",
            ["usage.guild"] = "Uso: .gremio crear <nombre> | invitar <personaje> | expulsar <personaje> | rango <personaje> <n> | salir | solicitar <gremio> [mensaje]",
            ["guild.create.nocharacter"] = "No hay ningún personaje activo.",
            ["guild.create.hasguild"] = "Ya tienes gremio.",
            ["guild.create.invalidname"] = "El nombre debe tener entre 3 y 30 caracteres: letras, números, espacios, guiones o apóstrofes.",
            ["guild.create.exists"] = "Ya existe un gremio llamado {0}.",
            ["guild.create.nogem"] = "Necesitas una guildalogema para fundar el gremio.",
            ["guild.create.done"] = "Gremio {0} fundado. Se ha consumido una guildalogema.",
            ["guild.invite.noguild"] = "No estás en ningún gremio.",
            ["guild.invite.notfound"] = "{0} no está conectado.",
            ["guild.invite.hasguild"] = "{0} ya tiene gremio.",
            ["guild.invite.sent"] = "Invitación enviada a {0}.",
            ["guild.left"] = "Has dejado el gremio {0}.",
            ["guild.noguild"] = "No estás en ningún gremio.",
            ["guild.kick.notleader"] = "Sólo el jefe del gremio puede expulsar.",
            ["guild.kick.notmember"] = "{0} no está en tu gremio.",
            ["guild.kick.self"] = "Para irte tú, usa .gremio salir.",
            ["guild.kick.done"] = "{0} expulsado del gremio.",
            ["guild.rank.notleader"] = "Sólo el jefe del gremio cambia rangos.",
            ["guild.rank.norank"] = "Ese rango no existe.",
            ["guild.rank.self"] = "El jefe no se cambia el rango a sí mismo.",
            ["guild.rank.done"] = "{0} pasa al rango {1}.",
            ["guild.apply.hasguild"] = "Ya tienes gremio.",
            ["guild.apply.notfound"] = "No hay ningún gremio que se llame {0}.",
            ["guild.apply.sent"] = "Candidatura enviada a {0}.",
            ["usage.raid"] = "Uso: .raid | comprar <1|2> | lanzar <1|2> | entrar | salir | fin | clasificacion [1|2]",
            ["usage.job"] = "Uso: .oficio <id del oficio> <nivel> — por ejemplo .oficio 27 200 (sastre); .oficio todos <nivel> para todos",
            ["usage.jobs"] = "Uso: .oficios [nivel] — todos los oficios a ese nivel, 200 si no se dice",
            ["jobs.result"] = "{0} oficios a nivel {1}.",
            ["job.result"] = "Oficio {0}: nivel {1}, antes {2}.",
            ["usage.forgegod"] = "Uso: .forjadios on | off",
            ["forgegod.on"] = "Modo forjadios activado: ninguna runa falla y no hay límites en la forja hasta que lo apagues o salgas.",
            ["forgegod.off"] = "Modo forjadios desactivado.",
            ["raid.unknown"] = "Esa raid no existe. 1 es la Sima del Gigalodón y 2 el Santuario de los Jardines Eternos.",
            ["raid.noguild"] = "No estás en ningún gremio.",
            ["raid.owned"] = "El gremio ya la tiene comprada.",
            ["raid.nokamas"] = "Al gremio no le llegan los kamas.",
            ["raid.notbought"] = "El gremio no la tiene comprada.",
            ["raid.already"] = "El gremio ya tiene una raid en marcha.",
            ["raid.none"] = "Tu gremio no tiene ninguna raid en marcha.",
            ["raid.inside"] = "Ya estás dentro.",
            ["raid.notinside"] = "No estás dentro de ninguna raid.",
            ["raid.full"] = "La raid está llena.",
            ["raid.offline"] = "No se te encuentra conectado.",
            ["raid.notcaptain"] = "Sólo la cierra quien la lanzó.",
            ["raid.status.none"] = "ninguna",
            ["raid.status.idle"] = "Sin raid en marcha. Compradas: {0}. Kamas de gremio: {1}.",
            ["raid.status.running"] = "{0}: quedan {1} min, {2} puntos, {3} dentro, planta {4}.",
            ["raid.status.light"] = " Luz por plantas: {0}. Sal en la bolsa: {1}.",
            ["light.lit"] = "La luminomáquina se traga {2} sales: la planta {0} queda a {1} franjas de luz.",
            ["light.nosalt"] = "No te llega la sal de las profundidades: hacen falta {0}.",
            ["light.changed"] = "La luz de la planta ha cambiado antes de que contestaras. Tu sal vuelve a la bolsa.",
            ["chest.dropped"] = "{0} tesoros al cofre: +{1} puntos. La raid va por {2}.",
            ["chest.taken"] = "Tomáis el cofre y escapáis con {0} puntos. Puesto {1} de la semana en {2}.",
            ["chest.taken.none"] = "Tomáis el cofre y escapáis con las manos vacías.",
            ["chest.gone"] = "Los tesoros ya no están en tu bolsa.",
            ["raid.ladder.head"] = "Clasificación de {0}, semana del {1}:",
            ["raid.ladder.row"] = "{0}. {1} — {2} puntos en {3} raid(s).{4}",
            ["raid.ladder.podium"] = " Ornamento {0}.",
            ["raid.ladder.empty"] = "Nadie ha puntuado esta semana en {0}.",
            ["command.unknown"] = "El comando {0} no existe. Los que hay: {1}.",
            ["command.denied"] = "No tienes permiso para usar {0}.",
            ["command.failed"] = "El comando {0} ha fallado: {1}",
            ["kamas.result"] = "Kamas: {0} ({1}{2}).",
            ["level.requested"] = " (se pidió {0})",
            ["level.omega"] = " Por encima de 200 no se reparten más puntos de característica.",
            ["level.result"] = "Nivel {0}{1}, antes {2}. Experiencia {3}. Puntos libres {4} de {5}. {6}{7}",
            ["spells.table_missing"] = "Hechizos sin tocar: la tabla de hechizos no está cargada.",
            ["spells.breed_missing"] = "Hechizos sin tocar: la raza {0} no tiene ninguno en los datos.",
            ["spells.result"] = "Hechizos: {0} (+{1}, -{2}, {3} cambian de grado).",
            ["teleport.in_fight"] = "No se puede teleportar en combate.",
            ["teleport.no_map"] = "No hay ningún mapa en [{0},{1}].",
            ["teleport.load_failed"] = "El mapa {0} de [{1},{2}] no se puede cargar.",
            ["teleport.multiple"] = " Había {0} mapas en esas coordenadas; se ha elegido el de la subzona con más casillas andables ({1}).",
            ["teleport.result"] = "En [{0},{1}]: mapa {2}, {3}, casilla {4}.{5}",
            ["map.subarea"] = "subzona {0}",
            ["relative.current_missing"] = "El mapa actual {0} no está en MapPositions.",
            ["relative.none"] = "No hay otro MapId en [{0},{1}].",
            ["relative.load_failed"] = "El mapa relativo {0} no se puede cargar.",
            ["relative.wrapped"] = " Vuelta al primer MapId.",
            ["relative.result"] = "Relative [{0},{1}]: {2} -> {3} ({4}/{5}), {6}, casilla {7}.{8}",
            ["shop.no_npcs"] = "No hay ningún NPC colocado en la base: no sé a qué mapa llevarte.",
            ["shop.map_missing"] = "El mapa de los vendedores ({0}) no está en los datos del mundo.",
            ["shop.unknown_place"] = "sitio desconocido",
            ["shop.result"] = "A la tienda: mapa {0} ({1}), {2} NPC, casilla {3}.",
            ["size.character_missing"] = "No encuentro tu personaje en la base para redibujarlo.",
            ["size.clamped"] = " (se pidió {0}; el tope va de {1} a {2})",
            ["size.result"] = "Tamaño {0} %{1}. El normal es {2}.",
            ["item.quantity"] = "La cantidad debe ser mayor que cero.",
            ["item.template_missing"] = "No existe la plantilla de objeto {0}.",
            ["item.added"] = "Objeto {0} x{1} añadido al inventario.",
            ["itemset.missing"] = "No existe la panoplia {0}.",
            ["itemset.templates_missing"] = " Plantillas ausentes: {0}.",
            ["itemset.added"] = "Panoplia {0}: {1}/{2} objetos añadidos.{3}",
            ["recipe.missing"] = "El objeto {0} no tiene receta.",
            ["recipe.added"] = "Receta de {0} x{1} (oficio {2}, nivel {3}): {4}.{5}",
            ["usage.dream"] = "Uso: .sueno [fila] — lleva tu sueño en curso a una sala de esa fila, o al Fin del sueño sin fila; las salas del camino cuentan como ganadas. Por ejemplo .sueno o .sueno 25",
            ["dream.none"] = "No tienes ningún sueño en curso: empieza uno en el pozo del Plano Astral.",
            ["dream.in_fight"] = "No se puede en combate.",
            ["dream.behind"] = "Ya estás en la fila {0}: un sueño sólo avanza.",
            ["dream.past"] = "El sueño llega hasta la fila {0}.",
            ["dream.skipped"] = "Sala {0} de la fila {1}: {2} combate(s) del camino dados por ganados; {3} puntos de sueño.",
            ["dream.completed"] = "¡Sueño completado! {0} oleada(s) superada(s) en el Fin del sueño: {1} retazo(s) de sueño.",
            ["dream.over"] = "El sueño ha terminado.",
            ["dream.arena"] = "Arena de Draconiros: la sala puede volver a intentarse.",
            ["dream.wave"] = "Oleada {0} del Fin del sueño: nivel {1}.",
            ["packets.none"] = "No hay ningún paquete sin atender apuntado.",
            ["packets.summary"] = "{0} forma(s) de {1} opcode(s): {2} sin atender, {3} silenciada(s), {4} ilegible(s)",
            ["packets.silenced"] = "silenciado",
            ["packets.undecodable"] = "ilegible",
            ["packets.unhandled"] = "sin atender",
        };

        private static readonly IReadOnlyDictionary<string, string> En = new Dictionary<string, string>
        {
            ["usage.kamas"] = "Usage: .kamas <amount> — for example .kamas 10000 (a negative amount removes kamas)",
            ["usage.level"] = "Usage: .level <level> — for example .level 200",
            ["usage.teleport"] = "Usage: .teleport [x,y] | .teleport <map id> — for example .teleport [-1,0]",
            ["teleport.no_such_map"] = "There is no map with id {0}.",
            ["usage.relative"] = "Usage: .relative — move to the next MapId at the same coordinates",
            ["usage.shop"] = "Usage: .shop — with no argument",
            ["usage.size"] = "Usage: .size <n> — 100 is the normal size, for example .size 200",
            ["usage.item"] = "Usage: .item <id> [quantity] — for example .item 10784 1",
            ["usage.itemset"] = "Usage: .itemset <set id> — for example .itemset 1",
            ["usage.recipe"] = "Usage: .receta <item id> [times, 1 to 100] — the ingredients of its recipe into the inventory, for example .receta 44",
            ["usage.packets"] = "Usage: .packets [count] — client messages the server does not handle",
            ["usage.guild"] = "Usage: .gremio crear <name> | invitar <character> | expulsar <personaje> | rango <personaje> <n> | salir | solicitar <guild> [message]",
            ["guild.create.nocharacter"] = "There is no active character.",
            ["guild.create.hasguild"] = "You already have a guild.",
            ["guild.create.invalidname"] = "The name must be 3 to 30 characters long and use letters, numbers, spaces, hyphens or apostrophes.",
            ["guild.create.exists"] = "A guild called {0} already exists.",
            ["guild.create.nogem"] = "You need a guildalogem to found the guild.",
            ["guild.create.done"] = "Guild {0} founded. One guildalogem was consumed.",
            ["guild.invite.noguild"] = "You are not in a guild.",
            ["guild.invite.notfound"] = "{0} is not connected.",
            ["guild.invite.hasguild"] = "{0} already has a guild.",
            ["guild.invite.sent"] = "Invitation sent to {0}.",
            ["guild.left"] = "You have left the guild {0}.",
            ["guild.noguild"] = "You are not in a guild.",
            ["guild.kick.notleader"] = "Only the guild leader can kick.",
            ["guild.kick.notmember"] = "{0} is not in your guild.",
            ["guild.kick.self"] = "To leave yourself, use .gremio salir.",
            ["guild.kick.done"] = "{0} kicked out of the guild.",
            ["guild.rank.notleader"] = "Only the guild leader changes ranks.",
            ["guild.rank.norank"] = "That rank does not exist.",
            ["guild.rank.self"] = "The leader cannot change their own rank.",
            ["guild.rank.done"] = "{0} is now rank {1}.",
            ["guild.apply.hasguild"] = "You already have a guild.",
            ["guild.apply.notfound"] = "There is no guild called {0}.",
            ["guild.apply.sent"] = "Application sent to {0}.",
            ["usage.raid"] = "Usage: .raid | comprar <1|2> | lanzar <1|2> | entrar | salir | fin | clasificacion [1|2]",
            ["usage.job"] = "Usage: .oficio <job id> <level> — for example .oficio 27 200 (tailor); .oficio all <level> for every job",
            ["usage.jobs"] = "Usage: .oficios [level] — every job at that level, 200 when none is given",
            ["jobs.result"] = "{0} jobs at level {1}.",
            ["job.result"] = "Job {0}: level {1}, previously {2}.",
            ["usage.forgegod"] = "Usage: .forgegod on | off",
            ["forgegod.on"] = "Forgegod mode on: no rune fails and the forge has no limits until you turn it off or log out.",
            ["forgegod.off"] = "Forgegod mode off.",
            ["raid.unknown"] = "No such raid. 1 is the Gigalodon Abyss, 2 the Eternal Gardens Sanctuary.",
            ["raid.noguild"] = "You are not in a guild.",
            ["raid.owned"] = "The guild already owns it.",
            ["raid.nokamas"] = "The guild cannot afford it.",
            ["raid.notbought"] = "The guild has not bought it.",
            ["raid.already"] = "The guild already has a raid running.",
            ["raid.none"] = "Your guild has no raid running.",
            ["raid.inside"] = "You are already inside.",
            ["raid.notinside"] = "You are not inside a raid.",
            ["raid.full"] = "The raid is full.",
            ["raid.offline"] = "You are not connected.",
            ["raid.notcaptain"] = "Only whoever launched it can close it.",
            ["raid.status.none"] = "none",
            ["raid.status.idle"] = "No raid running. Bought: {0}. Guild kamas: {1}.",
            ["raid.status.running"] = "{0}: {1} min left, {2} points, {3} inside, floor {4}.",
            ["raid.status.light"] = " Light per floor: {0}. Salt in the bag: {1}.",
            ["light.lit"] = "The luminomachine swallows {2} salt: floor {0} is left at {1} bands of light.",
            ["light.nosalt"] = "Not enough depths salt: {0} are needed.",
            ["light.changed"] = "The floor's light changed before you answered. Your salt is back in the bag.",
            ["chest.dropped"] = "{0} treasures into the chest: +{1} points. The raid is on {2}.",
            ["chest.taken"] = "You take the chest and run with {0} points. Place {1} of the week in {2}.",
            ["chest.taken.none"] = "You take the chest and run empty-handed.",
            ["chest.gone"] = "The treasures are no longer in your bag.",
            ["raid.ladder.head"] = "{0} ladder, week of {1}:",
            ["raid.ladder.row"] = "{0}. {1} — {2} points over {3} raid(s).{4}",
            ["raid.ladder.podium"] = " Ornament {0}.",
            ["raid.ladder.empty"] = "Nobody has scored in {0} this week.",
            ["command.unknown"] = "Command {0} does not exist. Available commands: {1}.",
            ["command.denied"] = "You do not have permission to use {0}.",
            ["command.failed"] = "Command {0} failed: {1}",
            ["kamas.result"] = "Kamas: {0} ({1}{2}).",
            ["level.requested"] = " (requested {0})",
            ["level.omega"] = " Levels above 200 do not grant characteristic points.",
            ["level.result"] = "Level {0}{1}, previously {2}. Experience {3}. Free points {4} of {5}. {6}{7}",
            ["spells.table_missing"] = "Spells unchanged: the spell table is not loaded.",
            ["spells.breed_missing"] = "Spells unchanged: breed {0} has no spells in the data.",
            ["spells.result"] = "Spells: {0} (+{1}, -{2}, {3} changed grade).",
            ["teleport.in_fight"] = "You cannot teleport during a fight.",
            ["teleport.no_map"] = "There is no map at [{0},{1}].",
            ["teleport.load_failed"] = "Map {0} at [{1},{2}] cannot be loaded.",
            ["teleport.multiple"] = " There were {0} maps at those coordinates; the sub-area with the most walkable cells was selected ({1}).",
            ["teleport.result"] = "At [{0},{1}]: map {2}, {3}, cell {4}.{5}",
            ["map.subarea"] = "sub-area {0}",
            ["relative.current_missing"] = "Current map {0} is not in MapPositions.",
            ["relative.none"] = "There is no other MapId at [{0},{1}].",
            ["relative.load_failed"] = "Relative map {0} cannot be loaded.",
            ["relative.wrapped"] = " Back to the first MapId.",
            ["relative.result"] = "Relative [{0},{1}]: {2} -> {3} ({4}/{5}), {6}, cell {7}.{8}",
            ["shop.no_npcs"] = "There are no NPC spawns in the database, so there is no shop map to use.",
            ["shop.map_missing"] = "The vendor map ({0}) is missing from the world data.",
            ["shop.unknown_place"] = "unknown location",
            ["shop.result"] = "Shop: map {0} ({1}), {2} NPC, cell {3}.",
            ["size.character_missing"] = "Your character could not be found in the database for its look refresh.",
            ["size.clamped"] = " (requested {0}; limits are {1} to {2})",
            ["size.result"] = "Size {0} %{1}. Normal size is {2}.",
            ["item.quantity"] = "Quantity must be greater than zero.",
            ["item.template_missing"] = "Item template {0} does not exist.",
            ["item.added"] = "Item {0} x{1} added to the inventory.",
            ["itemset.missing"] = "Item set {0} does not exist.",
            ["itemset.templates_missing"] = " Missing templates: {0}.",
            ["itemset.added"] = "Item set {0}: {1}/{2} items added.{3}",
            ["recipe.missing"] = "Item {0} has no recipe.",
            ["recipe.added"] = "Recipe of {0} x{1} (job {2}, level {3}): {4}.{5}",
            ["usage.dream"] = "Usage: .dream [row] — takes your dream in progress to a room of that row, or to the dream's end with no row; the rooms on the way count as won. For example .dream or .dream 25",
            ["dream.none"] = "You have no dream in progress: start one at the well of the Astral Plane.",
            ["dream.in_fight"] = "Not during a fight.",
            ["dream.behind"] = "You are already on row {0}: a dream only goes forward.",
            ["dream.past"] = "The dream goes down to row {0}.",
            ["dream.skipped"] = "Room {0} on row {1}: {2} fight(s) on the way counted as won; {3} dream points.",
            ["dream.completed"] = "Dream completed! {0} wave(s) cleared at the dream's end: {1} dream fragment(s).",
            ["dream.over"] = "The dream is over.",
            ["dream.arena"] = "Draconiros arena: the room can be tried again.",
            ["dream.wave"] = "Wave {0} of the dream's end: level {1}.",
            ["packets.none"] = "No unhandled packets have been recorded.",
            ["packets.summary"] = "{0} shape(s) from {1} opcode(s): {2} unhandled, {3} silenced, {4} undecodable",
            ["packets.silenced"] = "silenced",
            ["packets.undecodable"] = "undecodable",
            ["packets.unhandled"] = "unhandled",
        };

        private static readonly IReadOnlyDictionary<string, string> Fr = new Dictionary<string, string>
        {
            ["usage.kamas"] = "Utilisation : .kamas <quantité> — exemple : .kamas 10000 (une valeur négative en retire)",
            ["usage.level"] = "Utilisation : .level <niveau> — exemple : .level 200",
            ["usage.teleport"] = "Utilisation : .teleport [x,y] | .teleport <id de carte> — exemple : .teleport [-1,0]",
            ["teleport.no_such_map"] = "Aucune carte ne porte l'identifiant {0}.",
            ["usage.relative"] = "Utilisation : .relative — passe au MapId suivant aux mêmes coordonnées",
            ["usage.shop"] = "Utilisation : .shop — sans argument",
            ["usage.size"] = "Utilisation : .size <n> — 100 est la taille normale, exemple : .size 200",
            ["usage.item"] = "Utilisation : .item <id> [quantité] — exemple : .item 10784 1",
            ["usage.itemset"] = "Utilisation : .itemset <id de panoplie> — exemple : .itemset 1",
            ["usage.recipe"] = "Utilisation : .receta <id de l'objet> [fois, de 1 à 100] — les ingrédients de sa recette dans l'inventaire, exemple : .receta 44",
            ["usage.packets"] = "Utilisation : .packets [nombre] — messages du client non traités",
            ["usage.guild"] = "Utilisation : .gremio crear <nom> | invitar <personnage> | expulsar <personaje> | rango <personaje> <n> | salir | solicitar <guilde> [message]",
            ["guild.create.nocharacter"] = "Aucun personnage n'est actif.",
            ["guild.create.hasguild"] = "Vous avez déjà une guilde.",
            ["guild.create.invalidname"] = "Le nom doit contenir entre 3 et 30 caractères : lettres, chiffres, espaces, tirets ou apostrophes.",
            ["guild.create.exists"] = "Une guilde nommée {0} existe déjà.",
            ["guild.create.nogem"] = "Il vous faut une guildalogemme pour fonder la guilde.",
            ["guild.create.done"] = "Guilde {0} fondée. Une guildalogemme a été consommée.",
            ["guild.invite.noguild"] = "Vous n'êtes dans aucune guilde.",
            ["guild.invite.notfound"] = "{0} n'est pas connecté.",
            ["guild.invite.hasguild"] = "{0} a déjà une guilde.",
            ["guild.invite.sent"] = "Invitation envoyée à {0}.",
            ["guild.left"] = "Vous avez quitté la guilde {0}.",
            ["guild.noguild"] = "Vous n'êtes dans aucune guilde.",
            ["guild.kick.notleader"] = "Seul le meneur de la guilde peut exclure.",
            ["guild.kick.notmember"] = "{0} n'est pas dans votre guilde.",
            ["guild.kick.self"] = "Pour partir vous-même, utilisez .gremio salir.",
            ["guild.kick.done"] = "{0} exclu de la guilde.",
            ["guild.rank.notleader"] = "Seul le meneur change les rangs.",
            ["guild.rank.norank"] = "Ce rang n'existe pas.",
            ["guild.rank.self"] = "Le meneur ne change pas son propre rang.",
            ["guild.rank.done"] = "{0} passe au rang {1}.",
            ["guild.apply.hasguild"] = "Vous avez déjà une guilde.",
            ["guild.apply.notfound"] = "Aucune guilde ne s'appelle {0}.",
            ["guild.apply.sent"] = "Candidature envoyée à {0}.",
            ["usage.raid"] = "Utilisation : .raid | comprar <1|2> | lanzar <1|2> | entrar | salir | fin | clasificacion [1|2]",
            ["usage.job"] = "Utilisation : .oficio <id du métier> <niveau> — exemple : .oficio 27 200 (tailleur) ; .oficio tous <niveau> pour tous",
            ["usage.jobs"] = "Utilisation : .oficios [niveau] — tous les métiers à ce niveau, 200 par défaut",
            ["jobs.result"] = "{0} métiers au niveau {1}.",
            ["job.result"] = "Métier {0} : niveau {1}, auparavant {2}.",
            ["usage.forgegod"] = "Utilisation : .forgedieu on | off",
            ["forgegod.on"] = "Mode forgedieu activé : aucune rune n'échoue et la forge n'a plus de limites jusqu'à ce que vous le désactiviez ou vous déconnectiez.",
            ["forgegod.off"] = "Mode forgedieu désactivé.",
            ["raid.unknown"] = "Ce raid n'existe pas. 1 le Gouffre du Gigalodon, 2 le Sanctuaire des Jardins éternels.",
            ["raid.noguild"] = "Vous n'êtes dans aucune guilde.",
            ["raid.owned"] = "La guilde l'a déjà acheté.",
            ["raid.nokamas"] = "La guilde n'a pas assez de kamas.",
            ["raid.notbought"] = "La guilde ne l'a pas acheté.",
            ["raid.already"] = "La guilde a déjà un raid en cours.",
            ["raid.none"] = "Votre guilde n'a aucun raid en cours.",
            ["raid.inside"] = "Vous êtes déjà dedans.",
            ["raid.notinside"] = "Vous n'êtes dans aucun raid.",
            ["raid.full"] = "Le raid est complet.",
            ["raid.offline"] = "Vous n'êtes pas connecté.",
            ["raid.notcaptain"] = "Seul celui qui l'a lancé peut le fermer.",
            ["raid.status.none"] = "aucun",
            ["raid.status.idle"] = "Aucun raid en cours. Achetés : {0}. Kamas de guilde : {1}.",
            ["raid.status.running"] = "{0} : {1} min restantes, {2} points, {3} dedans, étage {4}.",
            ["raid.status.light"] = " Lumière par étage : {0}. Sel dans le sac : {1}.",
            ["light.lit"] = "La luminomachine avale {2} sels : l'étage {0} reste à {1} bandes de lumière.",
            ["light.nosalt"] = "Il vous manque du sel des profondeurs : il en faut {0}.",
            ["light.changed"] = "La lumière de l'étage a changé avant votre réponse. Votre sel revient dans le sac.",
            ["chest.dropped"] = "{0} trésors dans le coffre : +{1} points. Le raid en est à {2}.",
            ["chest.taken"] = "Vous prenez le coffre et fuyez avec {0} points. Place {1} de la semaine dans {2}.",
            ["chest.taken.none"] = "Vous prenez le coffre et fuyez les mains vides.",
            ["chest.gone"] = "Les trésors ne sont plus dans votre sac.",
            ["raid.ladder.head"] = "Classement de {0}, semaine du {1} :",
            ["raid.ladder.row"] = "{0}. {1} — {2} points en {3} raid(s).{4}",
            ["raid.ladder.podium"] = " Ornement {0}.",
            ["raid.ladder.empty"] = "Personne n'a marqué cette semaine dans {0}.",
            ["command.unknown"] = "La commande {0} n'existe pas. Commandes disponibles : {1}.",
            ["command.denied"] = "Tu n'as pas la permission d'utiliser {0}.",
            ["command.failed"] = "La commande {0} a échoué : {1}",
            ["kamas.result"] = "Kamas : {0} ({1}{2}).",
            ["level.requested"] = " (niveau demandé : {0})",
            ["level.omega"] = " Les niveaux supérieurs à 200 ne donnent pas de points de caractéristique.",
            ["level.result"] = "Niveau {0}{1}, auparavant {2}. Expérience {3}. Points disponibles : {4}/{5}. {6}{7}",
            ["spells.table_missing"] = "Sorts inchangés : la table des sorts n'est pas chargée.",
            ["spells.breed_missing"] = "Sorts inchangés : la classe {0} n'en possède aucun dans les données.",
            ["spells.result"] = "Sorts : {0} (+{1}, -{2}, {3} changent de rang).",
            ["teleport.in_fight"] = "Téléportation impossible pendant un combat.",
            ["teleport.no_map"] = "Aucune carte trouvée en [{0},{1}].",
            ["teleport.load_failed"] = "La carte {0} en [{1},{2}] ne peut pas être chargée.",
            ["teleport.multiple"] = " {0} cartes existent à ces coordonnées ; celle de la sous-zone avec le plus de cellules praticables a été choisie ({1}).",
            ["teleport.result"] = "En [{0},{1}] : carte {2}, {3}, cellule {4}.{5}",
            ["map.subarea"] = "sous-zone {0}",
            ["relative.current_missing"] = "La carte actuelle {0} est absente de MapPositions.",
            ["relative.none"] = "Aucun autre MapId en [{0},{1}].",
            ["relative.load_failed"] = "La carte relative {0} ne peut pas être chargée.",
            ["relative.wrapped"] = " Retour au premier MapId.",
            ["relative.result"] = "Relative [{0},{1}] : {2} -> {3} ({4}/{5}), {6}, cellule {7}.{8}",
            ["shop.no_npcs"] = "Aucun PNJ vendeur n'est enregistré dans la base.",
            ["shop.map_missing"] = "La carte des vendeurs ({0}) est absente des données du monde.",
            ["shop.unknown_place"] = "lieu inconnu",
            ["shop.result"] = "Boutique : carte {0} ({1}), {2} PNJ, cellule {3}.",
            ["size.character_missing"] = "Ton personnage est introuvable dans la base pour actualiser son apparence.",
            ["size.clamped"] = " (taille demandée : {0} ; limites : {1} à {2})",
            ["size.result"] = "Taille : {0} %{1}. Taille normale : {2}.",
            ["item.quantity"] = "La quantité doit être supérieure à zéro.",
            ["item.template_missing"] = "Le modèle d'objet {0} n'existe pas.",
            ["item.added"] = "Objet {0} x{1} ajouté à l'inventaire.",
            ["itemset.missing"] = "La panoplie {0} n'existe pas.",
            ["itemset.templates_missing"] = " Modèles absents : {0}.",
            ["itemset.added"] = "Panoplie {0} : {1}/{2} objets ajoutés.{3}",
            ["recipe.missing"] = "L'objet {0} n'a pas de recette.",
            ["recipe.added"] = "Recette de {0} x{1} (métier {2}, niveau {3}) : {4}.{5}",
            ["usage.dream"] = "Utilisation : .reve [rangée] — mène votre rêve en cours à une salle de cette rangée, ou à la Fin du rêve sans rangée ; les salles du chemin comptent comme gagnées. Exemple : .reve ou .reve 25",
            ["dream.none"] = "Vous n'avez aucun rêve en cours : commencez-en un au puits du Plan Astral.",
            ["dream.in_fight"] = "Impossible en combat.",
            ["dream.behind"] = "Vous êtes déjà à la rangée {0} : un rêve ne fait qu'avancer.",
            ["dream.past"] = "Le rêve va jusqu'à la rangée {0}.",
            ["dream.skipped"] = "Salle {0} de la rangée {1} : {2} combat(s) du chemin comptés comme gagnés ; {3} points de rêve.",
            ["dream.completed"] = "Rêve accompli ! {0} vague(s) vaincue(s) à la Fin du rêve : {1} bribe(s) de rêve.",
            ["dream.over"] = "Le rêve est terminé.",
            ["dream.arena"] = "Arène de Draconiros : la salle peut être retentée.",
            ["dream.wave"] = "Vague {0} de la Fin du rêve : niveau {1}.",
            ["packets.none"] = "Aucun paquet non traité n'a été enregistré.",
            ["packets.summary"] = "{0} forme(s) pour {1} opcode(s) : {2} non traitée(s), {3} ignorée(s), {4} illisible(s)",
            ["packets.silenced"] = "ignoré",
            ["packets.undecodable"] = "illisible",
            ["packets.unhandled"] = "non traité",
        };

        static CommandTexts()
        {
            AssertSameKeys(En, "en");
            AssertSameKeys(Fr, "fr");
        }

        public static string Get(string key, params object[] values)
            => Get(SessionContext.State.Language, key, values);

        internal static void AssertCatalogs() { }

        internal static string Get(string language, string key, params object[] values)
        {
            var catalog = language.Trim().ToLowerInvariant() switch
            {
                "en" => En,
                "fr" => Fr,
                _ => Es,
            };
            if (!catalog.TryGetValue(key, out string? format)) format = Es[key];
            return values.Length == 0
                ? format
                : string.Format(CultureInfo.InvariantCulture, format, values);
        }

        private static void AssertSameKeys(IReadOnlyDictionary<string, string> catalog, string language)
        {
            foreach (string key in Es.Keys)
            {
                if (!catalog.ContainsKey(key))
                    throw new InvalidOperationException($"Command text '{key}' is missing for {language}.");
                if (!Placeholders(Es[key]).SetEquals(Placeholders(catalog[key])))
                    throw new InvalidOperationException(
                        $"Command text '{key}' does not use the same placeholders in {language}.");
            }
            if (catalog.Count != Es.Count)
                throw new InvalidOperationException($"Command text catalogue {language} has unexpected keys.");
        }

        private static HashSet<int> Placeholders(string format)
        {
            var result = new HashSet<int>();
            foreach (Match match in Regex.Matches(format, @"\{(?<index>\d+)(?:[^}]*)\}"))
            {
                result.Add(int.Parse(match.Groups["index"].Value, CultureInfo.InvariantCulture));
            }
            return result;
        }
    }
}
