using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using Jondo.Unity.Launcher;

namespace Jondo.Unity.World.Emotes
{
    /// <summary>One emote, as the client's emoticon table describes it.</summary>
    public sealed class Emote
    {
        public int Id { get; init; }

        /// <summary>The animation khh names when it is played: "AnimEmoteSit" for 1.</summary>
        public string Anim { get; init; } = "";

        /// <summary>Milliseconds, as the client data gives them.</summary>
        public int Cooldown { get; init; }

        /// <summary>Milliseconds the animation lasts, as the client data gives it.</summary>
        public int Duration { get; init; }

        public bool AllowOnMount { get; init; }

        /// <summary>An aura rather than a gesture. The captures never answer one with khh.</summary>
        public bool Aura { get; init; }

        /// <summary>Held after it plays (sitting, the juggler): the client keeps the pose.</summary>
        public bool Persistent { get; init; }

        /// <summary>What the client itself asks before offering it: "Pw=2" for the guild banner.</summary>
        public string Criterion { get; init; } = "";
    }

    /// <summary>
    /// The 324 emotes, read out of <c>datos/emotes_3.6.10.10.json</c>.
    /// </summary>
    /// <remarks>
    /// Generated by <c>tools/extract_emotes.py</c> from the client's emoticon table. The server needs
    /// it for two things: the animation name the broadcast carries, and the rules the captures
    /// show it enforcing — no emote on a mount unless the emote allows it.
    /// </remarks>
    public sealed class EmoteCatalogue
    {
        private readonly Dictionary<int, Emote> _byId = new Dictionary<int, Emote>();

        public EmoteCatalogue(Action<string>? report = null)
        {
            string path = Paths.EmotesJson;
            if (!File.Exists(path))
            {
                report?.Invoke($"{Path.GetFileName(path)} is not there; no emote can be played. " +
                               "Run tools/extract_emotes.py to build it.");
                return;
            }

            try
            {
                using var doc = JsonDocument.Parse(File.ReadAllText(path));
                if (!doc.RootElement.TryGetProperty("emotes", out var table)) return;

                foreach (var entry in table.EnumerateObject())
                {
                    if (!int.TryParse(entry.Name, out int id)) continue;
                    var row = entry.Value;
                    _byId[id] = new Emote
                    {
                        Id = id,
                        Anim = Text(row, "anim"),
                        Cooldown = (int)Long(row, "cooldown"),
                        Duration = (int)Long(row, "duration"),
                        AllowOnMount = Long(row, "allowOnMount") != 0,
                        Aura = Long(row, "aura") != 0,
                        Persistent = Long(row, "persistent") != 0,
                        Criterion = Text(row, "criterion"),
                    };
                }
            }
            catch (Exception ex)
            {
                report?.Invoke($"{Path.GetFileName(path)} is unreadable: {ex.Message}");
            }
        }

        public bool Ready => _byId.Count > 0;
        public int Count => _byId.Count;

        public Emote? Of(int id) => _byId.TryGetValue(id, out var emote) ? emote : null;

        private static string Text(JsonElement row, string name)
            => row.TryGetProperty(name, out var v) && v.ValueKind == JsonValueKind.String ? (v.GetString() ?? "") : "";

        private static long Long(JsonElement row, string name)
            => row.TryGetProperty(name, out var v) && v.TryGetInt64(out long n) ? n : 0;
    }

    /// <summary>Why an emote was not played. The real server answers none of these: it stays silent.</summary>
    public enum EmoteRefusal
    {
        None = 0,
        Unknown,
        NotOwned,
        OnMount,
        TooSoon,
        Aura,
    }

    /// <summary>
    /// When an emote plays, and what a new character starts with.
    /// </summary>
    /// <remarks>
    /// Everything here is read off the captures, and every refusal is silent there: the client
    /// asks with khl and simply gets no khh back.
    /// </remarks>
    public static class EmoteRules
    {
        /// <summary>
        /// What a character has before earning any: sitting, the guild and alliance banners, and
        /// 127. Measured: the three captures that create a character or enter the world with a new
        /// one all carry exactly this khn.
        /// </summary>
        public static readonly IReadOnlyList<int> Starting = new[] { 1, 97, 98, 127 };

        /// <summary>
        /// How long after one emote the next is refused, in milliseconds. INFERRED.
        /// </summary>
        /// <remarks>
        /// In <c>Emotes\captura de muchas actitudes</c> five requests go unanswered, all of them
        /// 1.76 to 2.08 seconds after the previous emote played, and every request 2.61 seconds or
        /// more after one is answered — including one 2.93 seconds after an emote whose own
        /// cooldown is 3.5 seconds, so it is not the emote's cooldown. The real threshold is
        /// somewhere in between; this is that gap, rounded.
        /// </remarks>
        public const int MinimumGapMs = 2500;

        /// <summary>
        /// Whether an emote can be played now, and if not why.
        /// </summary>
        /// <remarks>
        /// Auras are refused as well: in eleven captures the client sends khl for an aura (171,
        /// 206, 22) and not one of them gets a khh back. What the server does with them instead
        /// is not in the captures.
        /// </remarks>
        public static EmoteRefusal Check(Emote? emote, bool owned, bool mounted,
                                         DateTime now, DateTime lastPlayed)
        {
            if (emote == null) return EmoteRefusal.Unknown;
            if (!owned) return EmoteRefusal.NotOwned;
            if (emote.Aura) return EmoteRefusal.Aura;
            if (mounted && !emote.AllowOnMount) return EmoteRefusal.OnMount;
            if (lastPlayed != DateTime.MinValue && (now - lastPlayed).TotalMilliseconds < MinimumGapMs)
            {
                return EmoteRefusal.TooSoon;
            }

            return EmoteRefusal.None;
        }
    }
}
