using System;

namespace Jondo.Unity.World.Content
{
    /// <summary>
    /// Which of the three layers a row came from. The order is the precedence: a row from a higher
    /// layer replaces the same row from a lower one.
    /// </summary>
    /// <remarks>
    /// The emulator's data lives in three places that cannot be edited the same way, and pretending
    /// otherwise is what loses work. <c>dofus3_data/</c> is a raw dump of the client and is read
    /// only; <c>datos/*.json</c> and <c>world.db</c> are regenerated by the tools in
    /// <c>tools/</c> whenever anybody re-runs them, so a hand edit there disappears without a
    /// word; and <c>world.db</c> is a 240 MB binary, which no pull request can review and no two
    /// people can merge.
    ///
    /// So the only layer anybody edits by hand is <see cref="Authored"/>, it is never regenerated,
    /// and it always wins.
    /// </remarks>
    public enum ContentLayer
    {
        /// <summary>Generated from the client dump. Regenerable, nobody edits it.</summary>
        Base = 0,

        /// <summary>Learned from packet captures. Regenerable, nobody edits it.</summary>
        Measured = 1,

        /// <summary>Decided by a person. Never regenerated, always wins.</summary>
        Authored = 2,
    }

    /// <summary>
    /// Where a single row came from.
    /// </summary>
    /// <remarks>
    /// This is the field that stops the whole thing rotting. Six months from now nobody will
    /// remember whether a cell number was measured off a capture or typed in by hand, and without
    /// somewhere to write it down the two become indistinguishable — which is the one mistake this
    /// project has spent a year avoiding everywhere else.
    ///
    /// <see cref="Source"/> is meant to be shown to a human, not parsed: the name of the file, or
    /// of the capture, that the row came out of.
    /// </remarks>
    public readonly struct Origin : IEquatable<Origin>
    {
        public Origin(ContentLayer layer, string source)
        {
            Layer = layer;
            Source = source ?? "";
        }

        public ContentLayer Layer { get; }

        /// <summary>The file or capture this came out of. Free text, for a person to read.</summary>
        public string Source { get; }

        public static Origin Base(string source) => new Origin(ContentLayer.Base, source);
        public static Origin Measured(string source) => new Origin(ContentLayer.Measured, source);
        public static Origin Authored(string source) => new Origin(ContentLayer.Authored, source);

        public bool Equals(Origin other) => Layer == other.Layer && Source == other.Source;
        public override bool Equals(object? obj) => obj is Origin other && Equals(other);
        public override int GetHashCode() => HashCode.Combine(Layer, Source);

        public override string ToString()
            => Source.Length == 0 ? Layer.ToString() : $"{Layer} · {Source}";
    }

    /// <summary>A value together with where it came from.</summary>
    public readonly struct Sourced<T>
    {
        public Sourced(T value, Origin from)
        {
            Value = value;
            From = from;
        }

        public T Value { get; }
        public Origin From { get; }

        public override string ToString() => $"{Value} ({From})";
    }
}
