using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;

namespace Jondo.Unity.Launcher.Managers
{
    /// <summary>
    /// Character heads, as the client itself defines them.
    ///
    /// The data comes from heads.json, generated by tools/extract_heads.py out of the client's
    /// heads bundle. Each head has an id (the one the creation screen sends) and a skin (the one
    /// that travels inside the look).
    ///
    /// A character's skins go out in this order, checked against the creation capture:
    ///
    ///     skins = [ breed base skin, head skin, ...equipment skins ]
    ///
    /// Leaving the head out is not cosmetic: the client draws the character with no face.
    /// </summary>
    public static class HeadTable
    {
        public sealed class Head
        {
            public int Skin { get; set; }
            public int Breed { get; set; }
            public int Gender { get; set; }
            /// <summary>Whether the creation screen offers it.</summary>
            public bool Creation { get; set; }
        }

        private static readonly Dictionary<int, Head> _heads = new Dictionary<int, Head>();
        private static readonly Dictionary<string, int> _defaults = new Dictionary<string, int>();
        private static bool _loaded;
        private static readonly object _lock = new object();

        private static void Ensure()
        {
            if (_loaded) return;
            lock (_lock)
            {
                if (_loaded) return;
                _loaded = true;
                try
                {
                    string path = Paths.HeadsJson;
                    if (!File.Exists(path))
                    {
                        Console.WriteLine($"[Heads] Cannot find {Path.GetFileName(path)}. " +
                                          "Run tools/extract_heads.py to generate it.");
                        return;
                    }

                    using var doc = JsonDocument.Parse(File.ReadAllText(path));
                    var root = doc.RootElement;

                    if (root.TryGetProperty("heads", out var heads))
                    {
                        foreach (var entry in heads.EnumerateObject())
                        {
                            if (!int.TryParse(entry.Name, out int id)) continue;
                            _heads[id] = new Head
                            {
                                Skin = ReadInt(entry.Value, "skin"),
                                Breed = ReadInt(entry.Value, "breed"),
                                Gender = ReadInt(entry.Value, "gender"),
                                Creation = ReadInt(entry.Value, "creation") != 0
                            };
                        }
                    }

                    if (root.TryGetProperty("defaults", out var defaults))
                    {
                        foreach (var entry in defaults.EnumerateObject())
                        {
                            if (entry.Value.TryGetInt32(out int id)) _defaults[entry.Name] = id;
                        }
                    }

                    Console.WriteLine($"[Heads] Loaded {_heads.Count} heads " +
                                      $"and {_defaults.Count} defaults by breed and sex.");
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"[Heads] Error loading the heads: {ex.Message}");
                }
            }
        }

        private static int ReadInt(JsonElement el, string name)
        {
            return el.TryGetProperty(name, out var v) && v.TryGetInt32(out int n) ? n : 0;
        }

        /// <summary>The head the creation screen offers first for that breed and sex.</summary>
        public static int DefaultHeadId(int breedId, int sex)
        {
            Ensure();
            if (_defaults.TryGetValue($"{breedId}_{(sex == 1 ? 1 : 0)}", out int id)) return id;
            return 0;
        }

        /// <summary>
        /// Skin of a head. When the character carries no head, or carries one that does not
        /// exist, it falls back to the breed default rather than sending nothing.
        /// </summary>
        public static int SkinFor(int headId, int breedId, int sex)
        {
            Ensure();
            if (headId > 0 && _heads.TryGetValue(headId, out var head) && head.Skin > 0)
            {
                return head.Skin;
            }

            int fallback = DefaultHeadId(breedId, sex);
            if (fallback > 0 && _heads.TryGetValue(fallback, out var byDefault)) return byDefault.Skin;
            return 0;
        }

        /// <summary>Whether a head can be picked for that breed and sex when creating a character.</summary>
        public static bool IsValidAtCreation(int headId, int breedId, int sex)
        {
            Ensure();
            return _heads.TryGetValue(headId, out var head)
                   && head.Creation
                   && head.Breed == breedId
                   && head.Gender == (sex == 1 ? 1 : 0);
        }
    }
}
