using System;
using System.IO;

namespace Jondo.Unity.Launcher
{
    /// <summary>
    /// Centralized resolution of the emulator's paths.
    ///
    /// Every file used to carry absolute paths to C:\Jondo scattered all over the code (28 of
    /// them in total). Now everything the emulator needs lives inside the emulator folder and the
    /// root is derived at run time from the assembly directory.
    ///
    /// La raíz no guarda ficheros sueltos: quien se baje el emulador tiene que ver el .exe y poco
    /// más, sin dudar de qué abrir. Los datos van en <c>datos\</c> y las bases en <c>bases\</c>.
    /// La búsqueda mira esas carpetas primero y la raíz después, así que una instalación a medio
    /// mover sigue arrancando igual; y si tampoco está ahí, se cae a la ruta histórica.
    /// </summary>
    public static class Paths
    {
        /// <summary>Historical location of the data, used as a fallback.</summary>
        public const string LegacyRoot = @"C:\Jondo 3.6.10.10";

        /// <summary>Dónde se busca cada fichero, en este orden.</summary>
        private static readonly string[] SubFolders = { "datos", "bases", "" };

        /// <summary>
        /// Data root of the emulator: the directory where the running assembly lives.
        /// With the current deployment that is the "Jondo Unity Emulator" folder.
        /// </summary>
        public static string Root { get; } = ResolveRoot();

        /// <summary>Dofus client folder (it lives outside the emulator root).</summary>
        public static string ClientDir
        {
            get
            {
                string candidate3610 = Path.GetFullPath(Path.Combine(Root, "..", "Cliente 3.6.10.10"));
                if (Directory.Exists(candidate3610)) return candidate3610;
                string fallback = Path.Combine(LegacyRoot, "Cliente 3.6.10.10");
                if (Directory.Exists(fallback)) return fallback;
                return Path.Combine(@"C:\Jondo", "DofusClient");
            }
        }

        // ─── Databases ──────────────────────────────────────────────────────────
        // Las bases se crean solas la primera vez, así que van por ResolveWritable: si todavía no
        // existen, la ruta que sale es la de bases\ y no la de la raíz.
        public static string WorldDb => ResolveWritable("world.db", DatabaseFolder);
        public static string AuthDb => ResolveWritable("auth.db", DatabaseFolder);
        public static string WorldZip => Resolve("world.zip");

        public static string WorldConnectionString => "Data Source=" + WorldDb.Replace('\\', '/');
        public static string AuthConnectionString => "Data Source=" + AuthDb.Replace('\\', '/');

        // ─── Game data ──────────────────────────────────────────────────────────
        public static string DataDir => ResolveDir("dofus3_data");
        public static string WalkableCellsJson => Resolve("map_walkable_cells.json");
        // FIGHT cells: walkable (mov=1, nonWalkableDuringFight=0) and opaque (los=0).
        // Generated by extract_fight_cells.py from the client bundles.
        public static string FightCellsJson => Resolve("map_fight_cells.json");
        // Accumulated experience required for each character level.
        // Generated by extract_character_xp.py from the client bundles.
        public static string CharacterXpJson => Resolve("character_xp.json");
        // Base look of each breed (bones, skins, scales and default colors).
        // Generated by extract_breed_looks.py from the client bundles.
        public static string BreedLooksJson => Resolve("breed_looks.json");
        // Character heads: the skin of each one and which is the default per breed and sex.
        // Generated by extract_heads.py from the client bundles.
        public static string HeadsJson => Resolve("heads.json");
        // What a point of each characteristic costs, per breed and per band.
        // Generated by extract_breed_stats.py from the client bundles.
        public static string BreedStatsJson => Resolve("breed_stats.json");
        // The sets, and what wearing several pieces of one is worth.
        // Generated by extract_item_sets.py from the dofusdude dump.
        public static string ItemSetsJson => Resolve("item_sets.json");
        // En qué campo del mensaje va el valor de cada efecto de objeto, aprendido de la captura.
        public static string EffectFieldsJson => Resolve("item_effect_fields.json");
        // The dungeons: their rooms, their entrance and their exit.
        // Generated by extract_dungeons.py from the client bundles.
        public static string DungeonsJson => Resolve("dungeons.json");
        // Lo que se puede clicar en cada mapa, con su casilla y su dibujo, y los zaaps con su
        // mapa y su subzona. Los genera extract_interactivos.py de los bundles del cliente.
        public static string InteractiveElementsJson => Resolve("interactive_elements.json");

        /// <summary>
        /// Los pasos entre mapas, normalizados de la tabla interactive_skills de Giny 2.68. El
        /// servidor los valida contra sus propios datos y sólo importa los que sobreviven.
        /// </summary>
        public static string InteractiveTeleportsJson => Resolve("interactive_teleports_giny_2.68.json");

        /// <summary>
        /// Los pasos sacados del grafo de navegación del cliente de Dofus 2.73, que los genera
        /// tools/extraer_world_graph.py. Rellenan los huecos que el catálogo de Giny no cubre.
        ///
        /// Van en un fichero aparte y NO mezclados con los de Giny a propósito: éstos traen la
        /// casilla de llegada aproximada —el grafo no la lleva— y eso tiene que poder distinguirse
        /// de un vistazo, tanto aquí como en la columna Confidence de la base.
        /// </summary>
        public static string WorldGraphTeleportsJson
            => Resolve("interactive_teleports_worldgraph_2.73.json");
        /// <summary>
        /// Routes de téléportation normalisées depuis la table interactive_skills de Giny 2.68.
        /// Le serveur les valide puis les importe dans SQLite au démarrage; les maisons restent
        /// dans leur catalogue séparé.
        /// </summary>
        public static string InteractiveTeleportsJson => Resolve("interactive_teleports_giny_2.68.json");
        /// <summary>
        /// Los catálogos de oficios, habilidades y recetas en crudo. Se quedan fuera de
        /// <c>datos</c> a propósito: el servidor los importa a world.db y nunca los sirve.
        ///
        /// Se busca en <c>dofus3_data</c> ANTES que en <c>JsonFromDofusDude</c>, que es donde los
        /// puso quien escribió esto. Los tres ficheros salen del volcado del cliente y ya vivían en
        /// dofus3_data desde antes, así que mirando sólo en la carpeta nueva no se encontraban y la
        /// importación se saltaba sola sin que nadie se enterara: las tablas quedaban creadas y
        /// vacías. Se sigue mirando en las dos carpetas de antes, porque quien los tenga allí no
        /// tiene por qué moverlos.
        ///
        /// La comprobación es por FICHERO y no por carpeta: <c>dofus3_data</c> existe en cualquier
        /// instalación, así que preguntar si existe la carpeta la habría elegido siempre, tuviera
        /// dentro los catálogos o no.
        /// </summary>
        public static string DofusDudeJsonDir
        {
            get
            {
                foreach (string candidate in new[]
                {
                    DataDir,
                    Path.Combine(Root, "JsonFromDofusDude"),
                    Path.GetFullPath(Path.Combine(Root, "..", "JsonFromDofusDude")),
                })
                {
                    if (File.Exists(Path.Combine(candidate, "jobs.json"))) return candidate;
                }

                return Path.Combine(Root, "JsonFromDofusDude");
            }
        }
        public static string JobsJson => Path.Combine(DofusDudeJsonDir, "jobs.json");
        public static string SkillsJson => Path.Combine(DofusDudeJsonDir, "skills.json");
        public static string RecipesJson => Path.Combine(DofusDudeJsonDir, "recipes.json");
        public static string WaypointsJson => Resolve("waypoints.json");
        public static string ZaapOverridesJson => Resolve("zaap_overrides.json");
        public static string HavenBagJson => Resolve("havenbag.json");
        public static string TitlesOrnamentsJson => Resolve("titles_ornaments.json");
        public static string CosmeticsJson => Resolve("cosmetics.json");
        public static string CosmeticSkinsJson => Resolve("cosmetic_skins.json");
        // El aspecto de cada montura, indexado por el objeto que la da. Lo genera
        // extract_monturas.py de los bundles del cliente.
        public static string MountsJson => Resolve("mounts.json");
        // Qué vende cada NPC de tienda y a qué precio, medido del servidor de torneos con
        // tools/extraer_tiendas.py.
        public static string NpcShopsJson => Resolve("npc_shops.json");
        // Las parejas de hechizo base/variante, una por cada hueco de la barra. Del volcado del
        // cliente; el personaje lleva uno de cada pareja, no los dos.
        public static string SpellVariantsJson
        {
            get
            {
                string inData = Path.Combine(DataDir, "spell_variants.json");
                return File.Exists(inData) ? inData : Resolve("spell_variants.json");
            }
        }

        // Las 120 características con el hueco que le toca a cada una dentro del kub, sacadas
        // de los 672 kub reales de las capturas por tools/extraer_caracteristicas_kub.py. Se
        // abría por ruta relativa, y sin ella la ficha cae de 120 entradas a 25 sin decir nada.
        public static string CharacteristicFieldsJson => Resolve("caracteristicas_kub.json");

        // Cuántas rondas vive cada invocación. Lo que no esté medido no lleva cuenta atrás.
        public static string SummonDurationsJson => Resolve("invocaciones_duracion.json");

        // The three blocks of the world entry, taken from the 3.6.10.10 capture with
        // extraer_world.py. They are separate files because the real server does not push them in
        // one go: it sends a block, waits for the client to confirm, and only then carries on.
        public static string WorldStageAfterCharacter => Resolve("world_etapa1_tras_elegir_personaje.bin");
        public static string WorldStageAfterConfirm => Resolve("world_etapa2_tras_confirmar.bin");
        public static string WorldStageMap => Resolve("world_etapa3_mapa.bin");

        public static string LogsDir
        {
            get
            {
                string dir = Path.Combine(Root, "logs");
                if (!Directory.Exists(dir)) Directory.CreateDirectory(dir);
                return dir;
            }
        }

        public static string MapDumpCoordinates => Path.Combine(LogsDir, "map_dump_coordinates.csv");
        public static string MapDumpScrolls => Path.Combine(LogsDir, "map_dump_scrolls.csv");
        public static string MapDumpInfos => Path.Combine(LogsDir, "map_dump_infos.csv");

        // ─── Logs ───────────────────────────────────────────────────────────────
        // Logs are ALWAYS written inside the logs/ folder to keep the root clean.
        public static string DebugLog => Path.Combine(LogsDir, "emulator_debug.log");
        public static string TrafficLog => Path.Combine(LogsDir, "gameserver_traffic.log");

        /// <summary>
        /// File that marks which folder is the emulator's data root.
        ///
        /// Deliberately NOT world.db: there are 0-byte copies of world.db inside bin\Debug,
        /// bin\Release and the project folder, and the upward search would have stopped at them,
        /// taking a build folder with an empty database as the root. This marker only exists in
        /// the real root.
        /// </summary>
        private const string RootMarker = ".jondo-root";

        /// <summary>
        /// Locates the data root by walking up from the assembly directory until the marker file
        /// shows up. That way it works the same running the deployment
        /// (...\Jondo Unity Emulator\) as with `dotnet run` (...\bin\Debug\net10.0\), which would
        /// otherwise take the build folder as the root and never find the data.
        /// </summary>
        private static string ResolveRoot()
        {
            foreach (string start in new[] { SafeBaseDirectory(), SafeCurrentDirectory() })
            {
                string found = SearchUpwards(start);
                if (found != null) return found;
            }

            // No marker: fall back to the assembly directory, and failing that, to the historical path.
            string fallback = SafeBaseDirectory();
            return string.IsNullOrEmpty(fallback) ? LegacyRoot : fallback;
        }

        private static string SearchUpwards(string start)
        {
            if (string.IsNullOrEmpty(start)) return null;
            try
            {
                var dir = new DirectoryInfo(start);
                // 6 levels are more than enough to cover bin\<config>\<tfw>\ and the deployment.
                for (int i = 0; i < 6 && dir != null; i++, dir = dir.Parent)
                {
                    if (File.Exists(Path.Combine(dir.FullName, RootMarker)))
                    {
                        return dir.FullName.TrimEnd(Path.DirectorySeparatorChar);
                    }
                }
            }
            catch { }
            return null;
        }

        private static string SafeBaseDirectory()
        {
            try
            {
                string d = AppContext.BaseDirectory;
                return Directory.Exists(d) ? d.TrimEnd(Path.DirectorySeparatorChar) : null;
            }
            catch { return null; }
        }

        private static string SafeCurrentDirectory()
        {
            try { return Directory.GetCurrentDirectory().TrimEnd(Path.DirectorySeparatorChar); }
            catch { return null; }
        }

        /// <summary>
        /// Busca un fichero en datos\, en bases\ y en la raíz; si no está en ninguna, en la ruta
        /// histórica. Cuando no aparece por ningún lado devuelve la ruta de <c>datos\</c>, que es
        /// donde debe crearse.
        /// </summary>
        public static string Resolve(string filename)
        {
            foreach (string sub in SubFolders)
            {
                string candidate = Combine(Root, Path.Combine(sub, filename));
                if (File.Exists(candidate)) return candidate;
            }

            string legacy = Combine(LegacyRoot, filename);
            if (File.Exists(legacy))
            {
                Console.WriteLine($"[Paths][WARNING] '{filename}' is still at the old path ({LegacyRoot}). " +
                                  $"Move it to {Root} to complete the migration.");
                return legacy;
            }

            return Combine(Root, Path.Combine(DataFolder, filename));
        }

        /// <summary>Same as Resolve but for directories.</summary>
        public static string ResolveDir(string dirname)
        {
            foreach (string sub in SubFolders)
            {
                string candidate = Combine(Root, Path.Combine(sub, dirname));
                if (Directory.Exists(candidate)) return candidate;
            }

            string legacy = Combine(LegacyRoot, dirname);
            if (Directory.Exists(legacy))
            {
                Console.WriteLine($"[Paths][WARNING] Directory '{dirname}' is still at the old path ({LegacyRoot}).");
                return legacy;
            }
            return Combine(Root, Path.Combine(DataFolder, dirname));
        }

        /// <summary>Carpeta de datos. Lo que no exista se creará aquí.</summary>
        public const string DataFolder = "datos";

        /// <summary>Carpeta de las bases de datos, que son las que el emulador escribe.</summary>
        public const string DatabaseFolder = "bases";

        /// <summary>
        /// Igual que Resolve pero para ficheros que el emulador CREA: si no existe todavía, la
        /// ruta que devuelve es la de la carpeta que le toca, no la de la raíz.
        /// </summary>
        /// <summary>
        /// Una base de datos: se busca PRIMERO en su carpeta, bases\, y sólo después en el resto.
        ///
        /// Antes usaba el mismo orden que los datos —datos\ primero— y eso costó una tarde. Si por
        /// lo que sea aparece un world.db en datos\, el servidor se pone a escribir ahí y deja de
        /// ver el de bases\: el personaje sale donde no lo dejaste, los oficios vuelven a nivel 1,
        /// y no hay ningún fallo de código que encontrar porque cada mitad es coherente consigo
        /// misma. Una base no es un dato del juego: datos\ es de sólo lectura y viene del cliente,
        /// bases\ es lo que el servidor escribe.
        ///
        /// Si queda una copia suelta en otro sitio se avisa por consola, porque es exactamente la
        /// clase de cosa que no se nota hasta que se ha perdido una partida.
        /// </summary>
        private static string ResolveWritable(string filename, string folder)
        {
            string propia = Combine(Root, Path.Combine(folder, filename));
            if (File.Exists(propia))
            {
                AvisarDeCopias(filename, propia);
                return propia;
            }

            foreach (string sub in SubFolders)
            {
                string candidate = Combine(Root, Path.Combine(sub, filename));
                if (File.Exists(candidate)) return candidate;
            }

            string legacy = Combine(LegacyRoot, filename);
            if (File.Exists(legacy)) return legacy;

            string destino = Combine(Root, folder);
            try { Directory.CreateDirectory(destino); } catch { }
            return Path.Combine(destino, filename);
        }

        /// <summary>Avisa si la misma base existe en dos sitios. Ver ResolveWritable.</summary>
        private static void AvisarDeCopias(string filename, string usada)
        {
            foreach (string sub in SubFolders)
            {
                string otra = Combine(Root, Path.Combine(sub, filename));
                if (!File.Exists(otra)) continue;
                if (string.Equals(otra, usada, StringComparison.OrdinalIgnoreCase)) continue;

                Console.WriteLine($"[Paths] OJO: hay otro {filename} en {otra}. Se usa {usada} " +
                                  "y ese otro se queda sin tocar; borra el que sobre.");
            }
        }

        private static string Combine(string a, string b) => Path.Combine(a, b);

        public static void LogResolvedPaths()
        {
            Console.WriteLine($"[Paths] emulator root     : {Root}");
            Console.WriteLine($"[Paths] world.db          : {WorldDb}");
            Console.WriteLine($"[Paths] auth.db           : {AuthDb}");
            Console.WriteLine($"[Paths] dofus3_data       : {DataDir}");
            Console.WriteLine($"[Paths] walkable cells    : {WalkableCellsJson}");
            Console.WriteLine($"[Paths] client            : {ClientDir}");
        }
    }
}
