import { StrictMode, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';
import './database.css';
import './tool-catalogue.css';
import './telemetry.css';

const api = window.admin;

function DatabaseExplorer() {
  const [databases, setDatabases] = useState([]), [database, setDatabase] = useState(''), [tables, setTables] = useState([]), [table, setTable] = useState('');
  const [data, setData] = useState(null), [page, setPage] = useState(0), [error, setError] = useState(''), [loading, setLoading] = useState(false);
  const refreshDatabases = () => api.database.list().then(result => { setDatabases(result.databases); if (!database && result.databases[0]) setDatabase(result.databases[0].name); }).catch(e => setError(e.message));
  useEffect(refreshDatabases, []);
  useEffect(() => { if (!database) return; setTable(''); setData(null); setLoading(true); api.database.tables(database).then(result => { setTables(result.tables); setTable(result.tables[0]?.name || ''); }).catch(e => setError(e.message)).finally(() => setLoading(false)); }, [database]);
  useEffect(() => { if (!database || !table) return; setLoading(true); api.database.rows({ database, table, page, pageSize: 50 }).then(setData).catch(e => setError(e.message)).finally(() => setLoading(false)); }, [database, table, page]);
  const chooseTable = name => { setTable(name); setPage(0); };
  const pages = data ? Math.max(1, Math.ceil(data.total / data.pageSize)) : 1;
  return <main className="database-view"><aside className="database-sidebar"><div className="sidebar-title"><div><b>Databases</b><small>Read-only explorer</small></div><button onClick={refreshDatabases}>↻</button></div><div className="database-list">{databases.map(item => <button key={item.name} className={database === item.name ? 'selected' : ''} onClick={() => setDatabase(item.name)}><strong>{item.name}</strong><small>{(item.size / 1024 / 1024).toFixed(item.size > 1024 * 1024 ? 1 : 2)} MB</small></button>)}</div><div className="sidebar-title tables-title"><div><b>Tables</b><small>{tables.length} available</small></div></div><div className="table-list">{tables.map(item => <button key={item.name} className={table === item.name ? 'selected' : ''} onClick={() => chooseTable(item.name)}><span>{item.name}</span><small>{item.rowCount.toLocaleString()}</small></button>)}</div></aside><section className="database-content"><div className="database-heading"><div><p className="eyebrow">{database || 'Database'}</p><h2>{table || 'Select a table'}</h2><p>Safe read-only rows from <code>bases</code>. Changes remain controlled through server tools.</p></div><button className="run" onClick={() => { setPage(0); setTable(table); }}>{loading ? 'Loading…' : 'Refresh rows'}</button></div>{error && <div className="error">{error}</div>}{data && <><div className="table-meta"><span>{data.total.toLocaleString()} rows</span><span>Page {data.page + 1} of {pages}</span><span>{data.columns.length} columns</span></div><div className="grid-wrap"><table><thead><tr>{data.columns.map(column => <th key={column}>{column}</th>)}</tr></thead><tbody>{data.rows.map((row, index) => <tr key={index}>{data.columns.map(column => <td key={column} title={String(row[column] ?? '')}>{row[column] === null ? <em>NULL</em> : typeof row[column] === 'object' ? JSON.stringify(row[column]) : String(row[column])}</td>)}</tr>)}</tbody></table></div><div className="pager"><button disabled={page === 0} onClick={() => setPage(value => value - 1)}>← Previous</button><button disabled={page + 1 >= pages} onClick={() => setPage(value => value + 1)}>Next →</button></div></>}</section></main>;
}

function Tools() {
  const [tools, setTools] = useState([]), [selected, setSelected] = useState(null), [args, setArgs] = useState(''), [result, setResult] = useState('Select a Python tool. Arguments are JSON strings, for example ["--summary"].'), [busy, setBusy] = useState(false);
  const refresh = () => api.tools.list().then(setTools).catch(error => setResult(error.message)); useEffect(refresh, []);
  async function run() { if (!selected || busy) return; let parsed = []; try { parsed = args.trim() ? JSON.parse(args) : []; if (!Array.isArray(parsed) || !parsed.every(x => typeof x === 'string')) throw Error(); } catch { setResult('Arguments must be a JSON array of strings.'); return; } setBusy(true); setResult('Running…'); try { const out = await api.tools.run({ name: selected.name, args: parsed }); setResult(out.output || `Exited with ${out.code}.`); } catch (error) { setResult(error.message); } finally { setBusy(false); } }
  return <main className="tools"><aside><div className="aside-head"><div><b>Maintenance tools</b><small>Indexed and allowlisted</small></div><button onClick={refresh}>Refresh</button></div>{tools.map(tool => <button key={tool.name} className={selected?.name === tool.name ? 'selected' : ''} onClick={() => { setSelected(tool); setArgs(''); }}>{tool.name.replace(/\.py$/, '')}</button>)}</aside><section><div className="tool-heading"><div><p className="eyebrow">{selected ? 'Indexed maintenance tool' : 'Tool catalogue'}</p><h2>{selected?.name?.replace(/\.py$/, '') || 'Select a tool'}</h2></div>{selected && <code className="script-name">tools/{selected.name}</code>}</div>{selected ? <><div className="tool-guide"><h3>What it does</h3><p>{selected.description}</p><h3>How to use it</h3><p>{selected.usage}</p><h3>Available arguments</h3>{selected.arguments?.length ? <ul>{selected.arguments.map(argument => <li key={argument}><code>{argument}</code></li>)}</ul> : <p>No arguments required.</p>}</div><label>Arguments (JSON string array)</label><input value={args} onChange={e => setArgs(e.target.value)} placeholder={selected.arguments?.length ? '["--summary"]' : '[]'}/><button className="run" disabled={busy} onClick={run}>{busy ? 'Running…' : 'Run tool'}</button></> : <p>Select a named tool to see its purpose, supported arguments, and safe usage guidance.</p>}<pre>{result}</pre></section></main>;
}

const statusClass = status => `status status-${String(status || 'unknown').toLowerCase()}`;
function Telemetry() {
  const [summary, setSummary] = useState(null), [packets, setPackets] = useState([]), [filter, setFilter] = useState('All'), [selected, setSelected] = useState(null), [detail, setDetail] = useState(null), [error, setError] = useState('');
  const refresh = async () => { setError(''); try { const [nextSummary, nextPackets] = await Promise.all([api.telemetry.summary(), api.telemetry.list()]); if (nextSummary.error) throw Error(nextSummary.error); if (nextPackets.error) throw Error(nextPackets.error); setSummary(nextSummary); setPackets(nextPackets); } catch (e) { setError(e.message); } };
  useEffect(() => { refresh(); }, []);
  const visible = packets.filter(packet => filter === 'All' || packet.status === filter);
  const selectPacket = async packet => { setSelected(packet); setDetail(null); const result = await api.telemetry.detail(packet.id); setDetail(result); };
  return <main className="telemetry-dashboard"><div className="telemetry-heading"><div><p className="eyebrow">Protocol observation</p><h2>Packet telemetry</h2><p>Durable client packet captures, grouped by implementation state.</p></div><button className="run" onClick={refresh}>Refresh telemetry</button></div>{error && <div className="error">{error}</div>}<div className="status-cards">{summary?.status_counts?.map(item => <button key={item.Status} className={`status-card ${filter === item.Status ? 'active' : ''}`} onClick={() => setFilter(filter === item.Status ? 'All' : item.Status)}><span className={statusClass(item.Status)}>{item.Status}</span><strong>{item.rows}</strong><small>{item.occurrences.toLocaleString()} occurrences</small></button>)}</div><section className="telemetry-table-panel"><div className="panel-title"><div><h3>Captured packet shapes</h3><p>{filter === 'All' ? `${packets.length} packet shapes` : `${visible.length} ${filter} packet shapes`}</p></div><select value={filter} onChange={e => setFilter(e.target.value)}><option>All</option>{summary?.status_counts?.map(item => <option key={item.Status}>{item.Status}</option>)}</select></div><div className="grid-wrap telemetry-grid"><table><thead><tr><th>Status</th><th>Opcode</th><th>Type URL</th><th>Phase</th><th>Occurrences</th><th>Last seen</th></tr></thead><tbody>{visible.map(packet => <tr key={packet.id} className={selected?.id === packet.id ? 'row-selected' : ''} onClick={() => selectPacket(packet)}><td><span className={statusClass(packet.status)}>{packet.status}</span></td><td><code>{packet.opcode || '—'}</code></td><td title={packet.type_url || ''}>{packet.type_url || '—'}</td><td>{packet.phase || '—'}</td><td>{packet.occurrences.toLocaleString()}</td><td>{packet.last_seen_utc?.replace('T', ' ').replace('Z', '') || '—'}</td></tr>)}</tbody></table></div></section>{selected && <section className="packet-detail"><div><p className="eyebrow">Packet #{selected.id}</p><h3><code>{selected.opcode || 'unknown'}</code> <span className={statusClass(selected.status)}>{selected.status}</span></h3><p>{selected.decoded_summary || 'No decoded summary recorded.'}</p></div>{detail?.error ? <div className="error">{detail.error}</div> : detail && <details><summary>Raw capture evidence</summary><pre>{JSON.stringify(detail, null, 2)}</pre></details>}</section>}</main>;
}

function App() {
  const [tab, setTab] = useState('database'), [summary, setSummary] = useState(null);
  return <div className="shell"><div className="title"><span>● Jondo Admin</span><div><button onClick={api.window.minimize}>—</button><button onClick={api.window.toggle}>□</button><button className="close" onClick={api.window.close}>×</button></div></div><header><div><h1>Jondo Admin</h1><p>Server data, telemetry, and controlled maintenance.</p></div><nav><button className={tab === 'database' ? 'active' : ''} onClick={() => setTab('database')}>Database</button><button className={tab === 'tools' ? 'active' : ''} onClick={() => setTab('tools')}>Tools</button><button className={tab === 'telemetry' ? 'active' : ''} onClick={() => setTab('telemetry')}>Packet telemetry</button></nav></header>{tab === 'database' ? <DatabaseExplorer/> : tab === 'tools' ? <Tools/> : <Telemetry/>}</div>;
}
createRoot(document.getElementById('root')).render(<StrictMode><App/></StrictMode>);
