using System;
using System.Collections.Generic;
using Avalonia.Controls;
using Avalonia.Layout;
using Avalonia.Media;
using Jondo.Unity.Studio.Data;
using Jondo.Unity.Studio.Pages;

namespace Jondo.Unity.Studio
{
    /// <summary>
    /// The editor's only window: a list of sections on the left, the section on the right.
    /// </summary>
    /// <remarks>
    /// Phase one is READ ONLY, on purpose. Nothing here writes a file. The point of it is to prove
    /// the shell and the content layers against the real data before anything is allowed to save,
    /// and to be immediately useful on its own: today, working out why a monster does nothing means
    /// writing a Python script.
    /// </remarks>
    public sealed class Shell : Window
    {
        private readonly ContentControl _content = new ContentControl();
        private readonly List<IStudioPage> _pages = new List<IStudioPage>();

        public Shell()
        {
            Title = "Jondo Studio";

            // Maximised from the start. This is a workbench, not a dialog: the map grid alone is
            // 560 cells wide and the placement list has five columns, and both of them get cropped
            // in anything smaller than the screen.
            WindowState = WindowState.Maximized;

            // Still worth setting: this is the size it goes back to when un-maximised.
            Width = 1180;
            Height = 760;
            MinWidth = 900;
            MinHeight = 600;

            var world = WorldData.Load();

            _pages.Add(new OverviewPage(world));
            _pages.Add(new NpcPlacementsPage(world));
            _pages.Add(new MapCellsPage(world));

            var sections = new ListBox
            {
                ItemsSource = _pages,
                Width = 210,
                Background = new SolidColorBrush(Color.FromRgb(0x1B, 0x1D, 0x22)),
                BorderThickness = new Avalonia.Thickness(0),
            };
            sections.SelectionChanged += (_, _) =>
            {
                if (sections.SelectedItem is IStudioPage page) _content.Content = Safely(page);
            };

            var layout = new Grid
            {
                ColumnDefinitions = new ColumnDefinitions("Auto,*"),
            };
            layout.Children.Add(sections);

            _content.Margin = new Avalonia.Thickness(18);
            _content.HorizontalAlignment = HorizontalAlignment.Stretch;
            _content.VerticalAlignment = VerticalAlignment.Stretch;
            Grid.SetColumn(_content, 1);
            layout.Children.Add(_content);

            Content = layout;
            sections.SelectedIndex = 0;
        }

        /// <summary>
        /// Builds a section, and shows what went wrong instead of taking the window down with it.
        /// </summary>
        /// <remarks>
        /// Every section reads files that are regenerated by tools outside this program, so one of
        /// them meeting something it did not expect is a matter of when. An editor that dies on
        /// startup tells you nothing; one that says which section broke and why can still be used
        /// for the other five.
        /// </remarks>
        private static Control Safely(IStudioPage page)
        {
            try
            {
                return page.Build();
            }
            catch (Exception ex)
            {
                return new ScrollViewer
                {
                    Content = new TextBlock
                    {
                        Text = $"'{page.Title}' could not be built." +
                               Environment.NewLine + Environment.NewLine + ex,
                        FontFamily = new FontFamily("Consolas, Menlo, monospace"),
                        Foreground = new SolidColorBrush(Color.FromRgb(0xD8, 0x8A, 0x7A)),
                        TextWrapping = TextWrapping.Wrap,
                    },
                };
            }
        }
    }

    /// <summary>One section of the editor.</summary>
    public interface IStudioPage
    {
        /// <summary>What the sidebar shows. ToString is what the list binds to.</summary>
        string Title { get; }

        /// <summary>Builds the section's contents. Called every time it is selected.</summary>
        Control Build();
    }
}
