using Jondo.Unity.Launcher;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Jondo.Unity.Server
{
    public static class RegressionGuardTests
    {
        private static readonly string[] ForbiddenLiterals = new string[]
        {
            "670668947750",
            "-20003",
            "\"Fortellon\""
        };

        public static void Run()
        {
            // The connection phase messages are always checked, in deployment too: that is where
            // structural bugs used to slip through, and all the client shows there is a blank
            // screen with no error at all.
            Network.ConnectionProtocolSelfTest.Run();
            Network.ClientLaunchRegistry.AssertTwoClientsAreIsolated();
            Network.ClientLaunchRegistry.AssertEightClientLimit();
            AssertProfessionCatalog();
            AssertRelativeMapLookup();
            AssertInteractiveRegistry();

            // WHAT STAYS HERE, AND WHY, now that Jondo.Unity.Tests exists.
            //
            // These guards throw, and a server that throws at startup does not boot. That is worth
            // paying only for the checks a green build cannot make: the ones that ask "is the data
            // I was SHIPPED sane?". datos/ and world.db are regenerated by the tools in tools/ and
            // redistributed compressed, entirely outside the build, so a bad regeneration reaches a
            // player with every test still passing.
            //
            // Everything that only asks "is this CODE correct?" moved to Jondo.Unity.Tests, where
            // it runs in a second under `dotnet test` instead of on every single boot: the content
            // layers, the collision formula, the coin bands, the fight sheet, frame limits,
            // protobuf parsing, password hashing, log censorship and session isolation.
            AssertCharacterSelectionNeedsAnAccount();
            AssertItemUidsAreServerWide();
            AssertJondoCoinTemplateExists();
            AssertShopCurrencyIsOptional();
            AssertPacketShapesAreTelling();
            AssertMonstersBringTheirSpells();
            AssertVendorsStandSomewhereSensible();

            // The source code sweep had been dead since the folders were reorganised: it went up
            // three levels from the binary and down into "Jondo.Unity.Launcher", which finds nothing
            // either running from bin\<config>\<tfw>\ or from the deployment. It always left through
            // the return for the path that does not exist, without checking a single line, and on top
            // of that it wrote that it had passed.
            //
            // Now the root is found by going up until the .sln turns up, which is the only fixed point
            // in both ways of starting. If it does not appear -- because the binary is handed out
            // without the code next to it -- it is skipped quietly, which is the honest thing: there is
            // nothing to look at, not everything is fine.
            string? raiz = BuscarLaRaizDelCodigo();
            if (raiz == null) return;

            BarrerElCodigo(raiz);
        }

        /// <summary>
        /// The folder that has the .sln, going up from where the binary is.
        ///
        /// It is the only fixed point that works for both ways of starting: from
        /// bin\&lt;config&gt;\&lt;tfw&gt;\&lt;rid&gt;\ it is four folders up, and from the deployment
        /// -- the .exe is at the root -- none. Counting levels by hand fails in one of the two, and
        /// fails silently, which is exactly what had been happening.
        /// </summary>
        private static string? BuscarLaRaizDelCodigo()
        {
            var dir = new DirectoryInfo(AppContext.BaseDirectory.TrimEnd(Path.DirectorySeparatorChar));
            for (int subidas = 0; dir != null && subidas < 8; subidas++, dir = dir.Parent)
            {
                if (File.Exists(Path.Combine(dir.FullName, "Jondo.Unity.sln"))) return dir.FullName;
            }
            return null;
        }

        /// <summary>
        /// Reads all the code of the three projects and hands it to the guards that look at text.
        ///
        /// It is read once and shared, rather than each guard walking the disk on its own: it is a
        /// few hundred files and this runs at every start.
        /// </summary>
        private static void BarrerElCodigo(string raiz)
        {
            var fuentes = new List<SecurityGuardTests.Fuente>();

            foreach (string proyecto in new[] { "Jondo.Unity.Server", "Jondo.Unity.World", "Jondo.Unity.Launcher" })
            {
                string carpeta = Path.Combine(raiz, proyecto);
                if (!Directory.Exists(carpeta)) continue;

                foreach (string fichero in Directory.GetFiles(carpeta, "*.cs", SearchOption.AllDirectories))
                {
                    // bin and obj hold copies and code generated by the compiler: they give false
                    // positives and triple what has to be read as well.
                    string sep = Path.DirectorySeparatorChar.ToString();
                    if (fichero.Contains(sep + "obj" + sep) || fichero.Contains(sep + "bin" + sep)) continue;

                    string nombre = Path.GetFileName(fichero);
                    if (nombre == "BasePayloads.cs" || nombre == "TransitionPayloads.cs" ||
                        nombre == "RegressionGuardTests.cs" || nombre == "SecurityGuardTests.cs")
                        continue;

                    fuentes.Add(new SecurityGuardTests.Fuente(fichero, File.ReadAllText(fichero)));
                }
            }

            // With no files it does not say it passed: nothing was looked at.
            if (fuentes.Count == 0) return;

            foreach (var fuente in fuentes)
            {
                foreach (var literal in ForbiddenLiterals)
                {
                    if (fuente.Texto.Contains(literal))
                        throw new InvalidOperationException(
                            $"[RegressionGuard FAILED] '{fuente.Nombre}' lleva el literal de captura " +
                            $"prohibido '{literal}'.");
                }
            }

            SecurityGuardTests.Run(fuentes);

            Console.WriteLine($"[RegressionGuard] {fuentes.Count} ficheros de código barridos: sin " +
                              "literales de captura y sin ninguna de las ocho marcas de seguridad.");
        }

        /// <summary>
        /// Without a resolved account no character is selected.
        ///
        /// This is checked by RUNNING it, not by reading the code: a real kvw is sent to it with
        /// account zero, which is what arrives if somebody opens a socket and sends the selection
        /// without first presenting the kqz ticket. It has to say no.
        ///
        /// The check was written as «accountId > 0 && !EsSuyo(...)», so with account zero it was
        /// skipped entirely and loaded whoever's sheet it was -- and then wrote over it on saving, so
        /// it was not just looking. No game broke because of it, so without this test there was no way
        /// to find out.
        /// </summary>
        private static void AssertCharacterSelectionNeedsAnAccount()
        {
            // A kvw like the one the client sends: the character's id in f1.
            byte[] kvw = Network.ConnectionProtocol.Push(
                Protocol.Op.Kvw, Network.Pb.New().Var(1, 302677754146L).Build());

            if (Handlers.CharacterSelectionHandler.HandleCharacterSelectionRequest(kvw, 0))
                throw new InvalidOperationException(
                    "[RegressionGuard FAILED] La selección de personaje sale bien con cuenta cero. " +
                    "Un socket que no ha presentado el ticket puede cargar la ficha de cualquiera.");

            // Nor with an account that exists but is not the owner.
            if (Handlers.CharacterSelectionHandler.HandleCharacterSelectionRequest(kvw, -1))
                throw new InvalidOperationException(
                    "[RegressionGuard FAILED] La selección de personaje sale bien con una cuenta " +
                    "que no es la dueña del personaje.");
        }

        /// <summary>
        /// A frame with a made-up length does not reserve memory.
        ///
        /// Five bytes «FF FF FF FF 07» asked for a 2 GB array before reading a single byte of
        /// content, and eight connections were enough to bring the server down without
        /// authenticating. It is tested with the largest varint that fits and with one that never
        /// ends.
        /// </summary>
        /// <summary>
        /// A malformed protobuf neither blows up nor takes the memory.
        ///
        /// What goes into ProtoMessage.Parse comes from the socket, so it can be wrong on purpose. A
        /// field with a length larger than what is left asked for the array anyway -- up to 4 GB with
        /// five bytes -- and an unused wire type threw an exception nobody caught, in the middle of the
        /// routing.
        /// </summary>
        /// <summary>
        /// Passwords are hashed, and the old ones are still accepted.
        ///
        /// They were stored as typed and the comparison was done by the SQL itself. What is checked
        /// here is what keeps the change from locking anybody out: a password written in clear still
        /// works ONCE, and that once it warns that it has to be rewritten.
        /// </summary>
        /// <summary>
        /// No password can be taken from the log.
        ///
        /// The log goes to the console, to logs\emulator_console.log and to the buffer that serves
        /// /api/registro. The passwords for signing in and for creating an account went through it in
        /// clear.
        /// </summary>
        /// <summary>
        /// The fight lock belongs to each session, not to all of them.
        ///
        /// It was a static SemaphoreSlim in FightHandler, one for the eight connections, and it is held
        /// during the write to the socket: one slow client left everybody else unable to move a piece in
        /// their own fight. It is checked that two sessions can hold it at the same time, which is
        /// exactly what did not happen before.
        /// </summary>
        /// <summary>
        /// Item uids are handed out for the whole server, not per character.
        ///
        /// This was a real loss of items, checked on a copy of the database. The uid is unique across
        /// the whole table -- there is a unique index, and SaveInventoryItem does
        /// ON CONFLICT(Uid) DO UPDATE -- but it was handed out looking ONLY at the character's
        /// inventory: «the largest uid I have, plus one». Two new characters both start at 1, so the
        /// second one to loot did not add his item: he OVERWROTE the first one's. The first one's piwi
        /// feather turned into the other's seed and the second got nothing, without a single error
        /// message.
        /// </summary>
        private static void AssertItemUidsAreServerWide()
        {
            long primero = DatabaseManager.NextItemUid();
            long segundo = DatabaseManager.NextItemUid();

            if (segundo <= primero)
                throw new InvalidOperationException(
                    "[RegressionGuard FAILED] El repartidor de uid devuelve el mismo número dos " +
                    "veces. Dos objetos con el mismo uid se pisan en la base.");

            // And none of the ones ALREADY written goes beyond the 32 bits the client keeps.
            //
            // Checking it on what NextItemUid has just returned would be useless: that method throws
            // by itself when it goes over the cap, so the condition could never be true. What can go
            // wrong again is the database: it is enough for somebody to seed an inventory again with
            // `characterId * 1000` -- which is where this came from -- for the client to receive a number
            // it cannot give back whole. With character 13,825,560 the uid 13,825,560,000 reached the
            // client as 940,658,112, and on equipping the item the server did not recognise it: «not one
            // of ours», and the sheet was left without that piece's effects.
            int fueraDeRango = DatabaseManager.ObjetosConUidFueraDelCliente();
            if (fueraDeRango > 0)
                throw new InvalidOperationException(
                    $"[RegressionGuard FAILED] Hay {fueraDeRango} objeto(s) con un uid que el " +
                    $"cliente no puede devolver entero: sólo conserva 32 bits. Los repara sola " +
                    "DatabaseManager.RepairClientItemUids al arrancar, así que si esto salta es " +
                    "que alguien escribe uid sin pasar por NextItemUid().");

            // And above what is already written, which is what avoids colliding with what exists.
            long enUso = DatabaseManager.MayorUidGuardado();
            if (primero <= enUso)
                throw new InvalidOperationException(
                    $"[RegressionGuard FAILED] El repartidor de uid da {primero} y en la base ya hay " +
                    $"hasta {enUso}. El siguiente objeto que se guarde pisará uno que existe.");
        }

        /// <summary>
        /// The fight sheet carries the same characteristics, in the same order and in the same slot as
        /// the real server's.
        ///
        /// The list below is NOT chosen: it is the 53 entries of the jxb of
        /// «combate contra 4 poutchs nivel 25», in their exact order. And the slot matters as much as
        /// the number: the client reads each characteristic from a specific place, and put in the other
        /// one it reads zero.
        ///
        /// This caught two things at once. The first: we sent characteristic 84 -- push damage -- which
        /// the real server does NOT send in any of its 53 entries, and right at the position where the
        /// elemental damages start. The second: the five resistances went in the slot of invested points
        /// when the real one sends them in the equipment's.
        ///
        /// Both are of the kind that give no error: the game goes on, the panel shows numbers, and the
        /// only thing that looks odd is the damage preview showing a ridiculous figure.
        /// </summary>
        /// <summary>
        /// The content layers merge the way they are supposed to, whatever order they load in.
        ///
        /// These four rules are the whole contract, and every domain built on top of the store
        /// inherits them. Getting any of them wrong is the kind of bug that shows up as "my edit
        /// disappeared" weeks later, with no way to tell whether it was ever saved.
        /// </summary>
        /// <summary>
        /// Push damage, against the samples that measured it.
        ///
        /// They are the anchors from the 401 captures, and each one pins a different term of the
        /// formula:
        ///
        ///   level 200 with nothing      33 per cell, that is 132 divided by four
        ///   level 165, two cells        57, which is floor(2 × 114.5 / 4) and which no fixed constant
        ///                               can give: it is what anchors the level term
        ///   level 200 with 100 of 84    58, and 68, 78 and 88 as the mask adds 40, 80 or 120
        ///   561 of 84 against 30        331 for two cells, which is what proves that the
        ///                               resistance is subtracted INSIDE the quarter: outside it gives 316
        ///
        /// If somebody moves the 32, or takes the resistance out of the parentheses, or rounds per cell
        /// instead of at the end, one of these four fails and the server does not start.
        /// </summary>
        /// <summary>
        /// The Jondo Coin pays by bands of 25 levels, and the item that represents it exists.
        ///
        /// The edges are what breaks by itself when the formula is touched: 25 has to pay one and 26
        /// two, not the other way round. A «/ 25» without the «- 1» in front changes exactly those two
        /// and goes unnoticed until somebody kills a level 25 monster and gets two.
        ///
        /// And it is checked that the template is still in the catalogue, because the number is written
        /// by hand: if world.zip is ever regenerated without that item, the coin would silently stop
        /// existing and fights would hand out an id the client cannot draw.
        /// </summary>
        private static void AssertJondoCoinTemplateExists()
        {
            // The banding itself is a unit test now (Jondo.Unity.Tests, Economy). What has to stay
            // here is the half that depends on the shipped data: world.db is regenerated and
            // redistributed, so the template can go missing without a single line of code changing.
            if (!DatabaseManager.TryGetItemTemplateEffects(Managers.JondoCoin.TemplateId, out _))
                throw new InvalidOperationException(
                    $"[RegressionGuard FAILED] La plantilla {Managers.JondoCoin.TemplateId}, que es " +
                    "la Jondo Coin, no está en ItemTemplates. El combate repartiría un objeto que " +
                    "el cliente no sabe dibujar.");
        }

        /// <summary>
        /// A shop that charges in kamas sends the SAME BYTES as before token shops existed, and a token
        /// shop differs only in the currency field.
        ///
        /// It is the regression that can really slip in: the new field of the kbd is optional, and if
        /// somebody changes the VarIfNotZero for a Var, the server's 51 normal shops would start sending
        /// an «f3 = 0». The client would read it as «the currency is item 0», and what shows then is not
        /// an error but a shop where nobody can buy anything.
        ///
        /// Measured over the 305 captures: of the real server's 60 kbd, 58 carry only f1 and f2 and two
        /// also carry f3, with 13052 «Sebuscalón» and 30529 «Fidelicha».
        /// </summary>
        private static void AssertShopCurrencyIsOptional()
        {
            int[] catalogo = { 20440 };

            byte[] enKamas = Network.ConnectionProtocol.BuildShop(1234, catalogo);
            byte[] sinMoneda = Network.ConnectionProtocol.BuildShop(1234, catalogo, null);

            if (!enKamas.AsSpan().SequenceEqual(sinMoneda))
                throw new InvalidOperationException(
                    "[RegressionGuard FAILED] Pasar una moneda de cero cambia los bytes de la " +
                    "tienda. Tiene que dar exactamente lo mismo que no pasar ninguna.");

            // And without a currency field 3 cannot appear anywhere. The raw tag is searched for:
            // field 3, varint type, which in protobuf is the byte 0x18.
            foreach (var (campo, _) in CamposDePrimerNivel(enKamas))
            {
                if (campo != 3) continue;
                throw new InvalidOperationException(
                    "[RegressionGuard FAILED] Una tienda que cobra en kamas está mandando el campo " +
                    "de la moneda. En las 58 tiendas de kamas de la captura ese campo no está.");
            }

            var deFichas = new Managers.TokenShops.Shop
            {
                TokenGid = Managers.JondoCoin.TemplateId,
                Prices = { [20440] = 4242 },
            };
            byte[] enFichas = Network.ConnectionProtocol.BuildShop(1234, catalogo, deFichas);
            bool llevaMoneda = false;
            foreach (var (campo, valor) in CamposDePrimerNivel(enFichas))
            {
                if (campo != 3) continue;
                llevaMoneda = true;
                if (valor != Managers.JondoCoin.TemplateId)
                    throw new InvalidOperationException(
                        $"[RegressionGuard FAILED] La tienda de fichas dice que la moneda es el " +
                        $"objeto {valor} y se le pidió la {Managers.JondoCoin.TemplateId}.");
            }
            if (!llevaMoneda)
                throw new InvalidOperationException(
                    "[RegressionGuard FAILED] La tienda de fichas no manda el campo de la moneda, " +
                    "así que el cliente cobraría en kamas.");

            // And the price that travels in the catalogue has to be the TOKEN one, not the kamas one.
            //
            // This came up playing: the first version sent the currency right but kept putting the price
            // in kamas on every entry, so the shop window said «1 token» and the charge was 150. A price
            // shown that is not the one charged is one of those things the player finds out by paying.
            bool precioBueno = false;
            foreach (var bloque in Network.ProtoMessage.Parse(enFichas).Fields)
            {
                if (bloque.FieldNumber != 1 || bloque.WireType != 2) continue;
                foreach (var dentro in Network.ProtoMessage.Parse(bloque.BytesValue).Fields)
                {
                    if (dentro.FieldNumber != 3 || dentro.WireType != 2) continue;
                    foreach (var precio in Network.ProtoMessage.Parse(dentro.BytesValue).Fields)
                        if (precio.FieldNumber == 2 && precio.VarIntValue == 4242) precioBueno = true;
                }
            }
            if (!precioBueno)
                throw new InvalidOperationException(
                    "[RegressionGuard FAILED] El catálogo de una tienda de fichas no lleva el " +
                    "precio en fichas. El cliente enseñaría un precio y el servidor cobraría otro.");
        }

        /// <summary>A message's top-level varints, to look at them without fully parsing it.</summary>
        private static List<(int Campo, long Valor)> CamposDePrimerNivel(byte[] mensaje)
        {
            var salida = new List<(int, long)>();
            int i = 0;
            while (i < mensaje.Length)
            {
                long etiqueta = LeerVarint(mensaje, ref i);
                if (etiqueta < 0) break;
                int campo = (int)(etiqueta >> 3);
                int tipo = (int)(etiqueta & 7);

                if (tipo == 0)
                {
                    long valor = LeerVarint(mensaje, ref i);
                    if (valor < 0) break;
                    salida.Add((campo, valor));
                }
                else if (tipo == 2)
                {
                    long largo = LeerVarint(mensaje, ref i);
                    if (largo < 0 || i + largo > mensaje.Length) break;
                    i += (int)largo;
                }
                else break;
            }
            return salida;
        }

        private static long LeerVarint(byte[] datos, ref int i)
        {
            long valor = 0;
            int desplazamiento = 0;
            while (i < datos.Length && desplazamiento <= 63)
            {
                byte b = datos[i++];
                valor |= (long)(b & 0x7F) << desplazamiento;
                if ((b & 0x80) == 0) return valor;
                desplazamiento += 7;
            }
            return -1;
        }

        /// <summary>
        /// A packet's signature tells apart different shapes of the same opcode and groups equal ones.
        ///
        /// It is the only thing that makes the list of unhandled packets worth anything. If the
        /// signature stops going into the submessages, all the messages of an opcode collapse into a
        /// single row and the list says «jjm, 4,000 times» instead of saying which of its shapes are the
        /// ones to look at. And if it starts telling apart too much -- for instance by the VALUE of a
        /// number instead of by its presence -- every click of the player creates a new row and the list
        /// turns into a log.
        ///
        /// Both directions are tested: that two different things give different signatures, and that
        /// two equal ones with other numbers inside give the SAME.
        /// </summary>
        private static void AssertPacketShapesAreTelling()
        {
            (byte[] Bytes, string Espera, string Que)[] casos =
            {
                (Network.Pb.New().Var(1, 5).Build(), "1:v",
                 "un número suelto"),

                (Network.Pb.New().Var(1, 5).Var(3, 9).Build(), "1:v,3:v",
                 "dos números, y el número de campo cuenta"),

                (Network.Pb.New().Var(1, 5).Msg(2, Network.Pb.New().Var(3, 7)).Build(),
                 "1:v,2:{3:v}",
                 "un submensaje, mirado por dentro"),

                (Network.Pb.New().Msg(1, Network.Pb.New().Msg(2, Network.Pb.New().Var(4, 1))).Build(),
                 "1:{2:{4:v}}",
                 "dos capas de submensaje"),

                (Network.Pb.New().Str(1, "un texto cualquiera").Build(), "1:s",
                 "una cadena, que no es una estructura"),
            };

            foreach (var (bytes, espera, que) in casos)
            {
                string dio = Network.UnknownPackets.Signature(bytes);
                if (dio == espera) continue;
                throw new InvalidOperationException(
                    $"[RegressionGuard FAILED] La firma de «{que}» tendría que ser «{espera}» y " +
                    $"es «{dio}». Sin ella la lista de paquetes sin atender no distingue nada.");
            }

            // The same with other values inside has to give THE SAME signature: what is grouped is
            // the shape, not what the player has just clicked.
            string unaVez = Network.UnknownPackets.Signature(
                Network.Pb.New().Var(1, 5).Msg(2, Network.Pb.New().Var(3, 7)).Build());
            string otraVez = Network.UnknownPackets.Signature(
                Network.Pb.New().Var(1, 999999).Msg(2, Network.Pb.New().Var(3, 1)).Build());
            if (unaVez != otraVez)
                throw new InvalidOperationException(
                    $"[RegressionGuard FAILED] Dos mensajes de la misma forma con otros números " +
                    $"dan firmas distintas («{unaVez}» y «{otraVez}»). Cada pulsación del jugador " +
                    "crearía una fila nueva.");

            // A data block that BY CHANCE reads as protobuf cannot slip in as a structure. This is not
            // hypothetical: the jrw -- the walking packet -- carries the path as a block of bytes, and
            // without the cap on the field number it was read as a structure with fields 1024, 1566 or
            // 1600, different on every step the player took. Measured on the captures: 307 «shapes» of a
            // single message in 1,798 captured, that is the list turned into a useless log.
            //
            // The cap is measured: in the whole 3.6.10.10 protocol there are 6,186 declared message
            // fields and the highest is 40.
            byte[] bloqueDeDatos = { 0x82, 0x40, 0x02, 0x11, 0x22, 0xC2, 0x60, 0x01, 0x33 };
            string comoSale = Network.UnknownPackets.Signature(
                Network.Pb.New().Var(1, 1).Bytes(2, bloqueDeDatos).Build());
            if (comoSale.Contains("{"))
                throw new InvalidOperationException(
                    $"[RegressionGuard FAILED] Un bloque de datos se está leyendo como estructura: " +
                    $"la firma sale «{comoSale}». Con eso el paquete de movimiento genera una fila " +
                    "nueva por cada paso que da el jugador.");

            // And two different shapes of the SAME opcode cannot collapse, which is the case that
            // motivates all this: in a real server's queue a single opcode got to have 32 different
            // payloads.
            string forma1 = Network.UnknownPackets.Signature(
                Network.Pb.New().Var(1, 1).Msg(2, Network.Pb.New().Var(1, 1).Str(3, "x")).Build());
            string forma2 = Network.UnknownPackets.Signature(
                Network.Pb.New().Var(1, 1).Msg(4, Network.Pb.New().Var(2, 1)).Build());
            if (forma1 == forma2)
                throw new InvalidOperationException(
                    "[RegressionGuard FAILED] Dos cargas distintas dan la misma firma. La lista de " +
                    "paquetes sin atender juntaría en una fila cosas que no tienen nada que ver.");
        }

        /// <summary>
        /// Monsters reach the fight with their spells.
        ///
        /// This hid 40% of the game's monsters and gave not a single error. Each grade's sheet carries
        /// a «startingSpellId» that is NOT a spell id but a spell LEVEL id -- a SpellLevels.Id --, and
        /// it was being put raw into the spell list. The bad part was not that the id was useless: it
        /// was that putting it in made the list stop being empty, and the code that reads the REAL
        /// spells was behind an «if the list is empty». A useless number cancelled the good ones.
        ///
        /// Measured: 2,133 of 5,134 monsters carry that field and 1,975 of them match no spell, so
        /// 2,051 monsters -- the Royal Jalamut among them -- stood in the fight with nothing to cast.
        /// They stayed still, which is how it was seen playing.
        ///
        /// Three monsters with known spells are checked, and one of those carrying the
        /// startingSpellId, so that the regression fires both if the good source stops being read and
        /// if somebody mixes the two numbers again.
        /// </summary>
        private static void AssertMonstersBringTheirSpells()
        {
            (int Monstruo, int Grado, int[] Hechizos, string Quien)[] esperado =
            {
                // The Royal Jalamut also carries startingSpellId 16186, which is exactly the one that used
                // to cancel these three.
                (2854, 0, new[] { 2230, 2231, 2355 }, "Jalamut Real"),
                (2894, 0, new[] { 2366, 2367, 2368 }, "Rata kenopintamos"),
            };

            foreach (var (monstruo, grado, hechizos, quien) in esperado)
            {
                var ficha = DatabaseManager.GetMonsterGradeStats(monstruo, grado);
                if (ficha == null)
                    throw new InvalidOperationException(
                        $"[RegressionGuard FAILED] No hay ficha para el monstruo {monstruo} " +
                        $"({quien}) en el grado {grado}.");

                foreach (int hechizo in hechizos)
                {
                    if (ficha.SpellIds.Contains(hechizo)) continue;
                    throw new InvalidOperationException(
                        $"[RegressionGuard FAILED] El monstruo {monstruo} ({quien}) tendría que " +
                        $"traer el hechizo {hechizo} y trae [{string.Join(", ", ficha.SpellIds)}]. " +
                        "Sin hechizos el monstruo se queda quieto en el combate y no avisa de nada.");
                }

                // And that the spell level id has not slipped in among the spell ids.
                if (ficha.StartingSpellLevelId != 0 &&
                    ficha.SpellIds.Contains(ficha.StartingSpellLevelId))
                {
                    throw new InvalidOperationException(
                        $"[RegressionGuard FAILED] El monstruo {monstruo} ({quien}) lleva su " +
                        $"startingSpellId ({ficha.StartingSpellLevelId}) en la lista de hechizos. " +
                        "Ese número es un SpellLevels.Id, no un Spells.Id: ver Summons.cs, que lo " +
                        "traduce bien.");
                }
            }
        }

        /// <summary>
        /// Where the vendors stand: walkable, free cells, not repeated and not side by side.
        ///
        /// The placement is a file edited by hand, and the four ways of spoiling it give no error: an
        /// NPC inside a wall cannot be clicked, one on top of the zaap covers the zaap, two on the same
        /// cell are drawn one over the other, and a row of blocks side by side is exactly the ugliness
        /// this came to fix.
        ///
        /// The not-side-by-side part is measured: over the 422 placements -- 327 different NPCs -- of
        /// 202 maps in the captures, only 24 of 635 pairs on the same map are neighbours -- 3.8% -- and
        /// the typical distance to the nearest is two to four cells. Ankama does not put them in a row.
        ///
        /// The previous count said 16 of 512 and 3.1%, and dated from when the placement file had fewer
        /// rows. It is measured again when it grows: a measured number that stops being one becomes a
        /// claim, and this is the one that justifies the bar.
        /// </summary>
        private static void AssertVendorsStandSomewhereSensible()
        {
            var puestos = new Dictionary<int, int>();

            foreach (long mapa in Managers.Npcs.Maps)
            foreach (var spawn in Managers.Npcs.Of(mapa))
            {
                var sitio = Managers.Vendors.PlacementOf(spawn.NpcId);

                // Only the one standing where WE PUT IT is looked at. Some vendors also appear in the
                // captures, placed by Ankama on other maps, and those go where the capture says even if
                // their cell is not walkable: an NPC can stand where the player does not walk, and only
                // 151 of the world's 422 do.
                if (sitio == null || spawn.Cell != sitio.Value.Cell) continue;

                if (!MapManager.IsCellWalkable(spawn.MapId, spawn.Cell))
                    throw new InvalidOperationException(
                        $"[RegressionGuard FAILED] El vendedor {spawn.NpcId} está puesto en la " +
                        $"casilla {spawn.Cell} del mapa {spawn.MapId}, que no se puede pisar. " +
                        "Ahí no hay quien lo cliquee.");

                if (puestos.TryGetValue(spawn.Cell, out int otro))
                    throw new InvalidOperationException(
                        $"[RegressionGuard FAILED] Los vendedores {otro} y {spawn.NpcId} están los " +
                        $"dos en la casilla {spawn.Cell}: se dibujarían uno encima del otro.");
                puestos[spawn.Cell] = spawn.NpcId;
            }

            // And none next to another. Measured on the map's grid, fourteen wide.
            const int AnchoDelMapa = 14;
            var celdas = new List<int>(puestos.Keys);
            for (int i = 0; i < celdas.Count; i++)
            {
                for (int j = i + 1; j < celdas.Count; j++)
                {
                    int ax = celdas[i] % AnchoDelMapa, ay = celdas[i] / AnchoDelMapa;
                    int bx = celdas[j] % AnchoDelMapa, by = celdas[j] / AnchoDelMapa;
                    if (Math.Abs(ax - bx) > 1 || Math.Abs(ay - by) > 1) continue;
                    throw new InvalidOperationException(
                        $"[RegressionGuard FAILED] Los vendedores {puestos[celdas[i]]} y " +
                        $"{puestos[celdas[j]]} están pegados, en las casillas {celdas[i]} y " +
                        $"{celdas[j]}. El juego real casi nunca los pone así: 24 parejas vecinas " +
                        "de 635 medidas, el 3,8 %.");
                }
            }
        }

                        private static void AssertInteractiveRegistry()
        {
            var expected = new HashSet<(long MapId, int ElementId)>();
            foreach (long mapId in Managers.Interactives.MapIds)
            {
                // Every element of the client must have its f11. Those with no action stay passive and
                // so do not become clickable.
                foreach (var element in Managers.Interactives.ElementsOf(mapId))
                    expected.Add((mapId, element.Id));

                foreach (var zaap in Managers.Interactives.ZaapElements(mapId))
                    expected.Add((mapId, zaap.Id));

                var chest = Managers.Merkasako.ChestOf(mapId);
                if (chest.Id != 0) expected.Add((mapId, chest.Id));

                var lottery = Managers.Lottery.Of(mapId);
                if (lottery.Id != 0) expected.Add((mapId, lottery.Id));

                // Zaapis and bins are recognised by their graphic and there are dozens, so they go in
                // a block. Without this the count does not add up and the server does not start -- which is
                // what happened when they were added: the guard saw them before anybody else.
                foreach (var zaapi in Managers.Zaapis.ElementsOn(mapId))
                    expected.Add((mapId, zaapi.Id));

                foreach (var bin in Managers.Bins.On(mapId))
                    expected.Add((mapId, bin.Id));

                foreach (var door in Managers.Houses.On(mapId))
                    expected.Add((mapId, door.ElementId));

                foreach (var teleport in Managers.TeleportManager.On(mapId))
                {
                    expected.Add((mapId, teleport.ElementId));
                    if (Managers.Houses.TryGetDoor(mapId, teleport.ElementId, out _))
                        throw new InvalidOperationException(
                            "[RegressionGuard FAILED] Un paso genérico pisa una puerta de casa.");
                }

                foreach (var resource in Managers.Resources.On(mapId))
                    expected.Add((mapId, resource.ElementId));

                foreach (var interactive in Managers.InteractiveRegistry.OnMap(mapId))
                {
                    foreach (var action in interactive.Actions)
                    {
                        if (!Managers.InteractiveRegistry.TryResolveUse(
                                mapId, interactive.Element.Id, action.SkillInstanceId,
                                out var resolved, out var resolvedAction) ||
                            !ReferenceEquals(interactive, resolved) ||
                            !ReferenceEquals(action, resolvedAction))
                        {
                            throw new InvalidOperationException(
                                "[RegressionGuard FAILED] Interactive registry cannot resolve its own declaration.");
                        }
                    }

                    if (Managers.InteractiveRegistry.TryResolveUse(
                            mapId, interactive.Element.Id, int.MaxValue, out _, out _))
                    {
                        throw new InvalidOperationException(
                            "[RegressionGuard FAILED] Interactive registry accepted a mismatched skill instance.");
                    }
                }
            }

            // House interiors are not in Interactives.MapIds -- they are maps without elements in
            // the client dump -- so they are counted apart.
            foreach (long interior in Managers.Houses.Interiors)
            {
                if (Managers.Houses.TryGetExit(interior, out var exit))
                    expected.Add((interior, exit.ElementId));
            }

            // Giny's rule: every passage can be resolved as a USE114 element and by its cell.
            // The second way covers the suns and floor exits that end with jrw/jqi without an iwo,
            // and the index also spots two routes placed by mistake on the same cell.
            foreach (var teleport in Managers.TeleportManager.All)
            {
                if (!Managers.InteractiveRegistry.TryResolveUse(
                        teleport.SourceMapId, teleport.ElementId,
                        Managers.Interactives.SkillInstanceOf(teleport.ElementId),
                        out var interactive, out var action) ||
                    interactive.Element.Id != teleport.ElementId ||
                    interactive.Element.Cell != teleport.SourceCellId ||
                    interactive.Element.Gfx != teleport.GfxId ||
                    interactive.Type != teleport.InteractiveType ||
                    action.Kind != Managers.InteractiveActionKind.Teleport ||
                    action.SkillId != teleport.SkillId ||
                    !Managers.TeleportManager.TryGetCellTrigger(
                        teleport.SourceMapId, teleport.SourceCellId, out var cellRoute) ||
                    !ReferenceEquals(teleport, cellRoute))
                {
                    throw new InvalidOperationException(
                        $"[RegressionGuard FAILED] El paso {teleport.SourceMapId}/" +
                        $"{teleport.ElementId} no es un interactivo de ruta declarado en f11.");
                }
            }

            // Three specific routes, with their numbers, so that a change in the catalogue does not go
            // unnoticed: the one from Astrub to the temple, the round trip of the jeweller's workshop,
            // and a stair -- gfx 62018 -- that goes exactly the same way as a sun.
            if (!Managers.TeleportManager.TryGet(191106048, 515837, out var astrub) ||
                astrub.DestinationMapId != 192416776 || astrub.DestinationCellId != 534)
            {
                throw new InvalidOperationException(
                    "[RegressionGuard FAILED] Falta o ha cambiado la ruta de Astrub al templo.");
            }

            if (!Managers.TeleportManager.TryGet(188746247, 515801, out var jewellerEntrance) ||
                jewellerEntrance.DestinationMapId != 192937990 ||
                jewellerEntrance.DestinationCellId != 400 ||
                !Managers.TeleportManager.TryGet(192937990, 515742, out var jewellerExit) ||
                jewellerExit.DestinationMapId != 188746247 ||
                jewellerExit.SourceCellId != 414 || jewellerExit.DestinationCellId != 358 ||
                !Managers.TeleportManager.TryGetCellTrigger(192937990, 414, out var cellExit) ||
                !ReferenceEquals(jewellerExit, cellExit) ||
                !Managers.InteractiveRegistry.TryResolveUse(
                    192937990, 515742, Managers.Interactives.SkillInstanceOf(515742),
                    out var jewellerInteractive, out var jewellerAction) ||
                jewellerInteractive.Element.Cell != 414 || jewellerInteractive.Element.Gfx != 3520 ||
                jewellerInteractive.Type != -1 ||
                jewellerAction.Kind != Managers.InteractiveActionKind.Teleport ||
                jewellerAction.SkillId != Managers.TeleportManager.ExitSkill)
            {
                throw new InvalidOperationException(
                    "[RegressionGuard FAILED] Falta o ha cambiado la ida y vuelta del taller del " +
                    "joyero de Astrub.");
            }

            if (!Managers.TeleportManager.TryGet(192940038, 515691, out var stairExit) ||
                stairExit.SourceCellId != 327 || stairExit.DestinationMapId != 188744711 ||
                stairExit.DestinationCellId != 427 || stairExit.GfxId != 62018 ||
                stairExit.InteractiveType != -1 ||
                stairExit.SkillId != 114 ||
                !Managers.TeleportManager.TryGetCellTrigger(192940038, 327, out var stairCellRoute) ||
                !ReferenceEquals(stairExit, stairCellRoute) ||
                !Managers.InteractiveRegistry.TryResolveUse(
                    192940038, 515691, Managers.Interactives.SkillInstanceOf(515691),
                    out var stairInteractive, out var stairAction) ||
                stairInteractive.Element.Gfx != 62018 || stairInteractive.Element.Cell != 327 ||
                stairInteractive.Type != stairExit.InteractiveType ||
                stairAction.Kind != Managers.InteractiveActionKind.Teleport ||
                stairAction.SkillId != 114)
            {
                throw new InvalidOperationException(
                    "[RegressionGuard FAILED] La escalera 192940038/515691 tiene que ser un paso " +
                    "clicable.");
            }

            // Astrub workshop tested in game: gfx 3507 is declared with type -1 in 27
            // 3.6 captures. Replacing it with zero keeps the numbers in the jss but makes
            // the sun disappear on the client side.
            if (!Managers.TeleportManager.TryGet(192940040, 515845, out var workshopExit) ||
                workshopExit.SourceCellId != 415 || workshopExit.GfxId != 3507 ||
                workshopExit.InteractiveType != -1 ||
                workshopExit.SkillId != Managers.TeleportManager.ExitSkill ||
                workshopExit.DestinationMapId != 188745223 ||
                workshopExit.DestinationCellId != 371 ||
                !Managers.InteractiveRegistry.TryResolveUse(
                    192940040, 515845, Managers.Interactives.SkillInstanceOf(515845),
                    out var workshopInteractive, out var workshopAction) ||
                workshopInteractive.Type != -1 ||
                workshopAction.Kind != Managers.InteractiveActionKind.Teleport)
            {
                throw new InvalidOperationException(
                    "[RegressionGuard FAILED] La sortie 192940040/515845 doit conserver son " +
                    "type mesuré -1.");
            }

            if (Managers.InteractiveRegistry.Count != expected.Count)
            {
                throw new InvalidOperationException(
                    $"[RegressionGuard FAILED] Expected {expected.Count} interactives, got " +
                    $"{Managers.InteractiveRegistry.Count}.");
            }
        }

        private static void AssertProfessionCatalog()
        {
            if (Managers.JobManager.Count == 0 || Managers.SkillManager.Count == 0 ||
                Managers.RecipeManager.Count == 0)
                throw new InvalidOperationException(
                    "[RegressionGuard FAILED] Profession catalogue is empty.");

            foreach (var skill in Managers.SkillManager.All)
            {
                if (!Managers.JobManager.TryGet(skill.ParentJobId, out _))
                    throw new InvalidOperationException(
                        $"[RegressionGuard FAILED] Skill {skill.Id} references missing job {skill.ParentJobId}.");
            }

            foreach (var recipe in Managers.RecipeManager.All)
            {
                if (!Managers.JobManager.TryGet(recipe.JobId, out _) ||
                    !Managers.SkillManager.TryGet(recipe.SkillId, out _) ||
                    recipe.Ingredients.Count == 0 ||
                    recipe.Ingredients.Any(i => i.ItemId <= 0 || i.Quantity <= 0))
                    throw new InvalidOperationException(
                        $"[RegressionGuard FAILED] Recipe {recipe.ResultId} is inconsistent.");
            }

            // The catalogue has to carry gathering skills and the world has to have resources with
            // those skills. This used to call GatheringHandler.TryResolve, which only crossed tables
            // in memory and sent not a byte; now the handler really gathers and what has to be checked
            // is that there is something to gather.
            var gathering = Managers.SkillManager.All.FirstOrDefault(s => s.IsGathering);
            if (gathering == null)
                throw new InvalidOperationException(
                    "[RegressionGuard FAILED] El catalogo no trae ninguna habilidad de recoleccion.");

            if (Managers.Resources.Count == 0)
                throw new InvalidOperationException(
                    "[RegressionGuard FAILED] No hay ningun recurso recolectable en el mundo.");

            // And the quantity has to respect what was measured: a maxed profession on the easiest
            // resource gives twenty, and a freshly started one gives four.
            if (Handlers.GatheringHandler.Ceiling(200, 1) != 20 ||
                Handlers.GatheringHandler.Ceiling(200, 80) != 13 ||
                Handlers.GatheringHandler.Ceiling(1, 1) != 4)
                throw new InvalidOperationException(
                    "[RegressionGuard FAILED] La cantidad recolectada no cuadra con las capturas.");

            // And the experience curve, with the three points the captures give.
            if (Managers.JobExperience.Floor(2) != 20 || Managers.JobExperience.Floor(3) != 60 ||
                Managers.JobExperience.Floor(200) != 398000 ||
                Managers.JobExperience.LevelOf(20) != 2 || Managers.JobExperience.LevelOf(19) != 1)
                throw new InvalidOperationException(
                    "[RegressionGuard FAILED] La curva de experiencia de oficio no cuadra.");

            var craft = Managers.RecipeManager.All.First();
            if (!Handlers.CraftHandler.TryResolve(craft.SkillId, out _, out _, out var recipes, out _) ||
                !Handlers.CraftHandler.TryResolveRecipe(craft.SkillId, craft.ResultId, out _, out _) ||
                recipes.Count == 0)
                throw new InvalidOperationException(
                    "[RegressionGuard FAILED] Craft handler cannot resolve a known recipe.");
        }

        private static void AssertRelativeMapLookup()
        {
            var group = MapManager.Maps.Values
                .Where(m => m.MapId > 0)
                .GroupBy(m => (m.PosX, m.PosY))
                .FirstOrDefault(g => g.Count() > 1);
            if (group == null) return;

            var ordered = group.OrderBy(m => m.MapId).ToList();
            for (int i = 0; i < ordered.Count; i++)
            {
                var match = Managers.MapLookup.NextRelative(ordered[i].MapId);
                long expected = ordered[(i + 1) % ordered.Count].MapId;
                if (match == null || match.Map.MapId != expected ||
                    match.Candidates != ordered.Count ||
                    match.Wrapped != (i == ordered.Count - 1))
                    throw new InvalidOperationException(
                        "[RegressionGuard FAILED] Relative map cycle is not stable.");
            }
        }

            }
}
