using Jondo.Unity.Launcher;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Jondo.Unity.Server
{
    public static class RegressionGuardTests
    {
        private static readonly string[] ForbiddenLiterals = new string[]
        {
            "670668947750",
            "-20003",
            "\"Fortellon\""
        };

        public static void Run()
        {
            // The connection phase messages are always checked, in deployment too: that is where
            // structural bugs used to slip through, and all the client shows there is a blank
            // screen with no error at all.
            Network.ConnectionProtocolSelfTest.Run();
            Network.ClientLaunchRegistry.AssertTwoClientsAreIsolated();
            Network.ClientLaunchRegistry.AssertEightClientLimit();
            AssertProfessionCatalog();
            AssertRelativeMapLookup();
            AssertInteractiveRegistry();

            // WHAT STAYS HERE, AND WHY, now that Jondo.Unity.Tests exists.
            //
            // These guards throw, and a server that throws at startup does not boot. That is worth
            // paying only for the checks a green build cannot make: the ones that ask "is the data
            // I was SHIPPED sane?". datos/ and world.db are regenerated by the tools in tools/ and
            // redistributed compressed, entirely outside the build, so a bad regeneration reaches a
            // player with every test still passing.
            //
            // Everything that only asks "is this CODE correct?" moved to Jondo.Unity.Tests, where
            // it runs in a second under `dotnet test` instead of on every single boot: the content
            // layers, the collision formula, the coin bands, the fight sheet, frame limits,
            // protobuf parsing, password hashing, log censorship and session isolation.
            AssertCharacterSelectionNeedsAnAccount();
            AssertItemUidsAreServerWide();
            AssertJondoCoinTemplateExists();
            AssertShopCurrencyIsOptional();
            AssertPacketShapesAreTelling();
            AssertMonstersBringTheirSpells();
            AssertVendorsStandSomewhereSensible();

            // El barrido del código fuente llevaba muerto desde que se reorganizaron las
            // carpetas: subía tres niveles desde el binario y bajaba a "Jondo.Unity.Launcher",
            // que no da con nada ni corriendo desde bin\<config>\<tfw>\ ni desde el despliegue.
            // Se salía siempre por el return de la ruta que no existe, sin comprobar una línea,
            // y encima escribiendo que había pasado.
            //
            // Ahora la raíz se busca subiendo hasta dar con el .sln, que es el único punto fijo
            // en las dos formas de arrancar. Si no aparece —porque se reparta el binario sin el
            // código al lado— se salta callando, que es lo honrado: no hay nada que mirar, no
            // es que esté todo bien.
            string? raiz = BuscarLaRaizDelCodigo();
            if (raiz == null) return;

            BarrerElCodigo(raiz);
        }

        /// <summary>
        /// La carpeta que tiene el .sln, subiendo desde donde está el binario.
        ///
        /// Es el único punto fijo que sirve para las dos formas de arrancar: desde
        /// bin\&lt;config&gt;\&lt;tfw&gt;\&lt;rid&gt;\ hay que subir cuatro carpetas, y desde el despliegue
        /// —el .exe está en la raíz— ninguna. Contar niveles a mano falla en una de las dos, y
        /// falla en silencio, que es exactamente lo que llevaba pasando.
        /// </summary>
        private static string? BuscarLaRaizDelCodigo()
        {
            var dir = new DirectoryInfo(AppContext.BaseDirectory.TrimEnd(Path.DirectorySeparatorChar));
            for (int subidas = 0; dir != null && subidas < 8; subidas++, dir = dir.Parent)
            {
                if (File.Exists(Path.Combine(dir.FullName, "Jondo.Unity.sln"))) return dir.FullName;
            }
            return null;
        }

        /// <summary>
        /// Lee todo el código de los tres proyectos y se lo pasa a las guardias que miran texto.
        ///
        /// Se lee una vez y se reparte, en vez de que cada guardia recorra el disco por su cuenta:
        /// son unos cuantos cientos de ficheros y esto corre en cada arranque.
        /// </summary>
        private static void BarrerElCodigo(string raiz)
        {
            var fuentes = new List<SecurityGuardTests.Fuente>();

            foreach (string proyecto in new[] { "Jondo.Unity.Server", "Jondo.Unity.World", "Jondo.Unity.Launcher" })
            {
                string carpeta = Path.Combine(raiz, proyecto);
                if (!Directory.Exists(carpeta)) continue;

                foreach (string fichero in Directory.GetFiles(carpeta, "*.cs", SearchOption.AllDirectories))
                {
                    // bin y obj llevan copias y código generado por el compilador: dan falsos
                    // positivos y además multiplican por tres lo que hay que leer.
                    string sep = Path.DirectorySeparatorChar.ToString();
                    if (fichero.Contains(sep + "obj" + sep) || fichero.Contains(sep + "bin" + sep)) continue;

                    string nombre = Path.GetFileName(fichero);
                    if (nombre == "BasePayloads.cs" || nombre == "TransitionPayloads.cs" ||
                        nombre == "RegressionGuardTests.cs" || nombre == "SecurityGuardTests.cs")
                        continue;

                    fuentes.Add(new SecurityGuardTests.Fuente(fichero, File.ReadAllText(fichero)));
                }
            }

            // Sin ficheros no se dice que haya pasado: no se ha mirado nada.
            if (fuentes.Count == 0) return;

            foreach (var fuente in fuentes)
            {
                foreach (var literal in ForbiddenLiterals)
                {
                    if (fuente.Texto.Contains(literal))
                        throw new InvalidOperationException(
                            $"[RegressionGuard FAILED] '{fuente.Nombre}' lleva el literal de captura " +
                            $"prohibido '{literal}'.");
                }
            }

            SecurityGuardTests.Run(fuentes);

            Console.WriteLine($"[RegressionGuard] {fuentes.Count} ficheros de código barridos: sin " +
                              "literales de captura y sin ninguna de las ocho marcas de seguridad.");
        }

        /// <summary>
        /// Sin cuenta resuelta no se selecciona personaje.
        ///
        /// Esto se comprueba EJECUTÁNDOLO, no leyendo el código: se le manda un kvw de verdad
        /// con cuenta cero, que es lo que llega si alguien abre un socket y manda la selección
        /// sin presentar antes el ticket del kqz. Tiene que decir que no.
        ///
        /// La comprobación estaba escrita como «accountId > 0 && !EsSuyo(...)», así que con
        /// cuenta cero se saltaba entera y cargaba la ficha de quien fuera —y después se
        /// escribía encima al guardar, con lo que no era sólo mirar—. Ninguna partida se rompía
        /// por eso, así que sin esta prueba no había forma de enterarse.
        /// </summary>
        private static void AssertCharacterSelectionNeedsAnAccount()
        {
            // Un kvw como el que manda el cliente: el id del personaje en el f1.
            byte[] kvw = Network.ConnectionProtocol.Push(
                Protocol.Op.Kvw, Network.Pb.New().Var(1, 302677754146L).Build());

            if (Handlers.CharacterSelectionHandler.HandleCharacterSelectionRequest(kvw, 0))
                throw new InvalidOperationException(
                    "[RegressionGuard FAILED] La selección de personaje sale bien con cuenta cero. " +
                    "Un socket que no ha presentado el ticket puede cargar la ficha de cualquiera.");

            // Y con una cuenta que existe pero no es la dueña, tampoco.
            if (Handlers.CharacterSelectionHandler.HandleCharacterSelectionRequest(kvw, -1))
                throw new InvalidOperationException(
                    "[RegressionGuard FAILED] La selección de personaje sale bien con una cuenta " +
                    "que no es la dueña del personaje.");
        }

        /// <summary>
        /// Una trama con la longitud inventada no reserva memoria.
        ///
        /// Cinco bytes «FF FF FF FF 07» pedían un array de 2 GB antes de leer un solo byte de
        /// contenido, y ocho conexiones bastaban para tumbar el servidor sin autenticarse. Se
        /// prueba con el varint más grande que cabe y con uno que no termina nunca.
        /// </summary>
                /// <summary>
        /// Un protobuf mal formado no revienta ni se lleva la memoria.
        ///
        /// Lo que entra en ProtoMessage.Parse viene del socket, así que puede estar mal a
        /// propósito. Un campo con longitud mayor que lo que queda pedía el array igual —hasta
        /// 4 GB con cinco bytes— y un tipo de cable de los que no se usan lanzaba una excepción
        /// que nadie recoge, en mitad del enrutado.
        /// </summary>
                /// <summary>
        /// Las contraseñas van cifradas, y las de antes se siguen aceptando.
        ///
        /// Se guardaban tal cual se escribían y la comparación la hacía el propio SQL. Lo que se
        /// comprueba aquí es lo que hace que el cambio no deje a nadie fuera: una clave escrita
        /// en claro sigue valiendo UNA vez, y en esa vez avisa de que hay que reescribirla.
        /// </summary>
                /// <summary>
        /// Del registro no se saca una contraseña.
        ///
        /// El registro va a la consola, a logs\emulator_console.log y al buffer que sirve
        /// /api/registro. Por ahí pasaban en claro las claves de entrar y de crear cuenta.
        /// </summary>
                /// <summary>
        /// El candado de combate es de cada sesión, no de todas.
        ///
        /// Era un SemaphoreSlim estático en FightHandler, uno para las ocho conexiones, y se
        /// sostiene durante la escritura en el socket: un cliente lento dejaba a todos los demás
        /// sin poder mover ficha en su propio combate. Se comprueba que dos sesiones puedan
        /// tenerlo a la vez, que es exactamente lo que antes no pasaba.
        /// </summary>
                /// <summary>
        /// Los uid de objeto se reparten para todo el servidor, no por personaje.
        ///
        /// Esto era una pérdida de objetos de verdad, comprobada sobre una copia de la base. El
        /// uid es único en toda la tabla —hay índice único, y SaveInventoryItem hace
        /// ON CONFLICT(Uid) DO UPDATE— pero se repartía mirando SÓLO el inventario del personaje:
        /// «el mayor uid que tengo yo, más uno». Dos personajes nuevos empiezan los dos por el 1,
        /// así que el segundo que looteara no añadía su objeto: PISABA el del primero. Al primero
        /// se le convertía la pluma de piwi en la semilla del otro y al segundo no le llegaba
        /// nada, sin un solo mensaje de error.
        /// </summary>
        private static void AssertItemUidsAreServerWide()
        {
            long primero = DatabaseManager.NextItemUid();
            long segundo = DatabaseManager.NextItemUid();

            if (segundo <= primero)
                throw new InvalidOperationException(
                    "[RegressionGuard FAILED] El repartidor de uid devuelve el mismo número dos " +
                    "veces. Dos objetos con el mismo uid se pisan en la base.");

            // Y ninguno de los que YA están escritos se sale de los 32 bits que el cliente
            // conserva.
            //
            // Comprobarlo sobre lo que acaba de devolver NextItemUid no serviría: ese método
            // lanza él mismo al pasarse del tope, así que la condición nunca podría ser cierta.
            // Lo que sí puede volver a torcerse es la base: basta con que alguien vuelva a
            // sembrar un inventario con `characterId * 1000` —que es de donde salió esto— para
            // que el cliente reciba un número que no puede devolver entero. Con el personaje
            // 13.825.560 el uid 13.825.560.000 le llegaba al cliente como 940.658.112, y al
            // equipar el objeto el servidor no lo reconocía: «no es de los nuestros», y la ficha
            // se quedaba sin los efectos de esa pieza.
            int fueraDeRango = DatabaseManager.ObjetosConUidFueraDelCliente();
            if (fueraDeRango > 0)
                throw new InvalidOperationException(
                    $"[RegressionGuard FAILED] Hay {fueraDeRango} objeto(s) con un uid que el " +
                    $"cliente no puede devolver entero: sólo conserva 32 bits. Los repara sola " +
                    "DatabaseManager.RepairClientItemUids al arrancar, así que si esto salta es " +
                    "que alguien escribe uid sin pasar por NextItemUid().");

            // Y por encima de lo que ya hay escrito, que es lo que evita chocar con lo existente.
            long enUso = DatabaseManager.MayorUidGuardado();
            if (primero <= enUso)
                throw new InvalidOperationException(
                    $"[RegressionGuard FAILED] El repartidor de uid da {primero} y en la base ya hay " +
                    $"hasta {enUso}. El siguiente objeto que se guarde pisará uno que existe.");
        }

        /// <summary>
        /// La ficha de combate lleva las mismas características, en el mismo orden y en el mismo
        /// hueco que la del servidor real.
        ///
        /// La lista de abajo NO está elegida: son las 53 entradas del jxb de
        /// «combate contra 4 poutchs nivel 25», en su orden exacto. Y el hueco importa tanto como
        /// el número: el cliente lee cada característica de un sitio concreto, y puesta en el otro
        /// lee cero.
        ///
        /// Esto cazó dos cosas de golpe. La primera: mandábamos la característica 84 —el daño de
        /// empuje— que el servidor real NO manda en ninguna de sus 53 entradas, y encima justo en
        /// la posición donde empiezan los daños elementales. La segunda: las cinco resistencias
        /// iban en el hueco de los puntos invertidos cuando el real las manda en el del equipo.
        ///
        /// Las dos son de las que no dan error: la partida sigue, el panel enseña números, y lo
        /// único que se ve raro es que la previsualización de daño diga una cifra ridícula.
        /// </summary>
                /// <summary>
        /// The content layers merge the way they are supposed to, whatever order they load in.
        ///
        /// These four rules are the whole contract, and every domain built on top of the store
        /// inherits them. Getting any of them wrong is the kind of bug that shows up as "my edit
        /// disappeared" weeks later, with no way to tell whether it was ever saved.
        /// </summary>
                /// <summary>
        /// El daño de empuje, contra las muestras que lo midieron.
        ///
        /// Son las anclas de las 401 capturas, y cada una fija un término distinto de la fórmula:
        ///
        ///   nivel 200 sin nada          33 por casilla, o sea 132 partido cuatro
        ///   nivel 165, dos casillas     57, que es floor(2 × 114,5 / 4) y que ninguna constante
        ///                               fija puede dar: es lo que ancla el término del nivel
        ///   nivel 200 con 100 de la 84  58, y 68, 78 y 88 según la máscara sume 40, 80 o 120
        ///   561 de la 84 contra 30      331 por dos casillas, que es lo que demuestra que la
        ///                               resistencia se resta DENTRO del cuarto: fuera daría 316
        ///
        /// Si alguien mueve el 32, o saca la resistencia del paréntesis, o redondea por casilla en
        /// vez de al final, alguna de estas cuatro se cae y el servidor no arranca.
        /// </summary>
                /// <summary>
        /// La Jondo Coin paga por tramos de 25 niveles, y el objeto que la representa existe.
        ///
        /// Los bordes son lo que se rompe solo al tocar la fórmula: el 25 tiene que pagar una y el
        /// 26 dos, no al revés. Un «/ 25» sin el «- 1» delante cambia justo esos dos y no se nota
        /// hasta que alguien mata un monstruo de nivel 25 y le caen dos.
        ///
        /// Y se comprueba que la plantilla siga en el catálogo, porque el número está escrito a
        /// mano: si world.zip se regenera algún día sin ese objeto, la moneda dejaría de existir
        /// en silencio y los combates repartirían un id que el cliente no sabe dibujar.
        /// </summary>
        private static void AssertJondoCoinTemplateExists()
        {
            // The banding itself is a unit test now (Jondo.Unity.Tests, Economy). What has to stay
            // here is the half that depends on the shipped data: world.db is regenerated and
            // redistributed, so the template can go missing without a single line of code changing.
            if (!DatabaseManager.TryGetItemTemplateEffects(Managers.JondoCoin.TemplateId, out _))
                throw new InvalidOperationException(
                    $"[RegressionGuard FAILED] La plantilla {Managers.JondoCoin.TemplateId}, que es " +
                    "la Jondo Coin, no está en ItemTemplates. El combate repartiría un objeto que " +
                    "el cliente no sabe dibujar.");
        }

        /// <summary>
        /// Una tienda que cobra en kamas manda los MISMOS BYTES que antes de que existieran las
        /// tiendas de fichas, y una de fichas se diferencia sólo en el campo de la moneda.
        ///
        /// Es la regresión que de verdad puede colarse: el campo nuevo del kbd es opcional, y si
        /// alguien cambia el VarIfNotZero por un Var, las 51 tiendas normales del servidor pasarían
        /// a mandar un «f3 = 0». El cliente lo leería como «la moneda es el objeto 0», y lo que se
        /// ve entonces no es un error sino una tienda donde nadie puede comprar nada.
        ///
        /// Medido sobre las 305 capturas: de los 60 kbd del servidor real, 58 llevan sólo f1 y f2
        /// y dos llevan además el f3, con el 13052 «Sebuscalón» y el 30529 «Fidelicha».
        /// </summary>
        private static void AssertShopCurrencyIsOptional()
        {
            int[] catalogo = { 20440 };

            byte[] enKamas = Network.ConnectionProtocol.BuildShop(1234, catalogo);
            byte[] sinMoneda = Network.ConnectionProtocol.BuildShop(1234, catalogo, null);

            if (!enKamas.AsSpan().SequenceEqual(sinMoneda))
                throw new InvalidOperationException(
                    "[RegressionGuard FAILED] Pasar una moneda de cero cambia los bytes de la " +
                    "tienda. Tiene que dar exactamente lo mismo que no pasar ninguna.");

            // Y sin moneda no puede aparecer el campo 3 por ningún lado. Se busca la etiqueta
            // cruda: campo 3, tipo varint, que en protobuf es el byte 0x18.
            foreach (var (campo, _) in CamposDePrimerNivel(enKamas))
            {
                if (campo != 3) continue;
                throw new InvalidOperationException(
                    "[RegressionGuard FAILED] Una tienda que cobra en kamas está mandando el campo " +
                    "de la moneda. En las 58 tiendas de kamas de la captura ese campo no está.");
            }

            var deFichas = new Managers.TokenShops.Shop
            {
                TokenGid = Managers.JondoCoin.TemplateId,
                Prices = { [20440] = 4242 },
            };
            byte[] enFichas = Network.ConnectionProtocol.BuildShop(1234, catalogo, deFichas);
            bool llevaMoneda = false;
            foreach (var (campo, valor) in CamposDePrimerNivel(enFichas))
            {
                if (campo != 3) continue;
                llevaMoneda = true;
                if (valor != Managers.JondoCoin.TemplateId)
                    throw new InvalidOperationException(
                        $"[RegressionGuard FAILED] La tienda de fichas dice que la moneda es el " +
                        $"objeto {valor} y se le pidió la {Managers.JondoCoin.TemplateId}.");
            }
            if (!llevaMoneda)
                throw new InvalidOperationException(
                    "[RegressionGuard FAILED] La tienda de fichas no manda el campo de la moneda, " +
                    "así que el cliente cobraría en kamas.");

            // Y el precio que viaja en el catálogo tiene que ser el DE FICHAS, no el de kamas.
            //
            // Esto salió jugando: la primera versión mandaba bien la moneda pero seguía poniendo
            // el precio en kamas en cada entrada, así que el escaparate decía «1 ficha» y el
            // cobro eran 150. Un precio enseñado que no es el que se cobra es de las cosas que el
            // jugador descubre pagando.
            bool precioBueno = false;
            foreach (var bloque in Network.ProtoMessage.Parse(enFichas).Fields)
            {
                if (bloque.FieldNumber != 1 || bloque.WireType != 2) continue;
                foreach (var dentro in Network.ProtoMessage.Parse(bloque.BytesValue).Fields)
                {
                    if (dentro.FieldNumber != 3 || dentro.WireType != 2) continue;
                    foreach (var precio in Network.ProtoMessage.Parse(dentro.BytesValue).Fields)
                        if (precio.FieldNumber == 2 && precio.VarIntValue == 4242) precioBueno = true;
                }
            }
            if (!precioBueno)
                throw new InvalidOperationException(
                    "[RegressionGuard FAILED] El catálogo de una tienda de fichas no lleva el " +
                    "precio en fichas. El cliente enseñaría un precio y el servidor cobraría otro.");
        }

        /// <summary>Los varint de primer nivel de un mensaje, para mirarlos sin parsear del todo.</summary>
        private static List<(int Campo, long Valor)> CamposDePrimerNivel(byte[] mensaje)
        {
            var salida = new List<(int, long)>();
            int i = 0;
            while (i < mensaje.Length)
            {
                long etiqueta = LeerVarint(mensaje, ref i);
                if (etiqueta < 0) break;
                int campo = (int)(etiqueta >> 3);
                int tipo = (int)(etiqueta & 7);

                if (tipo == 0)
                {
                    long valor = LeerVarint(mensaje, ref i);
                    if (valor < 0) break;
                    salida.Add((campo, valor));
                }
                else if (tipo == 2)
                {
                    long largo = LeerVarint(mensaje, ref i);
                    if (largo < 0 || i + largo > mensaje.Length) break;
                    i += (int)largo;
                }
                else break;
            }
            return salida;
        }

        private static long LeerVarint(byte[] datos, ref int i)
        {
            long valor = 0;
            int desplazamiento = 0;
            while (i < datos.Length && desplazamiento <= 63)
            {
                byte b = datos[i++];
                valor |= (long)(b & 0x7F) << desplazamiento;
                if ((b & 0x80) == 0) return valor;
                desplazamiento += 7;
            }
            return -1;
        }

        /// <summary>
        /// La firma de un paquete distingue formas distintas del mismo opcode y junta las iguales.
        ///
        /// Es lo único que hace que la lista de paquetes sin atender valga para algo. Si la firma
        /// deja de meterse en los submensajes, todos los mensajes de un opcode colapsan en una
        /// sola fila y la lista dice «jjm, 4.000 veces» en vez de decir cuáles de sus formas son
        /// las que hay que mirar. Y si empieza a distinguir de más —por ejemplo por el VALOR de un
        /// número en vez de por su presencia— cada pulsación del jugador crea una fila nueva y la
        /// lista se convierte en un registro.
        ///
        /// Se prueban las dos direcciones: que dos cosas distintas den firmas distintas, y que dos
        /// iguales con otros números dentro den la MISMA.
        /// </summary>
        private static void AssertPacketShapesAreTelling()
        {
            (byte[] Bytes, string Espera, string Que)[] casos =
            {
                (Network.Pb.New().Var(1, 5).Build(), "1:v",
                 "un número suelto"),

                (Network.Pb.New().Var(1, 5).Var(3, 9).Build(), "1:v,3:v",
                 "dos números, y el número de campo cuenta"),

                (Network.Pb.New().Var(1, 5).Msg(2, Network.Pb.New().Var(3, 7)).Build(),
                 "1:v,2:{3:v}",
                 "un submensaje, mirado por dentro"),

                (Network.Pb.New().Msg(1, Network.Pb.New().Msg(2, Network.Pb.New().Var(4, 1))).Build(),
                 "1:{2:{4:v}}",
                 "dos capas de submensaje"),

                (Network.Pb.New().Str(1, "un texto cualquiera").Build(), "1:s",
                 "una cadena, que no es una estructura"),
            };

            foreach (var (bytes, espera, que) in casos)
            {
                string dio = Network.UnknownPackets.Signature(bytes);
                if (dio == espera) continue;
                throw new InvalidOperationException(
                    $"[RegressionGuard FAILED] La firma de «{que}» tendría que ser «{espera}» y " +
                    $"es «{dio}». Sin ella la lista de paquetes sin atender no distingue nada.");
            }

            // Lo mismo con otros valores dentro tiene que dar LA MISMA firma: lo que se agrupa es
            // la forma, no lo que el jugador acaba de pulsar.
            string unaVez = Network.UnknownPackets.Signature(
                Network.Pb.New().Var(1, 5).Msg(2, Network.Pb.New().Var(3, 7)).Build());
            string otraVez = Network.UnknownPackets.Signature(
                Network.Pb.New().Var(1, 999999).Msg(2, Network.Pb.New().Var(3, 1)).Build());
            if (unaVez != otraVez)
                throw new InvalidOperationException(
                    $"[RegressionGuard FAILED] Dos mensajes de la misma forma con otros números " +
                    $"dan firmas distintas («{unaVez}» y «{otraVez}»). Cada pulsación del jugador " +
                    "crearía una fila nueva.");

            // Un bloque de datos que POR CASUALIDAD se lea como protobuf no puede colarse como
            // estructura. Esto no es hipotético: el jrw —el paquete de andar— lleva el camino
            // como un bloque de bytes, y sin el tope del número de campo se leía como una
            // estructura con campos 1024, 1566 o 1600, distintos en cada paso que daba el
            // jugador. Medido sobre las capturas: 307 «formas» de un mismo mensaje en 1.798
            // capturados, o sea la lista convertida en un registro inservible.
            //
            // El tope está medido: en el protocolo entero de 3.6.10.10 hay 6.186 campos de
            // mensaje declarados y el más alto es el 40.
            byte[] bloqueDeDatos = { 0x82, 0x40, 0x02, 0x11, 0x22, 0xC2, 0x60, 0x01, 0x33 };
            string comoSale = Network.UnknownPackets.Signature(
                Network.Pb.New().Var(1, 1).Bytes(2, bloqueDeDatos).Build());
            if (comoSale.Contains("{"))
                throw new InvalidOperationException(
                    $"[RegressionGuard FAILED] Un bloque de datos se está leyendo como estructura: " +
                    $"la firma sale «{comoSale}». Con eso el paquete de movimiento genera una fila " +
                    "nueva por cada paso que da el jugador.");

            // Y dos formas distintas del MISMO opcode no pueden colapsar, que es el caso que
            // motiva todo esto: en la cola de un servidor real un solo opcode llegó a tener 32
            // cargas distintas.
            string forma1 = Network.UnknownPackets.Signature(
                Network.Pb.New().Var(1, 1).Msg(2, Network.Pb.New().Var(1, 1).Str(3, "x")).Build());
            string forma2 = Network.UnknownPackets.Signature(
                Network.Pb.New().Var(1, 1).Msg(4, Network.Pb.New().Var(2, 1)).Build());
            if (forma1 == forma2)
                throw new InvalidOperationException(
                    "[RegressionGuard FAILED] Dos cargas distintas dan la misma firma. La lista de " +
                    "paquetes sin atender juntaría en una fila cosas que no tienen nada que ver.");
        }

        /// <summary>
        /// Los monstruos llegan al combate con sus hechizos.
        ///
        /// Esto tapaba al 40 % de los monstruos del juego y no daba ni un error. La ficha de cada
        /// grado trae un «startingSpellId» que NO es un id de hechizo sino de NIVEL de hechizo
        /// —un SpellLevels.Id—, y se estaba metiendo crudo en la lista de hechizos. Lo malo no era
        /// que ese id no valiera: era que al meterlo la lista dejaba de estar vacía, y el código
        /// que lee los hechizos DE VERDAD estaba detrás de un «si la lista está vacía». Un número
        /// inútil cancelaba los buenos.
        ///
        /// Medido: 2.133 de 5.134 monstruos traen ese campo y 1.975 de ellos no casan con ningún
        /// hechizo, así que 2.051 monstruos —el Jalamut Real entre ellos— se plantaban en el
        /// combate sin nada que lanzar. Se quedaban quietos, que es como se vio jugando.
        ///
        /// Se comprueban tres monstruos con hechizos conocidos y uno de los que traen el
        /// startingSpellId, para que la regresión salte tanto si se deja de leer la fuente buena
        /// como si alguien vuelve a mezclar los dos números.
        /// </summary>
        private static void AssertMonstersBringTheirSpells()
        {
            (int Monstruo, int Grado, int[] Hechizos, string Quien)[] esperado =
            {
                // El Jalamut Real trae ademas startingSpellId 16186, que es justo el que antes
                // cancelaba estos tres.
                (2854, 0, new[] { 2230, 2231, 2355 }, "Jalamut Real"),
                (2894, 0, new[] { 2366, 2367, 2368 }, "Rata kenopintamos"),
            };

            foreach (var (monstruo, grado, hechizos, quien) in esperado)
            {
                var ficha = DatabaseManager.GetMonsterGradeStats(monstruo, grado);
                if (ficha == null)
                    throw new InvalidOperationException(
                        $"[RegressionGuard FAILED] No hay ficha para el monstruo {monstruo} " +
                        $"({quien}) en el grado {grado}.");

                foreach (int hechizo in hechizos)
                {
                    if (ficha.SpellIds.Contains(hechizo)) continue;
                    throw new InvalidOperationException(
                        $"[RegressionGuard FAILED] El monstruo {monstruo} ({quien}) tendría que " +
                        $"traer el hechizo {hechizo} y trae [{string.Join(", ", ficha.SpellIds)}]. " +
                        "Sin hechizos el monstruo se queda quieto en el combate y no avisa de nada.");
                }

                // Y que no se haya colado el id de nivel de hechizo entre los de hechizo.
                if (ficha.StartingSpellLevelId != 0 &&
                    ficha.SpellIds.Contains(ficha.StartingSpellLevelId))
                {
                    throw new InvalidOperationException(
                        $"[RegressionGuard FAILED] El monstruo {monstruo} ({quien}) lleva su " +
                        $"startingSpellId ({ficha.StartingSpellLevelId}) en la lista de hechizos. " +
                        "Ese número es un SpellLevels.Id, no un Spells.Id: ver Summons.cs, que lo " +
                        "traduce bien.");
                }
            }
        }

        /// <summary>
        /// Donde se plantan los vendedores: casillas andables, libres, sin repetir y sin pegarse.
        ///
        /// La colocación es un fichero que se edita a mano, y las cuatro formas de estropearla no
        /// dan ningún error: un NPC dentro de una pared no se puede clicar, uno encima del zaap
        /// tapa el zaap, dos en la misma casilla se dibujan uno sobre otro, y una fila de bloques
        /// pegados es justo lo feo que esto venía a arreglar.
        ///
        /// Lo de no pegarse está medido: sobre 396 NPCs de 202 mapas de las capturas, sólo 16 de
        /// 512 parejas del mismo mapa son vecinas —el 3,1 %— y la distancia típica al más cercano
        /// es de dos a cuatro casillas. Ankama no los pone en fila.
        /// </summary>
        private static void AssertVendorsStandSomewhereSensible()
        {
            var puestos = new Dictionary<int, int>();

            foreach (long mapa in Managers.Npcs.Maps)
            foreach (var spawn in Managers.Npcs.Of(mapa))
            {
                var sitio = Managers.Vendors.PlacementOf(spawn.NpcId);

                // Sólo se mira al que está donde LO HEMOS PUESTO NOSOTROS. Algunos vendedores
                // salen además en las capturas, plantados por Ankama en otros mapas, y ésos van
                // donde diga la captura aunque su casilla no sea pisable: un NPC puede estar de
                // pie donde el jugador no anda, y sólo 151 de los 422 del mundo lo son.
                if (sitio == null || spawn.Cell != sitio.Value.Cell) continue;

                if (!MapManager.IsCellWalkable(spawn.MapId, spawn.Cell))
                    throw new InvalidOperationException(
                        $"[RegressionGuard FAILED] El vendedor {spawn.NpcId} está puesto en la " +
                        $"casilla {spawn.Cell} del mapa {spawn.MapId}, que no se puede pisar. " +
                        "Ahí no hay quien lo cliquee.");

                if (puestos.TryGetValue(spawn.Cell, out int otro))
                    throw new InvalidOperationException(
                        $"[RegressionGuard FAILED] Los vendedores {otro} y {spawn.NpcId} están los " +
                        $"dos en la casilla {spawn.Cell}: se dibujarían uno encima del otro.");
                puestos[spawn.Cell] = spawn.NpcId;
            }

            // Y ninguno pegado a otro. Se mide en la rejilla del mapa, catorce de ancho.
            const int AnchoDelMapa = 14;
            var celdas = new List<int>(puestos.Keys);
            for (int i = 0; i < celdas.Count; i++)
            {
                for (int j = i + 1; j < celdas.Count; j++)
                {
                    int ax = celdas[i] % AnchoDelMapa, ay = celdas[i] / AnchoDelMapa;
                    int bx = celdas[j] % AnchoDelMapa, by = celdas[j] / AnchoDelMapa;
                    if (Math.Abs(ax - bx) > 1 || Math.Abs(ay - by) > 1) continue;
                    throw new InvalidOperationException(
                        $"[RegressionGuard FAILED] Los vendedores {puestos[celdas[i]]} y " +
                        $"{puestos[celdas[j]]} están pegados, en las casillas {celdas[i]} y " +
                        $"{celdas[j]}. El juego real casi nunca los pone así: 16 parejas vecinas " +
                        "de 512 medidas, el 3,1 %.");
                }
            }
        }

                        private static void AssertInteractiveRegistry()
        {
            var expected = new HashSet<(long MapId, int ElementId)>();
            foreach (long mapId in Managers.Interactives.MapIds)
            {
                foreach (var zaap in Managers.Interactives.ZaapElements(mapId))
                    expected.Add((mapId, zaap.Id));

                var chest = Managers.Merkasako.ChestOf(mapId);
                if (chest.Id != 0) expected.Add((mapId, chest.Id));

                var lottery = Managers.Lottery.Of(mapId);
                if (lottery.Id != 0) expected.Add((mapId, lottery.Id));

                // Los zaapis y las papeleras se reconocen por su gráfico y son decenas, así que van
                // en bloque. Sin esto la cuenta no cuadra y el servidor no arranca — que es lo que
                // pasó al añadirlos: el guardia los vio antes que nadie.
                foreach (var zaapi in Managers.Zaapis.ElementsOn(mapId))
                    expected.Add((mapId, zaapi.Id));

                foreach (var bin in Managers.Bins.On(mapId))
                    expected.Add((mapId, bin.Id));

                foreach (var door in Managers.Houses.On(mapId))
                    expected.Add((mapId, door.ElementId));

                foreach (var teleport in Managers.TeleportManager.On(mapId))
                {
                    expected.Add((mapId, teleport.ElementId));
                    if (Managers.Houses.TryGetDoor(mapId, teleport.ElementId, out _))
                        throw new InvalidOperationException(
                            "[RegressionGuard FAILED] Un paso genérico pisa una puerta de casa.");
                }

                foreach (var resource in Managers.Resources.On(mapId))
                    expected.Add((mapId, resource.ElementId));

                foreach (var interactive in Managers.InteractiveRegistry.OnMap(mapId))
                {
                    foreach (var action in interactive.Actions)
                    {
                        if (!Managers.InteractiveRegistry.TryResolveUse(
                                mapId, interactive.Element.Id, action.SkillInstanceId,
                                out var resolved, out var resolvedAction) ||
                            !ReferenceEquals(interactive, resolved) ||
                            !ReferenceEquals(action, resolvedAction))
                        {
                            throw new InvalidOperationException(
                                "[RegressionGuard FAILED] Interactive registry cannot resolve its own declaration.");
                        }
                    }

                    if (Managers.InteractiveRegistry.TryResolveUse(
                            mapId, interactive.Element.Id, int.MaxValue, out _, out _))
                    {
                        throw new InvalidOperationException(
                            "[RegressionGuard FAILED] Interactive registry accepted a mismatched skill instance.");
                    }
                }
            }

            // Los interiores de casa no estan en Interactives.MapIds -son mapas sin elementos
            // en el volcado del cliente- asi que se cuentan aparte.
            foreach (long interior in Managers.Houses.Interiors)
            {
                if (Managers.Houses.TryGetExit(interior, out var exit))
                    expected.Add((interior, exit.ElementId));
            }

            // Regla de Giny: cada paso es un elemento clicable con USE114, y la misma ruta se
            // encuentra por su casilla. Lo de la casilla ya no dispara nada —el enganche al jqi
            // se quedó fuera— pero el índice sigue existiendo y esto es lo que caza que dos rutas
            // acaben en la misma casilla, que es un dato malo, no una casualidad.
            foreach (var teleport in Managers.TeleportManager.All)
            {
                if (!Managers.InteractiveRegistry.TryResolveUse(
                        teleport.SourceMapId, teleport.ElementId,
                        Managers.Interactives.SkillInstanceOf(teleport.ElementId),
                        out var interactive, out var action) ||
                    interactive.Element.Id != teleport.ElementId ||
                    interactive.Element.Cell != teleport.SourceCellId ||
                    interactive.Element.Gfx != teleport.GfxId ||
                    interactive.Type != Managers.TeleportManager.GenericTeleportType ||
                    teleport.InteractiveType != Managers.TeleportManager.GenericTeleportType ||
                    action.Kind != Managers.InteractiveActionKind.Teleport ||
                    action.SkillId != 114 || teleport.SkillId != 114 ||
                    !Managers.TeleportManager.TryGetCellTrigger(
                        teleport.SourceMapId, teleport.SourceCellId, out var cellRoute) ||
                    !ReferenceEquals(teleport, cellRoute))
                {
                    throw new InvalidOperationException(
                        $"[RegressionGuard FAILED] El paso {teleport.SourceMapId}/" +
                        $"{teleport.ElementId} no es un interactivo clicable f11/f15.");
                }
            }

            // Tres rutas concretas, con sus números, para que un cambio en el catálogo no pase
            // desapercibido: la de Astrub al templo, la ida y vuelta del taller del joyero, y una
            // escalera —gfx 62018— que va exactamente por el mismo camino que un sol.
            if (!Managers.TeleportManager.TryGet(191106048, 515837, out var astrub) ||
                astrub.DestinationMapId != 192416776 || astrub.DestinationCellId != 534)
            {
                throw new InvalidOperationException(
                    "[RegressionGuard FAILED] Falta o ha cambiado la ruta de Astrub al templo.");
            }

            if (!Managers.TeleportManager.TryGet(188746247, 515801, out var jewellerEntrance) ||
                jewellerEntrance.DestinationMapId != 192937990 ||
                jewellerEntrance.DestinationCellId != 400 ||
                !Managers.TeleportManager.TryGet(192937990, 515742, out var jewellerExit) ||
                jewellerExit.DestinationMapId != 188746247 ||
                jewellerExit.SourceCellId != 414 || jewellerExit.DestinationCellId != 358 ||
                !Managers.TeleportManager.TryGetCellTrigger(192937990, 414, out var cellExit) ||
                !ReferenceEquals(jewellerExit, cellExit) ||
                !Managers.InteractiveRegistry.TryResolveUse(
                    192937990, 515742, Managers.Interactives.SkillInstanceOf(515742),
                    out var jewellerInteractive, out var jewellerAction) ||
                jewellerInteractive.Element.Cell != 414 || jewellerInteractive.Element.Gfx != 3520 ||
                jewellerInteractive.Type != Managers.TeleportManager.GenericTeleportType ||
                jewellerAction.Kind != Managers.InteractiveActionKind.Teleport ||
                jewellerAction.SkillId != 114)
            {
                throw new InvalidOperationException(
                    "[RegressionGuard FAILED] Falta o ha cambiado la ida y vuelta del taller del " +
                    "joyero de Astrub.");
            }

            if (!Managers.TeleportManager.TryGet(192940038, 515691, out var stairExit) ||
                stairExit.SourceCellId != 327 || stairExit.DestinationMapId != 188744711 ||
                stairExit.DestinationCellId != 427 || stairExit.GfxId != 62018 ||
                stairExit.InteractiveType != Managers.TeleportManager.GenericTeleportType ||
                stairExit.SkillId != 114 ||
                !Managers.TeleportManager.TryGetCellTrigger(192940038, 327, out var stairCellRoute) ||
                !ReferenceEquals(stairExit, stairCellRoute) ||
                !Managers.InteractiveRegistry.TryResolveUse(
                    192940038, 515691, Managers.Interactives.SkillInstanceOf(515691),
                    out var stairInteractive, out var stairAction) ||
                stairInteractive.Element.Gfx != 62018 || stairInteractive.Element.Cell != 327 ||
                stairInteractive.Type != Managers.TeleportManager.GenericTeleportType ||
                stairAction.Kind != Managers.InteractiveActionKind.Teleport ||
                stairAction.SkillId != 114)
            {
                throw new InvalidOperationException(
                    "[RegressionGuard FAILED] La escalera 192940038/515691 tiene que ser un paso " +
                    "clicable.");
            }

            if (Managers.InteractiveRegistry.Count != expected.Count)
            {
                throw new InvalidOperationException(
                    $"[RegressionGuard FAILED] Expected {expected.Count} interactives, got " +
                    $"{Managers.InteractiveRegistry.Count}.");
            }
        }

        private static void AssertProfessionCatalog()
        {
            if (Managers.JobManager.Count == 0 || Managers.SkillManager.Count == 0 ||
                Managers.RecipeManager.Count == 0)
                throw new InvalidOperationException(
                    "[RegressionGuard FAILED] Profession catalogue is empty.");

            foreach (var skill in Managers.SkillManager.All)
            {
                if (!Managers.JobManager.TryGet(skill.ParentJobId, out _))
                    throw new InvalidOperationException(
                        $"[RegressionGuard FAILED] Skill {skill.Id} references missing job {skill.ParentJobId}.");
            }

            foreach (var recipe in Managers.RecipeManager.All)
            {
                if (!Managers.JobManager.TryGet(recipe.JobId, out _) ||
                    !Managers.SkillManager.TryGet(recipe.SkillId, out _) ||
                    recipe.Ingredients.Count == 0 ||
                    recipe.Ingredients.Any(i => i.ItemId <= 0 || i.Quantity <= 0))
                    throw new InvalidOperationException(
                        $"[RegressionGuard FAILED] Recipe {recipe.ResultId} is inconsistent.");
            }

            // El catalogo tiene que traer habilidades de recoleccion y el mundo tiene que tener
            // recursos con esas habilidades. Antes esto llamaba a GatheringHandler.TryResolve,
            // que solo cruzaba tablas en memoria y no mandaba un byte; ahora el handler recolecta
            // de verdad y lo que hay que comprobar es que haya algo que recolectar.
            var gathering = Managers.SkillManager.All.FirstOrDefault(s => s.IsGathering);
            if (gathering == null)
                throw new InvalidOperationException(
                    "[RegressionGuard FAILED] El catalogo no trae ninguna habilidad de recoleccion.");

            if (Managers.Resources.Count == 0)
                throw new InvalidOperationException(
                    "[RegressionGuard FAILED] No hay ningun recurso recolectable en el mundo.");

            // Y la cantidad tiene que respetar lo medido: un oficio al tope sobre el recurso mas
            // facil da veinte, y uno recien empezado da cuatro.
            if (Handlers.GatheringHandler.Ceiling(200, 1) != 20 ||
                Handlers.GatheringHandler.Ceiling(200, 80) != 13 ||
                Handlers.GatheringHandler.Ceiling(1, 1) != 4)
                throw new InvalidOperationException(
                    "[RegressionGuard FAILED] La cantidad recolectada no cuadra con las capturas.");

            // Y la curva de experiencia, con los tres puntos que dan las capturas.
            if (Managers.JobExperience.Floor(2) != 20 || Managers.JobExperience.Floor(3) != 60 ||
                Managers.JobExperience.Floor(200) != 398000 ||
                Managers.JobExperience.LevelOf(20) != 2 || Managers.JobExperience.LevelOf(19) != 1)
                throw new InvalidOperationException(
                    "[RegressionGuard FAILED] La curva de experiencia de oficio no cuadra.");

            var craft = Managers.RecipeManager.All.First();
            if (!Handlers.CraftHandler.TryResolve(craft.SkillId, out _, out _, out var recipes, out _) ||
                !Handlers.CraftHandler.TryResolveRecipe(craft.SkillId, craft.ResultId, out _, out _) ||
                recipes.Count == 0)
                throw new InvalidOperationException(
                    "[RegressionGuard FAILED] Craft handler cannot resolve a known recipe.");
        }

        private static void AssertRelativeMapLookup()
        {
            var group = MapManager.Maps.Values
                .Where(m => m.MapId > 0)
                .GroupBy(m => (m.PosX, m.PosY))
                .FirstOrDefault(g => g.Count() > 1);
            if (group == null) return;

            var ordered = group.OrderBy(m => m.MapId).ToList();
            for (int i = 0; i < ordered.Count; i++)
            {
                var match = Managers.MapLookup.NextRelative(ordered[i].MapId);
                long expected = ordered[(i + 1) % ordered.Count].MapId;
                if (match == null || match.Map.MapId != expected ||
                    match.Candidates != ordered.Count ||
                    match.Wrapped != (i == ordered.Count - 1))
                    throw new InvalidOperationException(
                        "[RegressionGuard FAILED] Relative map cycle is not stable.");
            }
        }

            }
}
