<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <!-- Reference all assemblies in MelonLoader net6 folder for 3.6.10.10 -->
    <Reference Include="C:\Jondo 3.6.10.10\Cliente 3.6.10.10\MelonLoader\net6\*.dll">
      <Private>false</Private>
    </Reference>
    <!-- Reference all compiled Il2Cpp assemblies for 3.6.10.10 -->
    <Reference Include="C:\Jondo 3.6.10.10\Cliente 3.6.10.10\MelonLoader\Il2CppAssemblies\*.dll">
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
