using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using Jondo.Unity.Launcher;

namespace Jondo.Unity.World.Almanax
{
    /// <summary>One bonus of an Almanax day: its type, how much, and the conditions it applies under.</summary>
    public sealed class AlmanaxBonus
    {
        public int Id { get; init; }

        /// <summary>The client's bonus type. 1 is experience, 2 job experience, 16 drops...</summary>
        public int Type { get; init; }

        /// <summary>In percent.</summary>
        public int Amount { get; init; }

        /// <summary>[criterion type, value] pairs, as the client's bonus_criterions table gives them.</summary>
        public IReadOnlyList<(int Type, int Value)> Criteria { get; init; } = Array.Empty<(int, int)>();
    }

    /// <summary>One entry of the Almanax calendar.</summary>
    public sealed class AlmanaxDay
    {
        public int Id { get; init; }

        /// <summary>"dd/mm/yyyy" with "*" for any part: the days this entry covers.</summary>
        public IReadOnlyList<string> Dates { get; init; } = Array.Empty<string>();

        /// <summary>The saint of the day: the NPC the offering quest sends the player to.</summary>
        public int Saint { get; init; }

        /// <summary>The offering quest, "Ofrenda para ...".</summary>
        public int QuestId { get; init; }

        /// <summary>The objective that asks for the offering.</summary>
        public int ObjectiveId { get; init; }

        public int Category { get; init; }
        public long NameKey { get; init; }
        public long DescriptionKey { get; init; }

        public IReadOnlyList<AlmanaxBonus> Bonuses { get; init; } = Array.Empty<AlmanaxBonus>();

        /// <summary>Whether this entry names that day, and how precisely.</summary>
        /// <returns>0 when it does not; 2 when a pattern names the year too; 1 otherwise.</returns>
        public int Matches(DateTime date)
        {
            int best = 0;
            foreach (string pattern in Dates)
            {
                string[] parts = pattern.Split('/');
                if (parts.Length != 3) continue;

                if (!Part(parts[0], date.Day) || !Part(parts[1], date.Month) || !Part(parts[2], date.Year)) continue;
                best = Math.Max(best, parts[2] == "*" ? 1 : 2);
            }

            return best;
        }

        private static bool Part(string text, int value)
            => text == "*" || (int.TryParse(text, out int n) && n == value);
    }

    /// <summary>
    /// The Almanax calendar, read out of <c>datos/almanax_3.6.10.10.json</c>.
    /// </summary>
    /// <remarks>
    /// Generated by <c>tools/extract_almanax.py</c> from the client's own calendar. Each of the 376
    /// entries names its days, its saint and the objective that asks for the offering; the
    /// objective leads to one of 376 quests, "Ofrenda para &lt;saint&gt;", handed out by Ontoral Zo in
    /// the sanctuary and started on a condition of the form <c>PL&gt;19&amp;Ad=&lt;entry&gt;</c>.
    ///
    /// <b>Which entry is today's is this engine's reading, not a measurement.</b> Every day of the
    /// year is named by two entries: one of the twelve months' saints, which names it alone, and
    /// Bryss, whose four entries name 31 to 34 days each and whose own text says he stands in when
    /// the awaited saint does not come. Six days a year a third entry names the date with its year
    /// — the moveable feasts. The most precise wins: a date with its year over one without, and
    /// among those the entry that names the fewest days. That makes the month's saint the saint of
    /// the day, the feast win on its day, and Bryss what he says he is. No capture visits the
    /// sanctuary, so none of this is checked against the real server.
    /// </remarks>
    public sealed class AlmanaxCalendar
    {
        private readonly Dictionary<int, AlmanaxDay> _byId = new Dictionary<int, AlmanaxDay>();
        private readonly Dictionary<int, AlmanaxDay> _byQuest = new Dictionary<int, AlmanaxDay>();

        public AlmanaxCalendar(Action<string>? report = null)
        {
            string path = Paths.AlmanaxJson;
            if (!File.Exists(path))
            {
                report?.Invoke($"{Path.GetFileName(path)} is not there; there is no Almanax. " +
                               "Run tools/extract_almanax.py to build it.");
                return;
            }

            try
            {
                using var doc = JsonDocument.Parse(File.ReadAllText(path));
                if (!doc.RootElement.TryGetProperty("days", out var table)) return;

                foreach (var entry in table.EnumerateObject())
                {
                    if (!int.TryParse(entry.Name, out int id)) continue;
                    var row = entry.Value;

                    var dates = new List<string>();
                    if (row.TryGetProperty("dates", out var list) && list.ValueKind == JsonValueKind.Array)
                    {
                        foreach (var d in list.EnumerateArray()) dates.Add(d.GetString() ?? "");
                    }

                    var bonuses = new List<AlmanaxBonus>();
                    if (row.TryGetProperty("bonuses", out var blist) && blist.ValueKind == JsonValueKind.Array)
                    {
                        foreach (var b in blist.EnumerateArray())
                        {
                            var criteria = new List<(int, int)>();
                            if (b.TryGetProperty("criteria", out var clist) && clist.ValueKind == JsonValueKind.Array)
                            {
                                foreach (var c in clist.EnumerateArray())
                                {
                                    if (c.GetArrayLength() >= 2) criteria.Add((c[0].GetInt32(), c[1].GetInt32()));
                                }
                            }

                            bonuses.Add(new AlmanaxBonus
                            {
                                Id = (int)Long(b, "id"),
                                Type = (int)Long(b, "type"),
                                Amount = (int)Long(b, "amount"),
                                Criteria = criteria,
                            });
                        }
                    }

                    var day = new AlmanaxDay
                    {
                        Id = id,
                        Dates = dates,
                        Saint = (int)Long(row, "saint"),
                        QuestId = (int)Long(row, "quest"),
                        ObjectiveId = (int)Long(row, "objective"),
                        Category = (int)Long(row, "category"),
                        NameKey = Long(row, "name"),
                        DescriptionKey = Long(row, "description"),
                        Bonuses = bonuses,
                    };

                    _byId[id] = day;
                    if (day.QuestId != 0) _byQuest.TryAdd(day.QuestId, day);
                }
            }
            catch (Exception ex)
            {
                report?.Invoke($"{Path.GetFileName(path)} is unreadable: {ex.Message}");
            }
        }

        public bool Ready => _byId.Count > 0;
        public int Count => _byId.Count;

        public AlmanaxDay? Of(int id) => _byId.TryGetValue(id, out var day) ? day : null;

        /// <summary>Whether a quest is one of the offerings.</summary>
        public bool IsOffering(int questId) => _byQuest.ContainsKey(questId);

        /// <summary>The calendar entry of a date: see the remarks on the class for which one wins.</summary>
        public AlmanaxDay? DayOf(DateTime date)
        {
            AlmanaxDay? best = null;
            int bestPrecision = 0;

            foreach (var day in _byId.Values)
            {
                int precision = day.Matches(date);
                if (precision == 0) continue;

                bool better = best == null
                              || precision > bestPrecision
                              || (precision == bestPrecision && day.Dates.Count < best.Dates.Count)
                              || (precision == bestPrecision && day.Dates.Count == best.Dates.Count && day.Id < best.Id);
                if (!better) continue;

                best = day;
                bestPrecision = precision;
            }

            return best;
        }

        private static long Long(JsonElement row, string name)
            => row.TryGetProperty(name, out var v) && v.TryGetInt64(out long n) ? n : 0;
    }
}
