import { StrictMode, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import logoUrl from './jondo-logo.svg';
import './style.css';
import './asset-paths.css';

const VERSION = '3.6.10.10';
const blank = { endpoint: 'http://127.0.0.1:8888', clientPath: '', language: 'en', accounts: [] };
const api = window.jondo;
const copy = {
  en: { home:'HOME', settings:'SETTINGS', check:'CHECK SERVER', online:'SERVER ONLINE', server:'SERVER CONTROL URL', client:'DOFUS CLIENT', browse:'BROWSE', install:'INSTALL CLIENT SUPPORT', team:'YOUR TEAM', launch:'LAUNCH SELECTED', signIn:'SIGN IN', create:'CREATE ACCOUNT', user:'Username', nick:'Nickname', password:'Password', connected:'Connect to your server to start playing.', hero:'YOUR WORLD,', heroAccent:'YOUR RULES.', heroText:'Connect safely to your Jondo server and launch Dofus 3.', language:'GAME LANGUAGE', saved:'Settings saved.', supportPending:'Choose Dofus.exe to check client support.', signOut:'Sign out all accounts', back:'Back to home' },
  fr: { home:'ACCUEIL', settings:'PARAMÈTRES', check:'VÉRIFIER LE SERVEUR', online:'SERVEUR EN LIGNE', server:'URL DE CONTRÔLE DU SERVEUR', client:'CLIENT DOFUS', browse:'PARCOURIR', install:'INSTALLER LE SUPPORT CLIENT', team:'VOTRE ÉQUIPE', launch:'LANCER LA SÉLECTION', signIn:'CONNEXION', create:'CRÉER UN COMPTE', user:'Identifiant', nick:'Pseudo', password:'Mot de passe', connected:'Connectez-vous à votre serveur pour jouer.', hero:'VOTRE MONDE,', heroAccent:'VOS RÈGLES.', heroText:'Connectez-vous à votre serveur Jondo et lancez Dofus 3.', language:'LANGUE DU JEU', saved:'Paramètres enregistrés.', supportPending:'Choisissez Dofus.exe pour vérifier le support client.', signOut:'Déconnecter tous les comptes', back:'Retour à l’accueil' },
  es: { home:'INICIO', settings:'AJUSTES', check:'COMPROBAR SERVIDOR', online:'SERVIDOR EN LÍNEA', server:'URL DE CONTROL DEL SERVIDOR', client:'CLIENTE DOFUS', browse:'EXAMINAR', install:'INSTALAR SOPORTE DEL CLIENTE', team:'TU EQUIPO', launch:'INICIAR SELECCIÓN', signIn:'INICIAR SESIÓN', create:'CREAR CUENTA', user:'Usuario', nick:'Apodo', password:'Contraseña', connected:'Conéctate a tu servidor para empezar a jugar.', hero:'TU MUNDO,', heroAccent:'TUS REGLAS.', heroText:'Conéctate con seguridad a tu servidor Jondo e inicia Dofus 3.', language:'IDIOMA DEL JUEGO', saved:'Ajustes guardados.', supportPending:'Elige Dofus.exe para comprobar el soporte.', signOut:'Cerrar todas las sesiones', back:'Volver al inicio' },
};

function TitleBar() {
  const [maximized, setMaximized] = useState(false);
  useEffect(() => api.window.onMaximized(setMaximized), []);
  return <div className="titlebar"><div className="window-drag"><img src={logoUrl}/><span>Jondo Launcher</span></div><div className="window-actions"><button onClick={() => api.window.minimize()}>—</button><button onClick={() => api.window.toggleMaximize()}>{maximized ? '❐' : '□'}</button><button className="close" onClick={() => api.window.close()}>×</button></div></div>;
}

function App() {
  const [prefs, setPrefs] = useState(blank), [page, setPage] = useState('home'), [mode, setMode] = useState('login');
  const [form, setForm] = useState({ login: '', password: '', nickname: '' });
  const [notice, setNotice] = useState(copy.en.connected), [online, setOnline] = useState(false), [support, setSupport] = useState(null), [busy, setBusy] = useState(false);
  const text = copy[prefs.language] || copy.en;
  const save = async next => { const stored = await api.savePreferences(next); setPrefs(stored); return stored; };
  const checkServer = async () => { try { const result = await api.server.status(); setOnline(Boolean(result.enLinea)); setNotice(result.enLinea ? `Server ${result.version || VERSION} is online.` : 'The server is reachable but game services are still starting.'); } catch (error) { setOnline(false); setNotice(error.message); } };
  useEffect(() => { api.preferences().then(setPrefs).catch(error => setNotice(error.message)); }, []);
  useEffect(() => {
    checkServer();
    const timer = window.setInterval(checkServer, 15_000);
    return () => window.clearInterval(timer);
  }, [prefs.endpoint]);
  useEffect(() => { document.documentElement.lang = prefs.language || 'en'; }, [prefs.language]);
  useEffect(() => { if (prefs.clientPath) api.client.supportStatus(prefs.clientPath).then(setSupport).catch(() => setSupport(null)); else setSupport(null); }, [prefs.clientPath]);
  const chooseLanguage = async language => { const stored = await save({ ...prefs, language }); setNotice(`${copy[stored.language].language}: ${language.toUpperCase()}. Dofus will launch with --langCode ${language}.`); };
  const chooseClient = async () => { const clientPath = await api.client.choose(); if (clientPath) { await save({ ...prefs, clientPath }); setNotice(text.saved); } };
  const installSupport = async () => { setBusy(true); try { const result = await api.client.installSupport(prefs.clientPath); setSupport(result); setNotice(result.message); } catch (error) { setNotice(error.message); } finally { setBusy(false); } };
  const signIn = async event => { event.preventDefault(); setBusy(true); try { const result = mode === 'login' ? await api.account.signIn({ ...form, endpoint: prefs.endpoint }) : await api.account.register({ ...form, endpoint: prefs.endpoint }); if (!result.bien) throw new Error(result.motivo || 'The server rejected the request.'); if (mode === 'register') { setMode('login'); setNotice('Account created. Sign in with it now.'); return; } const account = { accountId: result.cuenta, login: form.login, nickname: result.apodo || form.login, token: result.token, selected: true }; await save({ ...prefs, endpoint: result.endpoint, accounts: [...prefs.accounts.filter(item => item.accountId !== account.accountId), account].slice(-8) }); setNotice(`Signed in as ${account.nickname}.`); } catch (error) { setNotice(error.message); } finally { setBusy(false); } };
  const launch = async () => { const accounts = prefs.accounts.filter(account => account.selected); if (!accounts.length) return setNotice('Select at least one saved account.'); if (!support?.ready) { setPage('settings'); return setNotice('Choose Dofus.exe and install client support in Settings first.'); } setBusy(true); try { for (const account of accounts) await api.client.launch({ endpoint: prefs.endpoint, clientPath: prefs.clientPath, token: account.token, language: prefs.language }); setNotice(`Launching ${accounts.length} Dofus client${accounts.length === 1 ? '' : 's'} in ${prefs.language.toUpperCase()}.`); } catch (error) { setNotice(error.message); } finally { setBusy(false); } };
  const toggleAccount = async accountId => save({ ...prefs, accounts: prefs.accounts.map(account => account.accountId === accountId ? { ...account, selected: !account.selected } : account) });

  const accountCard = prefs.accounts.length ? <><div className="card-title"><span>{text.team}</span><button className="text-button" onClick={() => setPage('settings')}>⚙ {text.settings}</button></div><div className="accounts">{prefs.accounts.map(account => <label key={account.accountId} className="account"><input type="checkbox" checked={Boolean(account.selected)} onChange={() => toggleAccount(account.accountId)} /><span>{account.nickname}<small>{account.login}</small></span></label>)}</div><button className="launch" disabled={busy} onClick={launch}>{busy ? 'WORKING…' : text.launch}</button><button className="link" onClick={() => save({ ...prefs, accounts: [] })}>{text.signOut}</button></> : <form onSubmit={signIn}><div className="tabs"><button type="button" className={mode === 'login' ? 'active' : ''} onClick={() => setMode('login')}>{text.signIn}</button><button type="button" className={mode === 'register' ? 'active' : ''} onClick={() => setMode('register')}>{text.create}</button></div><input required value={form.login} onChange={e => setForm({ ...form, login: e.target.value })} placeholder={text.user}/>{mode === 'register' && <input required value={form.nickname} onChange={e => setForm({ ...form, nickname: e.target.value })} placeholder={text.nick}/>}<input required type="password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} placeholder={text.password}/><button className="launch" disabled={busy}>{busy ? 'PLEASE WAIT…' : mode === 'login' ? text.signIn : text.create}</button><button className="link" type="button" onClick={() => setPage('settings')}>⚙ {text.settings}</button></form>;
  return <div className="shell"><TitleBar/><main className="app"><header><button className="brand" onClick={() => setPage('home')}><img src={logoUrl}/></button><nav><button className={page === 'home' ? 'active' : ''} onClick={() => setPage('home')}>{text.home}</button><button className={page === 'settings' ? 'active' : ''} onClick={() => setPage('settings')}>⚙ {text.settings}</button></nav><div className="header-language">{['en','fr','es'].map(language => <button key={language} className={prefs.language === language ? 'active' : ''} onClick={() => chooseLanguage(language)}>{language.toUpperCase()}</button>)}</div><button className={`online ${online ? 'yes' : ''}`} onClick={checkServer}><i />{online ? text.online : text.check}</button></header><section className="notice" role="status">{notice}</section>{page === 'home' ? <section className="home"><div className="hero"><div className="hero-copy"><p>{text.hero}<br/><em>{text.heroAccent}</em></p><span>{text.heroText}</span></div><small className="art-credit">DOFUS artwork · Ankama</small></div><aside className="card">{accountCard}</aside></section> : <section className="settings"><div className="settings-card"><div className="settings-heading"><div><h1>{text.settings}</h1><p>Server connection and local Dofus client setup.</p></div><button onClick={() => setPage('home')}>{text.back}</button></div><label>{text.server}</label><div className="row"><input value={prefs.endpoint} onChange={e => setPrefs({ ...prefs, endpoint: e.target.value })} onBlur={() => save(prefs)} placeholder="https://server.example"/><button onClick={checkServer}>{text.check}</button></div><label>{text.client}</label><div className="row"><input value={prefs.clientPath} readOnly placeholder="Choose Dofus.exe"/><button onClick={chooseClient}>{text.browse}</button></div><div className={`support ${support?.ready ? 'ready' : ''}`}><span>{support?.message || text.supportPending}</span><button disabled={!prefs.clientPath || busy || support?.ready} onClick={installSupport}>{text.install}</button></div></div></section>}</main></div>;
}
createRoot(document.getElementById('root')).render(<StrictMode><App /></StrictMode>);
