using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.Primitives;
using Avalonia.Controls.Templates;
using Avalonia.Layout;
using Avalonia.Media;
using Jondo.Unity.Launcher;
using Jondo.Unity.Studio.Controls;
using Jondo.Unity.Studio.Data;
using Jondo.Unity.Studio.Ui;
using Jondo.Unity.World.Content;

namespace Jondo.Unity.Studio.Pages
{
    /// <summary>
    /// Groups of monsters: the ones Ankama placed, and what somebody decides to do to them.
    /// </summary>
    /// <remarks>
    /// The first version of this screen could add a whole new group and delete an existing one, and
    /// nothing else. That is not editing — it is an encyclopedia with two buttons. What anybody
    /// actually wants is to open the group that is already there, take a monster out of it, put
    /// another one in, and move it two cells to the left.
    ///
    /// So the rule is <b>opening is free, changing forks</b>. Selecting one of Ankama's groups only
    /// reads it. The moment something is altered, that group is written off in the authored layer —
    /// a tombstone — and an authored copy carrying the change takes its place. That is the content
    /// layer doing the job it exists for: the 38,744 groups live in <c>world.db</c>, which is
    /// regenerated by tooling, so an edit made there would vanish the next time anybody rebuilt it
    /// and nothing would say so.
    ///
    /// Nothing reaches the disk until <em>Save</em>. Everything before that is a working set.
    /// </remarks>
    public sealed class MonsterGroupsPage : IStudioPage
    {
        private readonly WorldData _world;
        private readonly MonsterIcons _icons = new MonsterIcons();

        private readonly Dictionary<MobGroupKey, MobGroupSpawn> _placed
            = new Dictionary<MobGroupKey, MobGroupSpawn>();

        private readonly HashSet<MobGroupKey> _removed = new HashSet<MobGroupKey>();

        /// <summary>Which authored group replaced which of Ankama's, so a fork can be undone.</summary>
        private readonly Dictionary<MobGroupKey, MobGroupKey> _forkedFrom
            = new Dictionary<MobGroupKey, MobGroupKey>();

        private readonly NpcSprites _sprites = new NpcSprites();

        private readonly Dictionary<int, string> _npcNames = new Dictionary<int, string>();
        private readonly Dictionary<int, string> _npcLooks = new Dictionary<int, string>();

        private MonsterCatalogue? _catalogue;
        private MapCatalogue? _maps;
        private List<MonsterSummary> _monsters = new List<MonsterSummary>();
        private Dictionary<int, MonsterSummary> _byId = new Dictionary<int, MonsterSummary>();

        private bool _loaded;
        private bool _dirty;

        public MonsterGroupsPage(WorldData world) => _world = world;

        public string TitleKey => "nav.monsters";

        public override string ToString() => Words.T(TitleKey);

        /// <summary>A group as the list shows it, whoever it belongs to.</summary>
        private sealed record Row(MobGroupKey Key, int Cell, IReadOnlyList<MobMemberSpec> Members,
                                  bool Authored, bool Removed);

        /// <summary>The group being edited, and where it came from.</summary>
        private sealed class Draft
        {
            /// <summary>Null for a group that did not exist before.</summary>
            public MobGroupKey? Origin;

            public bool FromAnkama;
            public long MapId;
            public int Cell = -1;
            public readonly List<MobMemberSpec> Members = new List<MobMemberSpec>();

            public bool Placed => Cell >= 0;
        }

        public Control Build()
        {
            if (!_loaded) Load();

            if (_catalogue == null || !_catalogue.Ready)
            {
                var missing = new StackPanel { Spacing = 8 };
                missing.Children.Add(Skin.Heading(Words.T("missing.world")));
                missing.Children.Add(OverviewPage.Mono(Words.T("missing.lookedIn", Paths.WorldDb)));
                return Skin.Card(missing);
            }

            var groupList = new ListBox
            {
                ItemTemplate = new FuncDataTemplate<Row>((row, _) => GroupRow(row, Describe(row.Members)),
                                                          supportsRecycling: true),
            };
            ScrollViewer.SetHorizontalScrollBarVisibility(groupList, ScrollBarVisibility.Disabled);

            var memberList = new ListBox
            {
                ItemTemplate = new FuncDataTemplate<MobMemberSpec>(
                    (member, _) => MemberRow(member, NameOf(member), _icons.Of(GfxOf(member.MonsterId))),
                    supportsRecycling: true),
            };

            var grid = new CellGrid();
            var mapField = new MapField(_maps!, 330);
            var status = new TextBlock { Foreground = Skin.TextSoftBrush, VerticalAlignment = VerticalAlignment.Center };
            var save = new Button { Content = Words.T("mob.save"), IsEnabled = _dirty };

            var newGroup = new Button { Content = Words.T("mob.newGroup") };
            var gradePick = new ComboBox
            {
                Width = 106,
                ItemsSource = Enumerable.Range(1, MobGroupContent.MaxGrade + 1)
                                        .Select(n => Words.T("mob.grade", n)).ToList(),
                SelectedIndex = 0,
            };

            var dropMember = new Button { Content = Words.T("mob.removeFrom"), IsEnabled = false };
            var takeAway = new Button { Content = Words.T("mob.takeAway"), IsEnabled = false };
            var putBack = new Button { Content = Words.T("mob.putBack"), IsEnabled = false };
            var discard = new Button { Content = Words.T("mob.discard"), IsEnabled = false };
            var editingLabel = new TextBlock { Foreground = Skin.AuthoredBrush, FontSize = 12.5 };
            var hint = new TextBlock { Foreground = Skin.TextSoftBrush, TextWrapping = TextWrapping.Wrap };

            var view = new ToggleButton { Content = Words.T("common.editView"), MinWidth = 132 };

            long drawn = 0;
            var measured = new List<MeasuredGroup>();
            Draft? draft = null;
            Row? chosen = null;

            // ─── the working set ──────────────────────────────────────────────────

            List<Row> Rows()
            {
                var rows = new List<Row>();

                foreach (var group in measured)
                {
                    var key = new MobGroupKey(group.MapId, group.GroupId);

                    // One that was forked shows as its replacement, not as both.
                    if (_removed.Contains(key) && _forkedFrom.ContainsValue(key)) continue;

                    rows.Add(new Row(key, group.Cell,
                                     group.Members.Select(m => new MobMemberSpec
                                     {
                                         MonsterId = m.Monster,
                                         Grade = m.Grade,
                                     }).ToList(),
                                     false, _removed.Contains(key)));
                }

                foreach (var pair in _placed)
                {
                    if (pair.Key.MapId != drawn) continue;
                    rows.Add(new Row(pair.Key, pair.Value.Cell, pair.Value.Members, true, false));
                }

                rows.Sort((a, b) => a.Cell.CompareTo(b.Cell));
                return rows;
            }

            void Redraw()
            {
                grid.Show(drawn != 0 && _world.Maps.TryGetValue(drawn, out var cells) ? cells : null);

                var marks = new Dictionary<int, CellMark>();

                // The NPCs too: a group standing on a merchant is a mistake nobody sees until the
                // map is open in the game.
                if (drawn != 0)
                {
                    foreach (var pair in _world.NpcPlacements.Rows)
                    {
                        if (pair.Key.MapId != drawn) continue;
                        marks[pair.Key.Cell] = new CellMark
                        {
                            Colour = new SolidColorBrush(Color.FromArgb(0x99, 0x5F, 0xA8, 0xD3)),
                            Label = Short(_npcNames.TryGetValue(pair.Key.NpcId, out string? who) && who.Length > 0
                                ? who
                                : Words.T("cells.npcHere")),
                            Icon = _npcLooks.TryGetValue(pair.Key.NpcId, out string? look)
                                ? _sprites.Of(look) : null,
                        };
                    }
                }

                foreach (var row in Rows())
                {
                    marks[row.Cell] = new CellMark
                    {
                        Colour = row.Removed ? Skin.WrongBrush : (row.Authored ? Skin.AuthoredBrush : Skin.DoneBrush),
                        Label = Short(Describe(row.Members)),
                        Faded = row.Removed,
                        Icon = row.Removed || row.Members.Count == 0
                            ? null
                            : _icons.Of(GfxOf(row.Members[0].MonsterId)),
                    };
                }

                grid.Mark(marks);
                grid.Select(draft is { Placed: true } ? draft.Cell : chosen?.Cell ?? -1);

                grid.Preview(draft == null || draft.Members.Count == 0 || drawn == 0
                    ? null
                    : new CellMark
                    {
                        Colour = Skin.AuthoredBrush,
                        Label = Short(Describe(draft.Members)),
                        Icon = _icons.Of(GfxOf(draft.Members[0].MonsterId)),
                    });
            }

            void Hint()
            {
                if (drawn == 0) { hint.Text = Words.T("mob.hintNoMap"); return; }
                if (draft == null) { hint.Text = Words.T("mob.hintOpen"); return; }

                hint.Text = draft.Placed ? Words.T("mob.hintMove") : Words.T("mob.hintDrop");
            }

            void ShowAll()
            {
                var rows = Rows();
                groupList.ItemsSource = rows;
                memberList.ItemsSource = draft == null
                    ? Array.Empty<MobMemberSpec>()
                    : draft.Members.ToList();

                bool editing = draft != null;
                gradePick.IsEnabled = editing;
                discard.IsEnabled = editing;
                dropMember.IsEnabled = editing && memberList.SelectedItem != null;

                takeAway.IsEnabled = chosen is { Removed: false };
                putBack.IsEnabled = chosen is { Removed: true };

                editingLabel.Text = draft == null
                    ? Words.T("mob.nothingOpen")
                    : (draft.Origin == null
                           ? Words.T("mob.editingNew", draft.Members.Count)
                           : Words.T("mob.editingOne", draft.Members.Count,
                                     draft.FromAnkama ? Words.T("mob.ankama") : Words.T("common.authored")));

                var text = new StringBuilder();
                text.Append(drawn == 0
                    ? Words.T("mob.hintNoMap")
                    : Words.T("mob.here", drawn, rows.Count(r => !r.Authored), rows.Count(r => r.Authored)));
                text.Append("   ·   ").Append(Words.T("mob.everywhere", _placed.Count, _removed.Count));
                if (_dirty) text.Append("   ·   ").Append(Words.T("common.unsaved"));

                status.Text = text.ToString();
                save.IsEnabled = _dirty;

                Redraw();
                Hint();
            }

            void Touch()
            {
                _dirty = true;
                ShowAll();
            }

            // Writes the draft back into the working set, forking Ankama's group if need be.
            void Commit()
            {
                if (draft == null || !draft.Placed) return;

                MobGroupKey key;
                if (draft.Origin is { } mine && !draft.FromAnkama)
                {
                    key = mine;
                }
                else
                {
                    // Ankama's is written off and an authored copy takes its place. The tombstone
                    // is what makes the change survive the next regeneration of the database the
                    // original lives in.
                    key = new MobGroupKey(draft.MapId, MobGroupContent.NextId(_placed.Values));

                    if (draft.Origin is { } ankama)
                    {
                        _removed.Add(ankama);
                        _forkedFrom[key] = ankama;
                    }

                    draft.Origin = key;
                    draft.FromAnkama = false;
                }

                _placed[key] = new MobGroupSpawn
                {
                    MapId = draft.MapId,
                    GroupId = key.GroupId,
                    Cell = draft.Cell,
                    Members = draft.Members.ToArray(),
                };

                Touch();
            }

            void Open(Row row)
            {
                draft = new Draft
                {
                    Origin = row.Key,
                    FromAnkama = !row.Authored,
                    MapId = drawn,
                    Cell = row.Cell,
                };

                draft.Members.AddRange(row.Members);
                ShowAll();
            }

            void OpenMap(long mapId)
            {
                drawn = mapId;
                mapField.Set(mapId);
                measured = mapId == 0 ? new List<MeasuredGroup>() : _catalogue.GroupsOn(mapId);
                draft = null;
                chosen = null;
                ShowAll();
            }

            // ─── what the controls do ─────────────────────────────────────────────

            mapField.Chosen += place => OpenMap(place.MapId);

            view.IsCheckedChanged += (_, _) =>
            {
                bool game = view.IsChecked == true;
                grid.View = game ? GridView.Game : GridView.Editing;
                view.Content = game ? Words.T("common.gameView") : Words.T("common.editView");
            };

            groupList.SelectionChanged += (_, _) =>
            {
                chosen = groupList.SelectedItem as Row;

                // Selecting opens it for editing straight away. A separate "edit" button would be
                // one more click for the only thing anybody clicks a row to do.
                if (chosen is { Removed: false }) Open(chosen);
                else ShowAll();
            };

            memberList.SelectionChanged += (_, _)
                => dropMember.IsEnabled = draft != null && memberList.SelectedItem != null;

            var picker = Picker.Of(_monsters,
                                   monster => monster.Name.Length > 0 ? monster.Name : monster.Id.ToString(),
                                   monster => monster.Id, Words.T("mob.pick"),
                                   monster =>
                                   {
                                       // Adding to nothing starts a new group rather than doing
                                       // nothing, because "put a Gobbly somewhere" is one thought.
                                       draft ??= new Draft { MapId = drawn };

                                       draft.Members.Add(new MobMemberSpec
                                       {
                                           MonsterId = monster.Id,
                                           Grade = Math.Clamp(gradePick.SelectedIndex, 0, MobGroupContent.MaxGrade),
                                       });

                                       if (draft.Placed) Commit();
                                       else ShowAll();
                                   },
                                   300,
                                   monster => _icons.Of(monster.GfxId));

            newGroup.Click += (_, _) =>
            {
                draft = new Draft { MapId = drawn };
                chosen = null;
                groupList.SelectedItem = null;
                ShowAll();
            };

            dropMember.Click += (_, _) =>
            {
                if (draft == null || memberList.SelectedItem is not MobMemberSpec member) return;

                draft.Members.Remove(member);

                // A group with nobody in it is not a group. Emptying it takes it out of the world,
                // which is what taking the last monster out means.
                if (draft.Members.Count == 0 && draft.Origin is { } origin)
                {
                    if (draft.FromAnkama) _removed.Add(origin);
                    else _placed.Remove(origin);

                    draft = null;
                    chosen = null;
                    groupList.SelectedItem = null;
                    Touch();
                    return;
                }

                if (draft.Placed) Commit();
                else ShowAll();
            };

            discard.Click += (_, _) =>
            {
                draft = null;
                chosen = null;
                groupList.SelectedItem = null;
                ShowAll();
            };

            grid.Clicked += cell =>
            {
                if (drawn == 0 || draft == null) return;

                draft.Cell = cell;
                if (draft.Members.Count == 0) { ShowAll(); return; }

                Commit();
            };

            takeAway.Click += (_, _) =>
            {
                if (chosen == null) return;

                if (chosen.Authored) _placed.Remove(chosen.Key);
                else _removed.Add(chosen.Key);

                draft = null;
                chosen = null;
                groupList.SelectedItem = null;
                Touch();
            };

            putBack.Click += (_, _) =>
            {
                if (chosen is not { Removed: true }) return;

                _removed.Remove(chosen.Key);

                // If it was forked rather than simply deleted, the replacement goes too — otherwise
                // putting Ankama's group back leaves two standing on the same cell.
                foreach (var pair in _forkedFrom.Where(p => p.Value.Equals(chosen.Key)).ToList())
                {
                    _placed.Remove(pair.Key);
                    _forkedFrom.Remove(pair.Key);
                }

                draft = null;
                chosen = null;
                groupList.SelectedItem = null;
                Touch();
            };

            save.Click += (_, _) =>
            {
                try
                {
                    MobGroupContent.Save(Paths.ContentFile(MobGroupContent.AuthoredFile), _placed.Values, _removed);
                    _dirty = false;
                    ShowAll();
                    status.Text += "   ·   " + Words.T("common.saved");
                }
                catch (Exception ex)
                {
                    status.Text = Words.T("common.couldNotSave", ex.Message);
                }
            };

            var top = new WrapPanel { Margin = new Thickness(0, 0, 0, 12) };
            foreach (var control in new Control[] { save, newGroup, picker, gradePick, dropMember,
                                                    takeAway, putBack, discard, view, status })
            {
                control.Margin = new Thickness(0, 0, 12, 6);
                control.VerticalAlignment = VerticalAlignment.Center;
                top.Children.Add(control);
            }

            var left = new Grid { RowDefinitions = new RowDefinitions("*,Auto,Auto,180") };
            Grid.SetRow(groupList, 0);

            var partyLabel = Skin.Heading(Words.T("mob.members"));
            partyLabel.Margin = new Thickness(0, 12, 0, 4);
            Grid.SetRow(partyLabel, 1);

            editingLabel.Margin = new Thickness(0, 0, 0, 6);
            Grid.SetRow(editingLabel, 2);
            Grid.SetRow(memberList, 3);

            left.Children.Add(groupList);
            left.Children.Add(partyLabel);
            left.Children.Add(editingLabel);
            left.Children.Add(memberList);

            // The map gets the room, not the table. See Ui.Zoomer for why that needed saying.
            var above = new WrapPanel();
            mapField.Margin = new Thickness(0, 0, 12, 6);
            above.Children.Add(mapField);
            above.Children.Add(Zoomer.For(grid));

            var board = new DockPanel { LastChildFill = true, Margin = new Thickness(12, 0, 0, 0) };
            DockPanel.SetDock(above, Dock.Top);
            hint.Margin = new Thickness(0, 6, 0, 8);
            DockPanel.SetDock(hint, Dock.Top);

            var key = Legend();
            key.Margin = new Thickness(0, 8, 0, 0);
            DockPanel.SetDock(key, Dock.Bottom);

            board.Children.Add(above);
            board.Children.Add(hint);
            board.Children.Add(key);
            board.Children.Add(new ScrollViewer
            {
                Content = grid,
                HorizontalScrollBarVisibility = ScrollBarVisibility.Auto,
                VerticalScrollBarVisibility = ScrollBarVisibility.Auto,
            });

            var split = new Grid { ColumnDefinitions = new ColumnDefinitions("420,8,*") };
            Grid.SetColumn(left, 0);
            Grid.SetColumn(board, 2);
            split.Children.Add(left);
            split.Children.Add(board);

            var layout = new DockPanel { LastChildFill = true };
            DockPanel.SetDock(top, Dock.Top);
            layout.Children.Add(top);
            layout.Children.Add(split);

            ShowAll();
            return layout;
        }

        private void Load()
        {
            _catalogue = new MonsterCatalogue(_world.Text, _world.Complaints.Add);
            _maps = new MapCatalogue(_world.Text, _world.Complaints.Add, _world.NpcsPerMap());

            // The NPCs too, by name and by look: a monster group standing on a merchant is the
            // mistake this screen exists to catch, and "un NPC" on a grey diamond does not catch it.
            using (var npcs = new NpcCatalogue(_world.Text, _world.Complaints.Add))
            {
                if (npcs.Ready)
                {
                    foreach (var npc in npcs.All())
                    {
                        _npcNames[npc.Id] = npc.Name;
                        _npcLooks[npc.Id] = npc.Look;
                    }
                }
            }

            _monsters = _catalogue.Ready ? _catalogue.All() : new List<MonsterSummary>();
            _byId = _monsters.ToDictionary(monster => monster.Id);

            var stored = MobGroupContent.Load(Paths.ContentFile(MobGroupContent.AuthoredFile),
                                              _world.Complaints.Add);
            foreach (var pair in stored.Rows) _placed[pair.Key] = pair.Value.Value;
            foreach (var key in stored.ErasedKeys) _removed.Add(key);

            _loaded = true;
        }

        private int GfxOf(int monsterId)
            => _byId.TryGetValue(monsterId, out var monster) ? monster.GfxId : 0;

        private string NameOf(MobMemberSpec member)
            => _byId.TryGetValue(member.MonsterId, out var monster) && monster.Name.Length > 0
                ? monster.Name + (monster.Toothless ? "  ·  " + Words.T("mob.noSpells") : "")
                : member.MonsterId.ToString();

        private string Describe(IReadOnlyList<MobMemberSpec> members)
        {
            if (members.Count == 0) return "(∅)";

            var names = new List<string>(members.Count);
            foreach (var member in members)
            {
                names.Add(_byId.TryGetValue(member.MonsterId, out var known) && known.Name.Length > 0
                    ? known.Name
                    : member.MonsterId.ToString());
            }

            return string.Join(", ", names);
        }

        private static string Short(string text)
            => text.Length <= 16 ? text : text[..15] + "…";

        private static Control Legend()
        {
            var row = new WrapPanel();
            row.Children.Add(Skin.Key(Skin.DoneBrush, Words.T("mob.ankama")));
            row.Children.Add(Skin.Key(Skin.AuthoredBrush, Words.T("common.authored")));
            row.Children.Add(Skin.Key(Skin.WrongBrush, Words.T("common.removed")));
            row.Children.Add(Skin.Key(Skin.MeasuredBrush, Words.T("cells.npcHere")));
            return row;
        }

        private static Control GroupRow(Row row, string members)
        {
            var line = new Grid { ColumnDefinitions = new ColumnDefinitions("50,104,*") };

            var cell = Skin.Fixed(row.Cell.ToString(), Skin.TextBrush);
            cell.VerticalAlignment = VerticalAlignment.Top;
            Grid.SetColumn(cell, 0);
            line.Children.Add(cell);

            var what = Skin.Fixed(
                row.Removed ? Words.T("common.removed")
                            : (row.Authored ? Words.T("common.authored") : Words.T("mob.ankama")),
                row.Removed ? Skin.WrongBrush : (row.Authored ? Skin.AuthoredBrush : Skin.TextFaintBrush));
            what.VerticalAlignment = VerticalAlignment.Top;
            Grid.SetColumn(what, 1);
            line.Children.Add(what);

            var who = new TextBlock
            {
                Text = members,
                Foreground = row.Removed ? Skin.TextFaintBrush : Skin.TextBrush,
                TextWrapping = TextWrapping.Wrap,
                FontSize = 12.5,
            };
            Grid.SetColumn(who, 2);
            line.Children.Add(who);

            return line;
        }

        private static Control MemberRow(MobMemberSpec member, string name, IImage? picture)
        {
            var line = new Grid { ColumnDefinitions = new ColumnDefinitions("40,70,*") };

            if (picture != null)
            {
                var shown = new Image
                {
                    Source = picture,
                    Width = 32,
                    Height = 32,
                    VerticalAlignment = VerticalAlignment.Center,
                };
                Grid.SetColumn(shown, 0);
                line.Children.Add(shown);
            }

            var grade = Skin.Fixed(Words.T("mob.grade", member.Grade + 1), Skin.TextFaintBrush);
            grade.VerticalAlignment = VerticalAlignment.Center;
            Grid.SetColumn(grade, 1);
            line.Children.Add(grade);

            var who = new TextBlock
            {
                Text = name,
                Foreground = Skin.TextBrush,
                FontSize = 12.5,
                VerticalAlignment = VerticalAlignment.Center,
                TextTrimming = TextTrimming.CharacterEllipsis,
            };
            Grid.SetColumn(who, 2);
            line.Children.Add(who);

            return line;
        }
    }
}
